#!/bin/sh
# GENERATED by `gleam run -m generate` in drills/ - do not edit.
# Runs every Haskell solution variant against its harness:
#   ./verify_all.sh     (from drills/haskell)
# Each .verify/<stem> directory compiles alone; its report is the last
# line, a JSON object whose error is null and whose cases all passed.
cd "$(dirname "$0")" || exit 1
count=0
failures=0
while IFS='|' read -r module label stem; do
  [ -z "$stem" ] && continue
  count=$((count + 1))
  report=$(cd ".verify/$stem" && timeout -s KILL 30 sh -c 'ghc -v0 -O0 -o run.bin Harness.hs && ./run.bin' 2>&1 | tail -n 1)
  [ -z "$report" ] && report='timed out'
  case "$report" in
    *'"error":null'*) ;;
    *) failures=$((failures + 1)); echo "FAIL $module [$label] $report"; continue ;;
  esac
  case "$report" in
    *'"cases":[]'*) failures=$((failures + 1)); echo "FAIL $module [$label] harness produced no cases" ;;
    *'"passed":false'*) failures=$((failures + 1)); echo "FAIL $module [$label] $report" ;;
  esac
done <<'VARIANTS'
nc01_contains_duplicate|Hash Set|nc01_contains_duplicate
VARIANTS
echo "$count Haskell variants checked, $failures failures"
[ "$failures" -eq 0 ]
