#!/bin/sh
# GENERATED by `gleam run -m generate` in drills/ - do not edit.
# Runs every Haskell solution variant against its harness:
#   ./verify_all.sh     (from drills/haskell)
# Each .verify/<stem> directory compiles alone; its report is the last
# line, a JSON object whose error is null and whose cases all passed.
cd "$(dirname "$0")" || exit 1
count=0
failures=0
while IFS='|' read -r module label stem; do
  [ -z "$stem" ] && continue
  count=$((count + 1))
  report=$(cd ".verify/$stem" && timeout -s KILL 30 sh -c 'ghc -v0 -O0 -o run.bin Harness.hs && ./run.bin' 2>&1 | tail -n 1)
  [ -z "$report" ] && report='timed out'
  case "$report" in
    *'"error":null'*) ;;
    *) failures=$((failures + 1)); echo "FAIL $module [$label] $report"; continue ;;
  esac
  case "$report" in
    *'"cases":[]'*) failures=$((failures + 1)); echo "FAIL $module [$label] harness produced no cases" ;;
    *'"passed":false'*) failures=$((failures + 1)); echo "FAIL $module [$label] $report" ;;
  esac
done <<'VARIANTS'
nc01_contains_duplicate|Hash Set|nc01_contains_duplicate
nc02_valid_anagram|Count Map|nc02_valid_anagram
nc03_two_sum|Hash Map|nc03_two_sum
nc04_group_anagrams|Count Key|nc04_group_anagrams
nc05_top_k_frequent|Bucket Sort|nc05_top_k_frequent
nc06_product_except_self|Prefix & Suffix Products|nc06_product_except_self
nc07_longest_consecutive|Hash Set|nc07_longest_consecutive
nc08_valid_palindrome|Two Pointers|nc08_valid_palindrome
nc09_two_sum_sorted|Two Pointers|nc09_two_sum_sorted
nc100_edit_distance|Space-Saving DP|nc100_edit_distance
nc101_burst_balloons|Top-Down Memo|nc101_burst_balloons
nc102_regular_expression_matching|Top-Down Memo|nc102_regular_expression_matching
nc103_implement_trie|Trie|nc103_implement_trie
nc104_word_dictionary|Trie|nc104_word_dictionary
nc105_word_search_ii|Trie|nc105_word_search_ii
nc106_number_of_islands|DFS|nc106_number_of_islands
nc107_clone_graph|BFS|nc107_clone_graph
nc108_max_area_of_island|DFS|nc108_max_area_of_island
nc109_pacific_atlantic|BFS|nc109_pacific_atlantic
nc10_three_sum|Sort + Two Pointers|nc10_three_sum
nc110_surrounded_regions|Boundary DFS|nc110_surrounded_regions
nc111_rotting_oranges|Multi-Source BFS|nc111_rotting_oranges
nc112_walls_and_gates|Multi-Source BFS|nc112_walls_and_gates
nc113_course_schedule|Topological Sort|nc113_course_schedule
nc114_course_schedule_ii|Topological Sort|nc114_course_schedule_ii
nc115_redundant_connection|Union-Find|nc115_redundant_connection
nc116_connected_components|Union-Find|nc116_connected_components
nc117_graph_valid_tree|DFS|nc117_graph_valid_tree
nc118_word_ladder|BFS|nc118_word_ladder
nc119_reconstruct_itinerary|Hierholzer|nc119_reconstruct_itinerary
nc11_container_water|Two Pointers|nc11_container_water
nc120_min_cost_connect_points|Prim|nc120_min_cost_connect_points
nc121_network_delay_time|Dijkstra|nc121_network_delay_time
nc122_swim_in_water|Dijkstra|nc122_swim_in_water
nc123_alien_dictionary|Topological Sort|nc123_alien_dictionary
nc124_cheapest_flights|Bellman-Ford|nc124_cheapest_flights
nc125_reverse_linked_list|Iterative|nc125_reverse_linked_list
nc126_merge_two_sorted_lists|Iterative|nc126_merge_two_sorted_lists
nc127_reorder_list|Fast & Slow Pointers|nc127_reorder_list
nc128_remove_nth_from_end|Two Pointers|nc128_remove_nth_from_end
nc129_copy_random_list|Hash Map|nc129_copy_random_list
nc12_best_time_stock|Greedy|nc12_best_time_stock
nc130_add_two_numbers|Simulation|nc130_add_two_numbers
nc131_linked_list_cycle|Fast & Slow Pointers|nc131_linked_list_cycle
nc132_find_the_duplicate|Fast & Slow Pointers|nc132_find_the_duplicate
nc133_lru_cache|Nifty Python · Dict Order|nc133_lru_cache
nc134_merge_k_sorted_lists|Divide & Conquer|nc134_merge_k_sorted_lists
nc135_reverse_k_group|Linked List|nc135_reverse_k_group
nc136_invert_binary_tree|DFS|nc136_invert_binary_tree
nc137_maximum_depth|DFS|nc137_maximum_depth
nc138_diameter_of_binary_tree|DFS|nc138_diameter_of_binary_tree
nc139_balanced_binary_tree|DFS|nc139_balanced_binary_tree
nc13_longest_substring|Sliding Window|nc13_longest_substring
nc140_same_tree|DFS|nc140_same_tree
nc141_subtree_of_another_tree|DFS|nc141_subtree_of_another_tree
nc142_lowest_common_ancestor_bst|BST Walk|nc142_lowest_common_ancestor_bst
nc143_level_order_traversal|BFS|nc143_level_order_traversal
nc144_right_side_view|BFS|nc144_right_side_view
nc145_count_good_nodes|DFS|nc145_count_good_nodes
nc146_validate_bst|DFS|nc146_validate_bst
nc147_kth_smallest_bst|Iterative In-Order|nc147_kth_smallest_bst
nc148_build_tree_preorder_inorder|Recursion|nc148_build_tree_preorder_inorder
nc149_max_path_sum|DFS|nc149_max_path_sum
nc14_character_replacement|Sliding Window|nc14_character_replacement
nc150_serialize_deserialize|Pre-Order DFS|nc150_serialize_deserialize
nc15_permutation_in_string|Sliding Window|nc15_permutation_in_string
nc16_valid_parentheses|Stack|nc16_valid_parentheses
nc17_min_stack|Two Stacks|nc17_min_stack
nc18_daily_temperatures|Monotonic Stack|nc18_daily_temperatures
nc19_binary_search|Binary Search|nc19_binary_search
nc20_find_min_rotated|Binary Search|nc20_find_min_rotated
nc21_search_rotated|Binary Search|nc21_search_rotated
nc22_encode_decode|Length Prefix|nc22_encode_decode
nc23_valid_sudoku|One Pass + Seen Set|nc23_valid_sudoku
nc24_trapping_rain_water|Two Pointers|nc24_trapping_rain_water
nc25_min_window_substring|Sliding Window|nc25_min_window_substring
nc26_sliding_window_maximum|Prefix & Suffix Maxima|nc26_sliding_window_maximum
nc27_eval_rpn|Stack|nc27_eval_rpn
nc28_generate_parentheses|Backtracking|nc28_generate_parentheses
nc29_car_fleet|Sort + Greedy|nc29_car_fleet
nc30_largest_rectangle|Monotonic Stack|nc30_largest_rectangle
nc31_search_2d_matrix|Binary Search|nc31_search_2d_matrix
nc32_koko_bananas|Binary Search|nc32_koko_bananas
nc33_time_map|Binary Search|nc33_time_map
nc34_median_two_sorted|Two Pointers|nc34_median_two_sorted
nc35_insert_interval|Intervals|nc35_insert_interval
nc36_merge_intervals|Intervals|nc36_merge_intervals
nc37_non_overlapping|Greedy|nc37_non_overlapping
nc38_meeting_rooms|Sorting|nc38_meeting_rooms
nc39_meeting_rooms_ii|Sweep Line|nc39_meeting_rooms_ii
nc40_min_interval|Brute Force|nc40_min_interval
nc41_maximum_subarray|Kadane|nc41_maximum_subarray
nc42_jump_game|Greedy|nc42_jump_game
nc43_jump_game_ii|Greedy|nc43_jump_game_ii
nc44_gas_station|Greedy|nc44_gas_station
nc45_hand_of_straights|Greedy|nc45_hand_of_straights
nc46_merge_triplets|Greedy|nc46_merge_triplets
nc47_partition_labels|Greedy|nc47_partition_labels
nc48_valid_parenthesis_string|Greedy|nc48_valid_parenthesis_string
nc49_single_number|Bit Manipulation|nc49_single_number
nc50_number_of_one_bits|Bit Manipulation|nc50_number_of_one_bits
nc51_counting_bits|Bottom-Up DP|nc51_counting_bits
nc52_reverse_bits|Bit Manipulation|nc52_reverse_bits
nc53_missing_number|Bit Manipulation|nc53_missing_number
nc54_sum_of_two_integers|Bit Manipulation|nc54_sum_of_two_integers
nc55_reverse_integer|Math|nc55_reverse_integer
nc56_rotate_image|Nifty Python · Zip|nc56_rotate_image
nc57_spiral_matrix|Nifty Python · Rotate|nc57_spiral_matrix
nc58_set_matrix_zeroes|Hash Set|nc58_set_matrix_zeroes
nc59_happy_number|Hash Set|nc59_happy_number
nc60_plus_one|Math|nc60_plus_one
nc61_pow|Binary Exponentiation|nc61_pow
nc62_multiply_strings|Math|nc62_multiply_strings
nc63_detect_squares|Hash Map|nc63_detect_squares
nc64_climbing_stairs|Space-Saving DP|nc64_climbing_stairs
nc65_min_cost_climbing_stairs|Space-Saving DP|nc65_min_cost_climbing_stairs
nc66_house_robber|Space-Saving DP|nc66_house_robber
nc67_house_robber_ii|Space-Saving DP|nc67_house_robber_ii
nc68_longest_palindrome|Centre Expansion|nc68_longest_palindrome
nc69_palindromic_substrings|Centre Expansion|nc69_palindromic_substrings
nc70_decode_ways|Space-Saving DP|nc70_decode_ways
nc71_coin_change|Bottom-Up DP|nc71_coin_change
nc72_maximum_product_subarray|Space-Saving DP|nc72_maximum_product_subarray
nc73_word_break|Bottom-Up DP|nc73_word_break
nc74_longest_increasing_subsequence|Bottom-Up DP|nc74_longest_increasing_subsequence
nc75_partition_equal_subset|Bottom-Up DP|nc75_partition_equal_subset
nc76_kth_largest_stream|Heap|nc76_kth_largest_stream
nc77_last_stone_weight|Heap|nc77_last_stone_weight
nc78_k_closest_points|Sorting|nc78_k_closest_points
nc79_kth_largest_array|Sorting|nc79_kth_largest_array
nc80_task_scheduler|Greedy|nc80_task_scheduler
nc81_design_twitter|Design|nc81_design_twitter
nc82_find_median_stream|Two Heaps|nc82_find_median_stream
nc83_subsets|Recursion|nc83_subsets
nc84_combination_sum|Backtracking|nc84_combination_sum
nc85_permutations|Backtracking|nc85_permutations
nc86_subsets_ii|Backtracking|nc86_subsets_ii
nc87_combination_sum_ii|Backtracking|nc87_combination_sum_ii
nc88_word_search|Backtracking|nc88_word_search
nc89_palindrome_partitioning|Backtracking|nc89_palindrome_partitioning
nc90_letter_combinations|Recursion|nc90_letter_combinations
nc91_n_queens|Backtracking|nc91_n_queens
nc92_unique_paths|Space-Saving DP|nc92_unique_paths
nc93_longest_common_subsequence|Space-Saving DP|nc93_longest_common_subsequence
nc94_coin_change_ii|Bottom-Up DP|nc94_coin_change_ii
nc95_target_sum|Bottom-Up DP|nc95_target_sum
nc96_stock_with_cooldown|State Machine DP|nc96_stock_with_cooldown
nc97_interleaving_string|Top-Down Memo|nc97_interleaving_string
nc98_longest_increasing_path|DFS + Memo|nc98_longest_increasing_path
nc99_distinct_subsequences|Space-Saving DP|nc99_distinct_subsequences
VARIANTS
echo "$count Haskell variants checked, $failures failures"
[ "$failures" -eq 0 ]
