# GENERATED by `gleam run -m generate` in drills/ - do not edit.
# Runs every Python solution variant against its harness:
#   python3 verify_all.py     (from drills/python)
import os
import sys

VARIANTS = [
    ("nc01_contains_duplicate", "Solution 1", "nc01_contains_duplicate"),
    ("nc01_contains_duplicate", "Solution 2 · Sorting", "nc01_contains_duplicate__sorting"),
    ("nc02_valid_anagram", "Solution 1", "nc02_valid_anagram"),
    ("nc02_valid_anagram", "Solution 2 · Sorting", "nc02_valid_anagram__sorting"),
    ("nc03_two_sum", "Solution 1", "nc03_two_sum"),
    ("nc03_two_sum", "Solution 2 · Brute force", "nc03_two_sum__brute_force"),
    ("nc03_two_sum", "Solution 3 · Sorted two pointer", "nc03_two_sum__sorted_two_pointer"),
    ("nc04_group_anagrams", "Solution 1", "nc04_group_anagrams"),
    ("nc04_group_anagrams", "Solution 2 · Sorted key", "nc04_group_anagrams__sorted_key"),
    ("nc05_top_k_frequent", "Solution 1", "nc05_top_k_frequent"),
    ("nc05_top_k_frequent", "Solution 2 · Heapq", "nc05_top_k_frequent__heapq"),
    ("nc05_top_k_frequent", "Solution 3 · Sorting", "nc05_top_k_frequent__sorting"),
    ("nc06_product_except_self", "Solution 1", "nc06_product_except_self"),
    ("nc06_product_except_self", "Solution 2 · Brute force", "nc06_product_except_self__brute_force"),
    ("nc07_longest_consecutive", "Solution 1", "nc07_longest_consecutive"),
    ("nc07_longest_consecutive", "Solution 2 · Sorting", "nc07_longest_consecutive__sorting"),
    ("nc08_valid_palindrome", "Solution 1", "nc08_valid_palindrome"),
    ("nc08_valid_palindrome", "Solution 2 · Cleaned reverse", "nc08_valid_palindrome__cleaned_reverse"),
    ("nc09_two_sum_sorted", "Solution 1", "nc09_two_sum_sorted"),
    ("nc09_two_sum_sorted", "Solution 2 · Binary search", "nc09_two_sum_sorted__binary_search"),
    ("nc10_three_sum", "Solution 1", "nc10_three_sum"),
    ("nc10_three_sum", "Solution 2 · Brute force", "nc10_three_sum__brute_force"),
    ("nc11_container_water", "Solution 1", "nc11_container_water"),
    ("nc11_container_water", "Solution 2 · Brute force", "nc11_container_water__brute_force"),
    ("nc12_best_time_stock", "Solution 1", "nc12_best_time_stock"),
    ("nc12_best_time_stock", "Solution 2 · Brute force", "nc12_best_time_stock__brute_force"),
    ("nc13_longest_substring", "Solution 1", "nc13_longest_substring"),
    ("nc13_longest_substring", "Solution 2 · Index scan", "nc13_longest_substring__index_scan"),
    ("nc14_character_replacement", "Solution 1", "nc14_character_replacement"),
    ("nc14_character_replacement", "Solution 2 · Per character", "nc14_character_replacement__per_character"),
    ("nc15_permutation_in_string", "Solution 1", "nc15_permutation_in_string"),
    ("nc15_permutation_in_string", "Solution 2 · Sorted windows", "nc15_permutation_in_string__sorted_windows"),
    ("nc16_valid_parentheses", "Solution 1", "nc16_valid_parentheses"),
    ("nc16_valid_parentheses", "Solution 2 · Reduction", "nc16_valid_parentheses__reduction"),
    ("nc17_min_stack", "Solution 1", "nc17_min_stack"),
    ("nc17_min_stack", "Solution 2 · Pair stack", "nc17_min_stack__pair_stack"),
    ("nc18_daily_temperatures", "Solution 1", "nc18_daily_temperatures"),
    ("nc18_daily_temperatures", "Solution 2 · Brute force", "nc18_daily_temperatures__brute_force"),
    ("nc19_binary_search", "Solution 1", "nc19_binary_search"),
    ("nc19_binary_search", "Solution 2 · Recursive", "nc19_binary_search__recursive"),
    ("nc20_find_min_rotated", "Solution 1", "nc20_find_min_rotated"),
    ("nc20_find_min_rotated", "Solution 2 · Linear scan", "nc20_find_min_rotated__linear_scan"),
    ("nc21_search_rotated", "Solution 1", "nc21_search_rotated"),
    ("nc21_search_rotated", "Solution 2 · Find pivot", "nc21_search_rotated__find_pivot"),
    ("nc22_encode_decode", "Solution 1", "nc22_encode_decode"),
    ("nc22_encode_decode", "Solution 2 · Escaping", "nc22_encode_decode__escaping"),
    ("nc23_valid_sudoku", "Solution 1", "nc23_valid_sudoku"),
    ("nc23_valid_sudoku", "Solution 2 · By unit", "nc23_valid_sudoku__by_unit"),
    ("nc24_trapping_rain_water", "Solution 1", "nc24_trapping_rain_water"),
    ("nc24_trapping_rain_water", "Solution 2 · Prefix maxima", "nc24_trapping_rain_water__prefix_maxima"),
    ("nc25_min_window_substring", "Solution 1", "nc25_min_window_substring"),
    ("nc25_min_window_substring", "Solution 2 · Filtered positions", "nc25_min_window_substring__filtered_positions"),
    ("nc26_sliding_window_maximum", "Solution 1", "nc26_sliding_window_maximum"),
    ("nc26_sliding_window_maximum", "Solution 2 · Brute force", "nc26_sliding_window_maximum__brute_force"),
    ("nc26_sliding_window_maximum", "Solution 3 · Monotonic deque", "nc26_sliding_window_maximum__monotonic_deque"),
    ("nc27_eval_rpn", "Solution 1", "nc27_eval_rpn"),
    ("nc27_eval_rpn", "Solution 2 · Recursive", "nc27_eval_rpn__recursive"),
    ("nc28_generate_parentheses", "Solution 1", "nc28_generate_parentheses"),
    ("nc28_generate_parentheses", "Solution 2 · By composition", "nc28_generate_parentheses__by_composition"),
    ("nc29_car_fleet", "Solution 1", "nc29_car_fleet"),
    ("nc29_car_fleet", "Solution 2 · Pairwise", "nc29_car_fleet__pairwise"),
    ("nc30_largest_rectangle", "Solution 1", "nc30_largest_rectangle"),
    ("nc30_largest_rectangle", "Solution 2 · Expand from each bar", "nc30_largest_rectangle__expand_from_each_bar"),
    ("nc31_search_2d_matrix", "Solution 1", "nc31_search_2d_matrix"),
    ("nc31_search_2d_matrix", "Solution 2 · Staircase", "nc31_search_2d_matrix__staircase"),
    ("nc32_koko_bananas", "Solution 1", "nc32_koko_bananas"),
    ("nc32_koko_bananas", "Solution 2 · Linear scan", "nc32_koko_bananas__linear_scan"),
    ("nc33_time_map", "Solution 1", "nc33_time_map"),
    ("nc33_time_map", "Solution 2 · Linear scan", "nc33_time_map__linear_scan"),
    ("nc34_median_two_sorted", "Solution 1", "nc34_median_two_sorted"),
    ("nc34_median_two_sorted", "Solution 2 · Concat sort", "nc34_median_two_sorted__concat_sort"),
    ("nc34_median_two_sorted", "Solution 3 · Partition search", "nc34_median_two_sorted__partition_search"),
    ("nc35_insert_interval", "Solution 1", "nc35_insert_interval"),
    ("nc35_insert_interval", "Solution 2 · Merge after append", "nc35_insert_interval__merge_after_append"),
    ("nc36_merge_intervals", "Solution 1", "nc36_merge_intervals"),
    ("nc36_merge_intervals", "Solution 2 · Sweep counts", "nc36_merge_intervals__sweep_counts"),
    ("nc37_non_overlapping", "Solution 1", "nc37_non_overlapping"),
    ("nc37_non_overlapping", "Solution 2 · By start", "nc37_non_overlapping__by_start"),
    ("nc38_meeting_rooms", "Solution 1", "nc38_meeting_rooms"),
    ("nc38_meeting_rooms", "Solution 2 · Pairwise", "nc38_meeting_rooms__pairwise"),
    ("nc39_meeting_rooms_ii", "Solution 1", "nc39_meeting_rooms_ii"),
    ("nc39_meeting_rooms_ii", "Solution 2 · Count at each start", "nc39_meeting_rooms_ii__count_at_each_start"),
    ("nc40_min_interval", "Solution 1", "nc40_min_interval"),
    ("nc40_min_interval", "Solution 2 · Min heap", "nc40_min_interval__min_heap"),
    ("nc40_min_interval", "Solution 3 · Offline by length", "nc40_min_interval__offline_by_length"),
    ("nc41_maximum_subarray", "Solution 1", "nc41_maximum_subarray"),
    ("nc41_maximum_subarray", "Solution 2 · Prefix minimum", "nc41_maximum_subarray__prefix_minimum"),
    ("nc42_jump_game", "Solution 1", "nc42_jump_game"),
    ("nc42_jump_game", "Solution 2 · Backwards", "nc42_jump_game__backwards"),
    ("nc43_jump_game_ii", "Solution 1", "nc43_jump_game_ii"),
    ("nc43_jump_game_ii", "Solution 2 · Reverse greedy", "nc43_jump_game_ii__reverse_greedy"),
    ("nc44_gas_station", "Solution 1", "nc44_gas_station"),
    ("nc44_gas_station", "Solution 2 · Try each start", "nc44_gas_station__try_each_start"),
    ("nc45_hand_of_straights", "Solution 1", "nc45_hand_of_straights"),
    ("nc45_hand_of_straights", "Solution 2 · Sorted consume", "nc45_hand_of_straights__sorted_consume"),
    ("nc46_merge_triplets", "Solution 1", "nc46_merge_triplets"),
    ("nc46_merge_triplets", "Solution 2 · Track positions", "nc46_merge_triplets__track_positions"),
    ("nc47_partition_labels", "Solution 1", "nc47_partition_labels"),
    ("nc47_partition_labels", "Solution 2 · Expand end", "nc47_partition_labels__expand_end"),
    ("nc48_valid_parenthesis_string", "Solution 1", "nc48_valid_parenthesis_string"),
    ("nc48_valid_parenthesis_string", "Solution 2 · Two passes", "nc48_valid_parenthesis_string__two_passes"),
    ("nc49_single_number", "Solution 1", "nc49_single_number"),
    ("nc49_single_number", "Solution 2 · Sum of uniques", "nc49_single_number__sum_of_uniques"),
    ("nc50_number_of_one_bits", "Solution 1", "nc50_number_of_one_bits"),
    ("nc50_number_of_one_bits", "Solution 2 · Shift and test", "nc50_number_of_one_bits__shift_and_test"),
    ("nc51_counting_bits", "Solution 1", "nc51_counting_bits"),
    ("nc51_counting_bits", "Solution 2 · Popcount each", "nc51_counting_bits__popcount_each"),
    ("nc52_reverse_bits", "Solution 1", "nc52_reverse_bits"),
    ("nc52_reverse_bits", "Solution 2 · Via binary string", "nc52_reverse_bits__via_binary_string"),
    ("nc53_missing_number", "Solution 1", "nc53_missing_number"),
    ("nc53_missing_number", "Solution 2 · Gauss sum", "nc53_missing_number__gauss_sum"),
    ("nc54_sum_of_two_integers", "Solution 1", "nc54_sum_of_two_integers"),
    ("nc54_sum_of_two_integers", "Solution 2 · Full adder", "nc54_sum_of_two_integers__full_adder"),
    ("nc55_reverse_integer", "Solution 1", "nc55_reverse_integer"),
    ("nc55_reverse_integer", "Solution 2 · Via string", "nc55_reverse_integer__via_string"),
    ("nc56_rotate_image", "Solution 1", "nc56_rotate_image"),
    ("nc56_rotate_image", "Solution 2 · By index", "nc56_rotate_image__by_index"),
    ("nc57_spiral_matrix", "Solution 1", "nc57_spiral_matrix"),
    ("nc57_spiral_matrix", "Solution 2 · Boundaries", "nc57_spiral_matrix__boundaries"),
    ("nc58_set_matrix_zeroes", "Solution 1", "nc58_set_matrix_zeroes"),
    ("nc58_set_matrix_zeroes", "Solution 2 · By scanning", "nc58_set_matrix_zeroes__by_scanning"),
    ("nc59_happy_number", "Solution 1", "nc59_happy_number"),
    ("nc59_happy_number", "Solution 2 · Floyd cycle", "nc59_happy_number__floyd_cycle"),
    ("nc60_plus_one", "Solution 1", "nc60_plus_one"),
    ("nc60_plus_one", "Solution 2 · Via number", "nc60_plus_one__via_number"),
    ("nc61_pow", "Solution 1", "nc61_pow"),
    ("nc61_pow", "Solution 2 · Repeated multiplication", "nc61_pow__repeated_multiplication"),
    ("nc62_multiply_strings", "Solution 1", "nc62_multiply_strings"),
    ("nc62_multiply_strings", "Solution 2 · Partial sums", "nc62_multiply_strings__partial_sums"),
    ("nc63_detect_squares", "Solution 1", "nc63_detect_squares"),
    ("nc63_detect_squares", "Solution 2 · By side length", "nc63_detect_squares__by_side_length"),
    ("tip01_counter", "Solution 1", "tip01_counter"),
    ("tip01_counter", "Solution 2 · Plain dict", "tip01_counter__plain_dict"),
    ("tip02_defaultdict", "Solution 1", "tip02_defaultdict"),
    ("tip02_defaultdict", "Solution 2 · Setdefault", "tip02_defaultdict__setdefault"),
    ("tip03_deque", "Solution 1", "tip03_deque"),
    ("tip03_deque", "Solution 2 · List queue", "tip03_deque__list_queue"),
    ("tip04_heapq", "Solution 1", "tip04_heapq"),
    ("tip04_heapq", "Solution 2 · Sorting", "tip04_heapq__sorting"),
    ("tip05_enumerate_zip", "Solution 1", "tip05_enumerate_zip"),
    ("tip05_enumerate_zip", "Solution 2 · Index loop", "tip05_enumerate_zip__index_loop"),
    ("tip06_slicing", "Solution 1", "tip06_slicing"),
    ("tip06_slicing", "Solution 2 · Explicit loops", "tip06_slicing__explicit_loops"),
    ("tip07_sort_key", "Solution 1", "tip07_sort_key"),
    ("tip07_sort_key", "Solution 2 · Decorate sort undecorate", "tip07_sort_key__decorate_sort_undecorate"),
    ("tip08_join", "Solution 1", "tip08_join"),
    ("tip08_join", "Solution 2 · Concatenation", "tip08_join__concatenation"),
]

def main():
    root = os.path.dirname(os.path.abspath(__file__))
    failures = []
    for module, label, stem in VARIANTS:
        with open(os.path.join(root, "solutions", stem + ".py")) as handle:
            solution = handle.read()
        with open(os.path.join(root, "harnesses", module + ".py")) as handle:
            harness = handle.read()
        namespace = {}
        try:
            exec(compile(solution, stem + ".py", "exec"), namespace)
            exec(compile(harness, module + ".py", "exec"), namespace)
        except Exception as error:
            failures.append("%s [%s] raised %s: %s" % (module, label, type(error).__name__, error))
            continue
        results = namespace.get("__results__", [])
        if not results:
            failures.append("%s [%s] harness produced no cases" % (module, label))
        for case, expected, actual in results:
            if expected != actual:
                failures.append("%s [%s] %s: expected %s, got %s" % (module, label, case, expected, actual))
    for failure in failures:
        print("FAIL " + failure)
    print("%d Python variants checked, %d failures" % (len(VARIANTS), len(failures)))
    sys.exit(1 if failures else 0)

main()
