# GENERATED by `gleam run -m generate` in drills/ - do not edit.
# Runs every Python solution variant against its harness:
#   python3 verify_all.py     (from drills/python)
import os
import sys

VARIANTS = [
    ("nc01_contains_duplicate", "Solution 1", "nc01_contains_duplicate"),
    ("nc01_contains_duplicate", "Solution 2 · Sorting", "nc01_contains_duplicate__sorting"),
    ("nc02_valid_anagram", "Solution 1", "nc02_valid_anagram"),
    ("nc02_valid_anagram", "Solution 2 · Sorting", "nc02_valid_anagram__sorting"),
    ("nc03_two_sum", "Solution 1", "nc03_two_sum"),
    ("nc03_two_sum", "Solution 2 · Brute force", "nc03_two_sum__brute_force"),
    ("nc03_two_sum", "Solution 3 · Sorted two pointer", "nc03_two_sum__sorted_two_pointer"),
    ("nc04_group_anagrams", "Solution 1", "nc04_group_anagrams"),
    ("nc04_group_anagrams", "Solution 2 · Sorted key", "nc04_group_anagrams__sorted_key"),
    ("nc05_top_k_frequent", "Solution 1", "nc05_top_k_frequent"),
    ("nc05_top_k_frequent", "Solution 2 · Heapq", "nc05_top_k_frequent__heapq"),
    ("nc05_top_k_frequent", "Solution 3 · Sorting", "nc05_top_k_frequent__sorting"),
    ("nc06_product_except_self", "Solution 1", "nc06_product_except_self"),
    ("nc06_product_except_self", "Solution 2 · Brute force", "nc06_product_except_self__brute_force"),
    ("nc07_longest_consecutive", "Solution 1", "nc07_longest_consecutive"),
    ("nc07_longest_consecutive", "Solution 2 · Sorting", "nc07_longest_consecutive__sorting"),
    ("nc08_valid_palindrome", "Solution 1", "nc08_valid_palindrome"),
    ("nc08_valid_palindrome", "Solution 2 · Cleaned reverse", "nc08_valid_palindrome__cleaned_reverse"),
    ("nc09_two_sum_sorted", "Solution 1", "nc09_two_sum_sorted"),
    ("nc09_two_sum_sorted", "Solution 2 · Binary search", "nc09_two_sum_sorted__binary_search"),
    ("nc10_three_sum", "Solution 1", "nc10_three_sum"),
    ("nc10_three_sum", "Solution 2 · Brute force", "nc10_three_sum__brute_force"),
    ("nc11_container_water", "Solution 1", "nc11_container_water"),
    ("nc11_container_water", "Solution 2 · Brute force", "nc11_container_water__brute_force"),
    ("nc12_best_time_stock", "Solution 1", "nc12_best_time_stock"),
    ("nc12_best_time_stock", "Solution 2 · Brute force", "nc12_best_time_stock__brute_force"),
    ("nc13_longest_substring", "Solution 1", "nc13_longest_substring"),
    ("nc13_longest_substring", "Solution 2 · Index scan", "nc13_longest_substring__index_scan"),
    ("nc14_character_replacement", "Solution 1", "nc14_character_replacement"),
    ("nc14_character_replacement", "Solution 2 · Per character", "nc14_character_replacement__per_character"),
    ("nc15_permutation_in_string", "Solution 1", "nc15_permutation_in_string"),
    ("nc15_permutation_in_string", "Solution 2 · Sorted windows", "nc15_permutation_in_string__sorted_windows"),
    ("nc16_valid_parentheses", "Solution 1", "nc16_valid_parentheses"),
    ("nc16_valid_parentheses", "Solution 2 · Reduction", "nc16_valid_parentheses__reduction"),
    ("nc17_min_stack", "Solution 1", "nc17_min_stack"),
    ("nc17_min_stack", "Solution 2 · Pair stack", "nc17_min_stack__pair_stack"),
    ("nc18_daily_temperatures", "Solution 1", "nc18_daily_temperatures"),
    ("nc18_daily_temperatures", "Solution 2 · Brute force", "nc18_daily_temperatures__brute_force"),
    ("nc19_binary_search", "Solution 1", "nc19_binary_search"),
    ("nc19_binary_search", "Solution 2 · Recursive", "nc19_binary_search__recursive"),
    ("nc20_find_min_rotated", "Solution 1", "nc20_find_min_rotated"),
    ("nc20_find_min_rotated", "Solution 2 · Linear scan", "nc20_find_min_rotated__linear_scan"),
    ("nc21_search_rotated", "Solution 1", "nc21_search_rotated"),
    ("nc21_search_rotated", "Solution 2 · Find pivot", "nc21_search_rotated__find_pivot"),
    ("nc22_encode_decode", "Solution 1", "nc22_encode_decode"),
    ("nc22_encode_decode", "Solution 2 · Escaping", "nc22_encode_decode__escaping"),
    ("nc23_valid_sudoku", "Solution 1", "nc23_valid_sudoku"),
    ("nc23_valid_sudoku", "Solution 2 · By unit", "nc23_valid_sudoku__by_unit"),
    ("nc24_trapping_rain_water", "Solution 1", "nc24_trapping_rain_water"),
    ("nc24_trapping_rain_water", "Solution 2 · Prefix maxima", "nc24_trapping_rain_water__prefix_maxima"),
    ("tip01_counter", "Solution 1", "tip01_counter"),
    ("tip01_counter", "Solution 2 · Plain dict", "tip01_counter__plain_dict"),
    ("tip02_defaultdict", "Solution 1", "tip02_defaultdict"),
    ("tip02_defaultdict", "Solution 2 · Setdefault", "tip02_defaultdict__setdefault"),
    ("tip03_deque", "Solution 1", "tip03_deque"),
    ("tip03_deque", "Solution 2 · List queue", "tip03_deque__list_queue"),
    ("tip04_heapq", "Solution 1", "tip04_heapq"),
    ("tip04_heapq", "Solution 2 · Sorting", "tip04_heapq__sorting"),
    ("tip05_enumerate_zip", "Solution 1", "tip05_enumerate_zip"),
    ("tip05_enumerate_zip", "Solution 2 · Index loop", "tip05_enumerate_zip__index_loop"),
    ("tip06_slicing", "Solution 1", "tip06_slicing"),
    ("tip06_slicing", "Solution 2 · Explicit loops", "tip06_slicing__explicit_loops"),
    ("tip07_sort_key", "Solution 1", "tip07_sort_key"),
    ("tip07_sort_key", "Solution 2 · Decorate sort undecorate", "tip07_sort_key__decorate_sort_undecorate"),
    ("tip08_join", "Solution 1", "tip08_join"),
    ("tip08_join", "Solution 2 · Concatenation", "tip08_join__concatenation"),
]

def main():
    root = os.path.dirname(os.path.abspath(__file__))
    failures = []
    for module, label, stem in VARIANTS:
        with open(os.path.join(root, "solutions", stem + ".py")) as handle:
            solution = handle.read()
        with open(os.path.join(root, "harnesses", module + ".py")) as handle:
            harness = handle.read()
        namespace = {}
        try:
            exec(compile(solution, stem + ".py", "exec"), namespace)
            exec(compile(harness, module + ".py", "exec"), namespace)
        except Exception as error:
            failures.append("%s [%s] raised %s: %s" % (module, label, type(error).__name__, error))
            continue
        results = namespace.get("__results__", [])
        if not results:
            failures.append("%s [%s] harness produced no cases" % (module, label))
        for case, expected, actual in results:
            if expected != actual:
                failures.append("%s [%s] %s: expected %s, got %s" % (module, label, case, expected, actual))
    for failure in failures:
        print("FAIL " + failure)
    print("%d Python variants checked, %d failures" % (len(VARIANTS), len(failures)))
    sys.exit(1 if failures else 0)

main()
