# GENERATED by `gleam run -m generate` in drills/ - do not edit.
# Runs every Elixir solution variant against its harness:
#   elixir verify_all.exs     (from drills/elixir)
Code.put_compiler_option(:ignore_module_conflict, true)

variants = [
  {"nc01_contains_duplicate", "Solution 1", "nc01_contains_duplicate"},
  {"nc01_contains_duplicate", "Solution 2 · Sorting", "nc01_contains_duplicate__sorting"},
  {"nc02_valid_anagram", "Solution 1", "nc02_valid_anagram"},
  {"nc02_valid_anagram", "Solution 2 · Sorting", "nc02_valid_anagram__sorting"},
  {"nc03_two_sum", "Solution 1", "nc03_two_sum"},
  {"nc03_two_sum", "Solution 2 · Brute force", "nc03_two_sum__brute_force"},
  {"nc04_group_anagrams", "Solution 1", "nc04_group_anagrams"},
  {"nc04_group_anagrams", "Solution 2 · Count key", "nc04_group_anagrams__count_key"},
  {"nc05_top_k_frequent", "Solution 1", "nc05_top_k_frequent"},
  {"nc05_top_k_frequent", "Solution 2 · Bucket sort", "nc05_top_k_frequent__bucket_sort"},
  {"nc06_product_except_self", "Solution 1", "nc06_product_except_self"},
  {"nc06_product_except_self", "Solution 2 · Brute force", "nc06_product_except_self__brute_force"},
  {"nc07_longest_consecutive", "Solution 1", "nc07_longest_consecutive"},
  {"nc07_longest_consecutive", "Solution 2 · Sorting", "nc07_longest_consecutive__sorting"},
  {"nc08_valid_palindrome", "Solution 1", "nc08_valid_palindrome"},
  {"nc08_valid_palindrome", "Solution 2 · Two pointers", "nc08_valid_palindrome__two_pointers"},
  {"nc09_two_sum_sorted", "Solution 1", "nc09_two_sum_sorted"},
  {"nc09_two_sum_sorted", "Solution 2 · Binary search", "nc09_two_sum_sorted__binary_search"},
  {"nc10_three_sum", "Solution 1", "nc10_three_sum"},
  {"nc10_three_sum", "Solution 2 · Brute force", "nc10_three_sum__brute_force"},
  {"nc11_container_water", "Solution 1", "nc11_container_water"},
  {"nc11_container_water", "Solution 2 · Brute force", "nc11_container_water__brute_force"},
  {"nc12_best_time_stock", "Solution 1", "nc12_best_time_stock"},
  {"nc12_best_time_stock", "Solution 2 · Brute force", "nc12_best_time_stock__brute_force"},
  {"nc13_longest_substring", "Solution 1", "nc13_longest_substring"},
  {"nc13_longest_substring", "Solution 2 · Shrinking window", "nc13_longest_substring__shrinking_window"},
  {"nc14_character_replacement", "Solution 1", "nc14_character_replacement"},
  {"nc14_character_replacement", "Solution 2 · Per character", "nc14_character_replacement__per_character"},
  {"nc15_permutation_in_string", "Solution 1", "nc15_permutation_in_string"},
  {"nc15_permutation_in_string", "Solution 2 · Sorted windows", "nc15_permutation_in_string__sorted_windows"},
  {"nc16_valid_parentheses", "Solution 1", "nc16_valid_parentheses"},
  {"nc16_valid_parentheses", "Solution 2 · Reduction", "nc16_valid_parentheses__reduction"},
  {"nc17_min_stack", "Solution 1", "nc17_min_stack"},
  {"nc17_min_stack", "Solution 2 · Two stacks", "nc17_min_stack__two_stacks"},
  {"nc18_daily_temperatures", "Solution 1", "nc18_daily_temperatures"},
  {"nc18_daily_temperatures", "Solution 2 · Brute force", "nc18_daily_temperatures__brute_force"},
  {"nc19_binary_search", "Solution 1", "nc19_binary_search"},
  {"nc19_binary_search", "Solution 2 · First match scan", "nc19_binary_search__first_match_scan"},
  {"nc20_find_min_rotated", "Solution 1", "nc20_find_min_rotated"},
  {"nc20_find_min_rotated", "Solution 2 · Linear scan", "nc20_find_min_rotated__linear_scan"},
  {"nc21_search_rotated", "Solution 1", "nc21_search_rotated"},
  {"nc21_search_rotated", "Solution 2 · Find pivot", "nc21_search_rotated__find_pivot"},
  {"nc22_encode_decode", "Solution 1", "nc22_encode_decode"},
  {"nc22_encode_decode", "Solution 2 · Escaping", "nc22_encode_decode__escaping"},
  {"nc23_valid_sudoku", "Solution 1", "nc23_valid_sudoku"},
  {"nc23_valid_sudoku", "Solution 2 · By unit", "nc23_valid_sudoku__by_unit"},
  {"nc24_trapping_rain_water", "Solution 1", "nc24_trapping_rain_water"},
  {"nc24_trapping_rain_water", "Solution 2 · Prefix maxima", "nc24_trapping_rain_water__prefix_maxima"},
  {"nc25_min_window_substring", "Solution 1", "nc25_min_window_substring"},
  {"nc25_min_window_substring", "Solution 2 · Filtered positions", "nc25_min_window_substring__filtered_positions"},
  {"nc26_sliding_window_maximum", "Solution 1", "nc26_sliding_window_maximum"},
  {"nc26_sliding_window_maximum", "Solution 2 · Brute force", "nc26_sliding_window_maximum__brute_force"},
  {"nc26_sliding_window_maximum", "Solution 3 · Monotonic deque", "nc26_sliding_window_maximum__monotonic_deque"},
  {"nc27_eval_rpn", "Solution 1", "nc27_eval_rpn"},
  {"nc27_eval_rpn", "Solution 2 · Recursive", "nc27_eval_rpn__recursive"},
  {"nc28_generate_parentheses", "Solution 1", "nc28_generate_parentheses"},
  {"nc28_generate_parentheses", "Solution 2 · By composition", "nc28_generate_parentheses__by_composition"},
  {"nc29_car_fleet", "Solution 1", "nc29_car_fleet"},
  {"nc29_car_fleet", "Solution 2 · Pairwise", "nc29_car_fleet__pairwise"},
  {"nc30_largest_rectangle", "Solution 1", "nc30_largest_rectangle"},
  {"nc30_largest_rectangle", "Solution 2 · Expand from each bar", "nc30_largest_rectangle__expand_from_each_bar"},
  {"nc31_search_2d_matrix", "Solution 1", "nc31_search_2d_matrix"},
  {"nc31_search_2d_matrix", "Solution 2 · Staircase", "nc31_search_2d_matrix__staircase"},
  {"nc32_koko_bananas", "Solution 1", "nc32_koko_bananas"},
  {"nc32_koko_bananas", "Solution 2 · Linear scan", "nc32_koko_bananas__linear_scan"},
  {"nc33_time_map", "Solution 1", "nc33_time_map"},
  {"nc33_time_map", "Solution 2 · Linear scan", "nc33_time_map__linear_scan"},
  {"nc34_median_two_sorted", "Solution 1", "nc34_median_two_sorted"},
  {"nc34_median_two_sorted", "Solution 2 · Concat sort", "nc34_median_two_sorted__concat_sort"},
  {"nc34_median_two_sorted", "Solution 3 · Partition search", "nc34_median_two_sorted__partition_search"},
  {"nc35_insert_interval", "Solution 1", "nc35_insert_interval"},
  {"nc35_insert_interval", "Solution 2 · Merge after append", "nc35_insert_interval__merge_after_append"},
  {"nc36_merge_intervals", "Solution 1", "nc36_merge_intervals"},
  {"nc36_merge_intervals", "Solution 2 · Sweep counts", "nc36_merge_intervals__sweep_counts"},
  {"nc37_non_overlapping", "Solution 1", "nc37_non_overlapping"},
  {"nc37_non_overlapping", "Solution 2 · By start", "nc37_non_overlapping__by_start"},
  {"nc38_meeting_rooms", "Solution 1", "nc38_meeting_rooms"},
  {"nc38_meeting_rooms", "Solution 2 · Pairwise", "nc38_meeting_rooms__pairwise"},
  {"nc39_meeting_rooms_ii", "Solution 1", "nc39_meeting_rooms_ii"},
  {"nc39_meeting_rooms_ii", "Solution 2 · Count at each start", "nc39_meeting_rooms_ii__count_at_each_start"},
  {"nc40_min_interval", "Solution 1", "nc40_min_interval"},
  {"nc40_min_interval", "Solution 2 · Offline by length", "nc40_min_interval__offline_by_length"},
]

root = Path.dirname(__ENV__.file)

failures =
  Enum.flat_map(variants, fn {module, label, stem} ->
    solution = File.read!(Path.join([root, "solutions", stem <> ".exs"]))
    harness = File.read!(Path.join([root, "harnesses", module <> ".exs"]))

    try do
      Code.compile_string(solution, stem <> ".exs")
      {cases, _bindings} = Code.eval_string(harness, [], file: module <> ".exs")

      case cases do
        [] ->
          ["#{module} [#{label}] harness produced no cases"]

        cases ->
          for {name, expected, actual} <- cases, expected != actual do
            "#{module} [#{label}] #{name}: expected #{expected}, got #{actual}"
          end
      end
    rescue
      error -> ["#{module} [#{label}] raised #{Exception.message(error)}"]
    end
  end)

Enum.each(failures, fn failure -> IO.puts("FAIL " <> failure) end)
IO.puts("#{length(variants)} Elixir variants checked, #{length(failures)} failures")
if failures != [], do: System.halt(1)
