#!/bin/sh
# GENERATED by `gleam run -m generate` in drills/ - do not edit.
# Runs every Go solution variant against its harness:
#   ./verify_all.sh     (from drills/go)
# Each .verify/<stem> directory is a package; its report is the last
# line, a JSON object whose error is null and whose cases all passed.
cd "$(dirname "$0")" || exit 1
export GOFLAGS=-mod=mod GOTOOLCHAIN=local CGO_ENABLED=0 GOPROXY=off
count=0
failures=0
while IFS='|' read -r module label stem; do
  [ -z "$stem" ] && continue
  count=$((count + 1))
  report=$(cd ".verify/$stem" && go run . 2>&1 | tail -n 1)
  case "$report" in
    *'"error":null'*) ;;
    *) failures=$((failures + 1)); echo "FAIL $module [$label] $report"; continue ;;
  esac
  case "$report" in
    *'"cases":[]'*) failures=$((failures + 1)); echo "FAIL $module [$label] harness produced no cases" ;;
    *'"passed":false'*) failures=$((failures + 1)); echo "FAIL $module [$label] $report" ;;
  esac
done <<'VARIANTS'
nc01_contains_duplicate|Sorting|nc01_contains_duplicate__sorting
nc01_contains_duplicate|Hash Set|nc01_contains_duplicate
nc02_valid_anagram|Sorting|nc02_valid_anagram__sorting
nc02_valid_anagram|Count Map|nc02_valid_anagram
nc03_two_sum|Brute Force|nc03_two_sum__brute_force
nc03_two_sum|Hash Map|nc03_two_sum
nc04_group_anagrams|Count Key|nc04_group_anagrams
nc04_group_anagrams|Solution 2 · Count key|nc04_group_anagrams__count_key
nc05_top_k_frequent|Bucket Sort|nc05_top_k_frequent
nc05_top_k_frequent|Solution 2 · Bucket sort|nc05_top_k_frequent__bucket_sort
nc06_product_except_self|Brute Force|nc06_product_except_self__brute_force
nc06_product_except_self|Prefix & Suffix Products|nc06_product_except_self
nc07_longest_consecutive|Sorting|nc07_longest_consecutive__sorting
nc07_longest_consecutive|Hash Set|nc07_longest_consecutive
nc08_valid_palindrome|Two Pointers|nc08_valid_palindrome
nc08_valid_palindrome|Solution 2 · Two pointers|nc08_valid_palindrome__two_pointers
nc09_two_sum_sorted|Binary Search|nc09_two_sum_sorted__binary_search
nc09_two_sum_sorted|Two Pointers|nc09_two_sum_sorted
nc10_three_sum|Brute Force|nc10_three_sum__brute_force
nc10_three_sum|Sort + Two Pointers|nc10_three_sum
nc11_container_water|Brute Force|nc11_container_water__brute_force
nc11_container_water|Two Pointers|nc11_container_water
nc12_best_time_stock|Brute Force|nc12_best_time_stock__brute_force
nc12_best_time_stock|Greedy|nc12_best_time_stock
nc136_invert_binary_tree|DFS|nc136_invert_binary_tree
nc13_longest_substring|Sliding Window|nc13_longest_substring
nc13_longest_substring|Solution 2 · Shrinking window|nc13_longest_substring__shrinking_window
nc14_character_replacement|Per-Letter Window|nc14_character_replacement__per_character
nc14_character_replacement|Sliding Window|nc14_character_replacement
nc15_permutation_in_string|Brute Force|nc15_permutation_in_string__sorted_windows
nc15_permutation_in_string|Sliding Window|nc15_permutation_in_string
nc16_valid_parentheses|Nifty Python · Replace|nc16_valid_parentheses__reduction
nc16_valid_parentheses|Stack|nc16_valid_parentheses
nc17_min_stack|Two Stacks|nc17_min_stack
nc17_min_stack|Solution 2 · Two stacks|nc17_min_stack__two_stacks
nc18_daily_temperatures|Brute Force|nc18_daily_temperatures__brute_force
nc18_daily_temperatures|Monotonic Stack|nc18_daily_temperatures
nc19_binary_search|Binary Search|nc19_binary_search
nc19_binary_search|Solution 2 · First match scan|nc19_binary_search__first_match_scan
nc20_find_min_rotated|Linear Scan|nc20_find_min_rotated__linear_scan
nc20_find_min_rotated|Binary Search|nc20_find_min_rotated
nc21_search_rotated|Pivot + Binary Search|nc21_search_rotated__find_pivot
nc21_search_rotated|Binary Search|nc21_search_rotated
nc22_encode_decode|Separator + Escaping|nc22_encode_decode__escaping
nc22_encode_decode|Length Prefix|nc22_encode_decode
nc23_valid_sudoku|Check Each Unit|nc23_valid_sudoku__by_unit
nc23_valid_sudoku|One Pass + Seen Set|nc23_valid_sudoku
nc24_trapping_rain_water|Prefix Maxima|nc24_trapping_rain_water__prefix_maxima
nc24_trapping_rain_water|Two Pointers|nc24_trapping_rain_water
nc25_min_window_substring|Filtered Sliding Window|nc25_min_window_substring__filtered_positions
nc25_min_window_substring|Sliding Window|nc25_min_window_substring
nc26_sliding_window_maximum|Brute Force|nc26_sliding_window_maximum__brute_force
nc26_sliding_window_maximum|Monotonic Deque|nc26_sliding_window_maximum__monotonic_deque
nc26_sliding_window_maximum|Prefix & Suffix Maxima|nc26_sliding_window_maximum
nc27_eval_rpn|Recursion|nc27_eval_rpn__recursive
nc27_eval_rpn|Stack|nc27_eval_rpn
nc28_generate_parentheses|Divide & Conquer|nc28_generate_parentheses__by_composition
nc28_generate_parentheses|Backtracking|nc28_generate_parentheses
nc29_car_fleet|Brute Force|nc29_car_fleet__pairwise
nc29_car_fleet|Sort + Greedy|nc29_car_fleet
nc30_largest_rectangle|Brute Force|nc30_largest_rectangle__expand_from_each_bar
nc30_largest_rectangle|Monotonic Stack|nc30_largest_rectangle
nc31_search_2d_matrix|Staircase Search|nc31_search_2d_matrix__staircase
nc31_search_2d_matrix|Binary Search|nc31_search_2d_matrix
nc32_koko_bananas|Brute Force|nc32_koko_bananas__linear_scan
nc32_koko_bananas|Binary Search|nc32_koko_bananas
nc33_time_map|Linear Scan|nc33_time_map__linear_scan
nc33_time_map|Binary Search|nc33_time_map
nc34_median_two_sorted|Sorting|nc34_median_two_sorted__concat_sort
nc34_median_two_sorted|Two Pointers|nc34_median_two_sorted
nc34_median_two_sorted|Binary Search|nc34_median_two_sorted__partition_search
nc35_insert_interval|Sort + Merge|nc35_insert_interval__merge_after_append
nc35_insert_interval|Intervals|nc35_insert_interval
nc36_merge_intervals|Sweep Line|nc36_merge_intervals__sweep_counts
nc36_merge_intervals|Intervals|nc36_merge_intervals
nc37_non_overlapping|Greedy by Start|nc37_non_overlapping__by_start
nc37_non_overlapping|Greedy|nc37_non_overlapping
nc38_meeting_rooms|Brute Force|nc38_meeting_rooms__pairwise
nc38_meeting_rooms|Sorting|nc38_meeting_rooms
nc39_meeting_rooms_ii|Brute Force|nc39_meeting_rooms_ii__count_at_each_start
nc39_meeting_rooms_ii|Sweep Line|nc39_meeting_rooms_ii
nc40_min_interval|Brute Force|nc40_min_interval
nc40_min_interval|Greedy|nc40_min_interval__offline_by_length
nc41_maximum_subarray|Prefix Sums|nc41_maximum_subarray__prefix_minimum
nc41_maximum_subarray|Kadane|nc41_maximum_subarray
nc42_jump_game|Backwards Greedy|nc42_jump_game__backwards
nc42_jump_game|Greedy|nc42_jump_game
nc43_jump_game_ii|Reverse Greedy|nc43_jump_game_ii__reverse_greedy
nc43_jump_game_ii|Greedy|nc43_jump_game_ii
nc44_gas_station|Brute Force|nc44_gas_station__try_each_start
nc44_gas_station|Greedy|nc44_gas_station
nc45_hand_of_straights|Sorting|nc45_hand_of_straights__sorted_consume
nc45_hand_of_straights|Greedy|nc45_hand_of_straights
nc46_merge_triplets|Coverage Check|nc46_merge_triplets__track_positions
nc46_merge_triplets|Greedy|nc46_merge_triplets
nc47_partition_labels|Brute Force|nc47_partition_labels__expand_end
nc47_partition_labels|Greedy|nc47_partition_labels
nc48_valid_parenthesis_string|Two Passes|nc48_valid_parenthesis_string__two_passes
nc48_valid_parenthesis_string|Greedy|nc48_valid_parenthesis_string
nc49_single_number|Math|nc49_single_number__sum_of_uniques
nc49_single_number|Bit Manipulation|nc49_single_number
nc50_number_of_one_bits|Shift & Test|nc50_number_of_one_bits__shift_and_test
nc50_number_of_one_bits|Bit Manipulation|nc50_number_of_one_bits
nc51_counting_bits|Bit Manipulation|nc51_counting_bits__popcount_each
nc51_counting_bits|Bottom-Up DP|nc51_counting_bits
nc52_reverse_bits|Nifty Python · Strings|nc52_reverse_bits__via_binary_string
nc52_reverse_bits|Bit Manipulation|nc52_reverse_bits
nc53_missing_number|Math|nc53_missing_number__gauss_sum
nc53_missing_number|Bit Manipulation|nc53_missing_number
nc54_sum_of_two_integers|Full Adder|nc54_sum_of_two_integers__full_adder
nc54_sum_of_two_integers|Bit Manipulation|nc54_sum_of_two_integers
nc55_reverse_integer|Nifty Python · Strings|nc55_reverse_integer__via_string
nc55_reverse_integer|Math|nc55_reverse_integer
nc56_rotate_image|Index Mapping|nc56_rotate_image__by_index
nc56_rotate_image|Nifty Python · Zip|nc56_rotate_image
nc57_spiral_matrix|Nifty Python · Rotate|nc57_spiral_matrix
nc57_spiral_matrix|Simulation|nc57_spiral_matrix__boundaries
nc58_set_matrix_zeroes|Brute Force|nc58_set_matrix_zeroes__by_scanning
nc58_set_matrix_zeroes|Hash Set|nc58_set_matrix_zeroes
nc59_happy_number|Fast & Slow Pointers|nc59_happy_number__floyd_cycle
nc59_happy_number|Hash Set|nc59_happy_number
nc60_plus_one|Nifty Python · Big Int|nc60_plus_one__via_number
nc60_plus_one|Math|nc60_plus_one
nc61_pow|Brute Force|nc61_pow__repeated_multiplication
nc61_pow|Binary Exponentiation|nc61_pow
nc62_multiply_strings|Simulation|nc62_multiply_strings__partial_sums
nc62_multiply_strings|Math|nc62_multiply_strings
nc63_detect_squares|Side Length Scan|nc63_detect_squares__by_side_length
nc63_detect_squares|Hash Map|nc63_detect_squares
VARIANTS
echo "$count Go variants checked, $failures failures"
[ "$failures" -eq 0 ]
