#!/bin/sh
# GENERATED by `gleam run -m generate` in drills/ - do not edit.
# Runs every Go solution variant against its harness:
#   ./verify_all.sh     (from drills/go)
# Each .verify/<stem> directory is a package; its report is the last
# line, a JSON object whose error is null and whose cases all passed.
cd "$(dirname "$0")" || exit 1
export GOFLAGS=-mod=mod GOTOOLCHAIN=local CGO_ENABLED=0 GOPROXY=off
count=0
failures=0
while IFS='|' read -r module label stem; do
  [ -z "$stem" ] && continue
  count=$((count + 1))
  report=$(cd ".verify/$stem" && go run . 2>&1 | tail -n 1)
  case "$report" in
    *'"error":null'*) ;;
    *) failures=$((failures + 1)); echo "FAIL $module [$label] $report"; continue ;;
  esac
  case "$report" in
    *'"cases":[]'*) failures=$((failures + 1)); echo "FAIL $module [$label] harness produced no cases" ;;
    *'"passed":false'*) failures=$((failures + 1)); echo "FAIL $module [$label] $report" ;;
  esac
done <<'VARIANTS'
nc01_contains_duplicate|Sorting|nc01_contains_duplicate__sorting
nc01_contains_duplicate|Hash Set|nc01_contains_duplicate
nc136_invert_binary_tree|DFS|nc136_invert_binary_tree
VARIANTS
echo "$count Go variants checked, $failures failures"
[ "$failures" -eq 0 ]
