//// Emits the generated content modules:
////   ../src/algodrill/problems/embedded.gleam         (Gleam drills)
////   ../src/algodrill/problems/embedded_python.gleam  (Python drills)
////   ../src/algodrill/problems/embedded_ts.gleam      (TypeScript drills)
//// One function per drill returning the solution variants plus the Check
//// (signature, starter stub, test harness), derived from the real, runnable
//// sources under src/, harnesses/, python/solutions/ and python/harnesses/.
////
//// Also emits the two verifiers that run every Python and TypeScript variant
//// against its harness natively (python/verify_all.py, ts/verify_all.ts). They
//// are generated rather than hand-written so that the rule for what counts as a
//// variant — `variant_entries` — has exactly one definition, shared with the
//// embedded modules. Gleam's equivalent is hand-written in solutions.gleam,
//// because its checks are typed and cannot be driven off a string harness.
////
//// Run from drills/: `gleam run -m generate`

import gleam/int
import gleam/io
import gleam/list
import gleam/order
import gleam/result
import gleam/string
import simplifile

const out_path = "../src/algodrill/problems/embedded.gleam"

const python_out_path = "../src/algodrill/problems/embedded_python.gleam"

pub fn main() {
  generate_approaches()
  generate_gleam()
  generate_python()
  generate_typescript()
  generate_elixir()
}

/// Elixir drills are reveal-only: no browser can compile Elixir source, so
/// there is no Check, no starter and no harness to embed — just the solutions.
/// They are still verified natively by elixir/verify_all.exs, so the code shown
/// is code that has been run.
fn generate_elixir() {
  let assert Ok(sources) = simplifile.read_directory("elixir/solutions")
  let assert Ok(harnesses) = simplifile.read_directory("elixir/harnesses")
  let modules = module_names(harnesses, ".exs")

  let header =
    "//// GENERATED by `gleam run -m generate` in drills/ — do not edit.\n"
    <> "//// Source of truth: drills/elixir/solutions/*.exs.\n"
    <> "//// Reveal-only: Elixir drills carry solutions but no Check.\n"

  let functions =
    list.map(modules, fn(module) {
      let solutions =
        variant_sources(module, sources, "elixir/solutions/", ".exs")
        |> list.map(fn(entry) {
          "    #(\""
          <> escape(entry.0)
          <> "\", \""
          <> escape(entry.1)
          <> "\", \""
          <> escape(entry.2)
          <> "\", \""
          <> escape(entry.3)
          <> "\"),\n"
        })
        |> string.concat
      "pub fn "
      <> module
      <> "() -> List(#(String, String, String, String)) {\n  [\n"
      <> solutions
      <> "  ]\n}\n"
    })

  let assert Ok(Nil) =
    simplifile.write(
      "../src/algodrill/problems/embedded_elixir.gleam",
      string.join(
        [
          header,
          ..list.append(functions, [
            by_stem_function(modules, "List(#(String, String, String, String))"),
          ])
        ],
        "\n",
      ),
    )
  io.println(
    "embedded_elixir.gleam: "
    <> int.to_string(list.length(modules))
    <> " drills",
  )

  generate_elixir_verifier(variant_rows(modules, sources, ".exs"))
}

/// elixir/verify_all.exs — compiles each solution and evaluates its harness,
/// which is a script whose value is the list of {label, expected, actual}
/// triples. Every variant defines the same `Solution` module, so recompiling
/// over the previous one is the point rather than a mistake.
fn generate_elixir_verifier(rows: List(#(String, String, String))) -> Nil {
  let table =
    rows
    |> list.map(fn(row) {
      let #(module, label, stem) = row
      "  {\""
      <> escape(module)
      <> "\", \""
      <> escape(label)
      <> "\", \""
      <> escape(stem)
      <> "\"},\n"
    })
    |> string.concat

  let source =
    "# GENERATED by `gleam run -m generate` in drills/ - do not edit.\n"
    <> "# Runs every Elixir solution variant against its harness:\n"
    <> "#   elixir verify_all.exs     (from drills/elixir)\n"
    <> "Code.put_compiler_option(:ignore_module_conflict, true)\n\n"
    <> "variants = [\n"
    <> table
    <> "]\n\n"
    <> "root = Path.dirname(__ENV__.file)\n\n"
    <> "failures =\n"
    <> "  Enum.flat_map(variants, fn {module, label, stem} ->\n"
    <> "    solution = File.read!(Path.join([root, \"solutions\", stem <> \".exs\"]))\n"
    <> "    harness = File.read!(Path.join([root, \"harnesses\", module <> \".exs\"]))\n\n"
    <> "    try do\n"
    <> "      Code.compile_string(solution, stem <> \".exs\")\n"
    <> "      {cases, _bindings} = Code.eval_string(harness, [], file: module <> \".exs\")\n\n"
    <> "      case cases do\n"
    <> "        [] ->\n"
    <> "          [\"#{module} [#{label}] harness produced no cases\"]\n\n"
    <> "        cases ->\n"
    <> "          for {name, expected, actual} <- cases, expected != actual do\n"
    <> "            \"#{module} [#{label}] #{name}: expected #{expected}, got #{actual}\"\n"
    <> "          end\n"
    <> "      end\n"
    <> "    rescue\n"
    <> "      error -> [\"#{module} [#{label}] raised #{Exception.message(error)}\"]\n"
    <> "    end\n"
    <> "  end)\n\n"
    <> "Enum.each(failures, fn failure -> IO.puts(\"FAIL \" <> failure) end)\n"
    <> "IO.puts(\"#{length(variants)} Elixir variants checked, #{length(failures)} failures\")\n"
    <> "if failures != [], do: System.halt(1)\n"

  let assert Ok(Nil) = simplifile.write("elixir/verify_all.exs", source)
  io.println(
    "verify_all.exs: " <> int.to_string(list.length(rows)) <> " Elixir variants",
  )
}

fn generate_typescript() {
  let assert Ok(entries) = simplifile.read_directory("ts/harnesses")
  let assert Ok(sources) = simplifile.read_directory("ts/solutions")
  let modules = module_names(entries, ".ts")

  let header =
    "//// GENERATED by `gleam run -m generate` in drills/ — do not edit.\n"
    <> "//// Source of truth: drills/ts/solutions/*.ts and drills/ts/harnesses/*.ts.\n\n"
    <> "import algodrill/problem.{Check}\n"
    <> "import algodrill/problems/embedded.{type Embedded, Embedded}\n"

  let functions =
    list.map(modules, fn(module) {
      let sources = variant_sources(module, sources, "ts/solutions/", ".ts")
      let assert Ok(harness) =
        simplifile.read("ts/harnesses/" <> module <> ".ts")
      let assert Ok(primary) = simplifile.read("ts/solutions/" <> module <> ".ts")
      let #(sig, stub) = typescript_surface(primary)
      drill_function(module, sources, sig, stub, string.trim_end(harness))
    })

  let assert Ok(Nil) =
    simplifile.write(
      "../src/algodrill/problems/embedded_ts.gleam",
      string.join(
        [
          header,
          ..list.append(functions, [by_stem_function(modules, "Embedded")])
        ],
        "\n",
      ),
    )
  io.println(
    "embedded_ts.gleam: " <> int.to_string(list.length(modules)) <> " drills",
  )

  generate_ts_verifier(variant_rows(modules, sources, ".ts"))
}

/// ts/verify_all.ts plus the ts/.verify scratch tree it imports.
///
/// A harness does `import * as solution from "./solution"`, so it only runs with
/// a sibling module of that name — hence one directory per variant. The harness
/// is copied in; the solution is a one-line re-export shim, so the real file
/// under ts/solutions stays the only copy of the code.
fn generate_ts_verifier(rows: List(#(String, String, String))) -> Nil {
  // Wipe first: a renamed or deleted variant must not linger and keep passing.
  let _ = simplifile.delete("ts/.verify")

  list.each(rows, fn(row) {
    let #(module, _label, stem) = row
    let directory = "ts/.verify/" <> stem
    let assert Ok(Nil) = simplifile.create_directory_all(directory)
    let assert Ok(Nil) =
      simplifile.write(
        directory <> "/solution.ts",
        "export * from \"../../solutions/" <> stem <> "\";\n",
      )
    let assert Ok(harness) = simplifile.read("ts/harnesses/" <> module <> ".ts")
    let assert Ok(Nil) = simplifile.write(directory <> "/harness.ts", harness)
  })

  let imports =
    rows
    |> list.index_map(fn(row, index) {
      "import * as v"
      <> int.to_string(index)
      <> " from \"./.verify/"
      <> row.2
      <> "/harness\";\n"
    })
    |> string.concat

  let table =
    rows
    |> list.index_map(fn(row, index) {
      let #(module, label, _stem) = row
      "  [\""
      <> escape(module)
      <> "\", \""
      <> escape(label)
      <> "\", v"
      <> int.to_string(index)
      <> ".run],\n"
    })
    |> string.concat

  let source =
    "// GENERATED by `gleam run -m generate` in drills/ - do not edit.\n"
    <> "// Runs every TypeScript solution variant against its harness:\n"
    <> "//   bun verify_all.ts     (from drills/ts)\n"
    <> imports
    <> "\ntype Case = [string, string, string];\n\n"
    <> "const VARIANTS: [string, string, () => Case[]][] = [\n"
    <> table
    <> "];\n\n"
    <> "const failures: string[] = [];\n"
    <> "for (const [module, label, run] of VARIANTS) {\n"
    <> "  let cases: Case[];\n"
    <> "  try {\n"
    <> "    cases = run();\n"
    <> "  } catch (error) {\n"
    <> "    failures.push(`${module} [${label}] threw ${error}`);\n"
    <> "    continue;\n"
    <> "  }\n"
    <> "  if (cases.length === 0) {\n"
    <> "    failures.push(`${module} [${label}] harness produced no cases`);\n"
    <> "  }\n"
    <> "  for (const [name, expected, actual] of cases) {\n"
    <> "    if (expected !== actual) {\n"
    <> "      failures.push(`${module} [${label}] ${name}: expected ${expected}, got ${actual}`);\n"
    <> "    }\n"
    <> "  }\n"
    <> "}\n"
    <> "for (const failure of failures) console.log(\"FAIL \" + failure);\n"
    <> "console.log(`${VARIANTS.length} TypeScript variants checked, ${failures.length} failures`);\n"
    <> "if (failures.length > 0) process.exit(1);\n"

  let assert Ok(Nil) = simplifile.write("ts/verify_all.ts", source)
  io.println(
    "verify_all.ts: "
    <> int.to_string(list.length(rows))
    <> " TypeScript variants",
  )
}

/// TypeScript surface: `export function name(...): ret` headers, and
/// `export class Name` blocks with their method headers. Both are single-line
/// in every drill source. Starter bodies get a `// todo` comment.
fn typescript_surface(source: String) -> #(String, String) {
  let items = typescript_items(string.split(source, "\n"), [])
  let sig =
    items
    |> list.map(fn(item) { string.join(item, "\n") })
    |> string.join("\n\n")
  let stub =
    items
    |> list.map(fn(item) {
      case item {
        // A class: header, one stubbed method per header, closing brace. The
        // method lines already carry their two-space indentation.
        [class_header, first_method, ..rest] ->
          [
            class_header <> " {",
            ..list.map([first_method, ..rest], fn(method) {
              method <> " {\n    // todo\n  }"
            })
          ]
          |> string.join("\n")
          |> string.append("\n}")
        [header] -> header <> " {\n  // todo\n}"
        [] -> ""
      }
    })
    |> string.join("\n\n")
  #(sig, stub)
}

/// One entry per exported item: a single-element list for a function, or the
/// class header followed by its method headers.
fn typescript_items(
  lines: List(String),
  acc: List(List(String)),
) -> List(List(String)) {
  case lines {
    [] -> list.reverse(acc)
    [line, ..rest] ->
      case
        string.starts_with(line, "export function "),
        string.starts_with(line, "export class ")
      {
        True, _ -> typescript_items(rest, [[strip_brace(line)], ..acc])
        _, True -> {
          let #(methods, remaining) = typescript_methods(rest, [])
          typescript_items(remaining, [[strip_brace(line), ..methods], ..acc])
        }
        False, False -> typescript_items(rest, acc)
      }
  }
}

/// A class body's method headers: the lines indented by exactly two spaces that
/// open a block. Fields do not open one, and statements inside a method body
/// are indented further, so the two tests together are enough.
fn typescript_methods(
  lines: List(String),
  acc: List(String),
) -> #(List(String), List(String)) {
  case lines {
    [] -> #(list.reverse(acc), [])
    [line, ..rest] ->
      case line == "" || string.starts_with(line, " ") {
        False -> #(list.reverse(acc), lines)
        True ->
          case
            string.starts_with(line, "  ")
            && !string.starts_with(line, "   ")
            && string.ends_with(string.trim_end(line), "{")
          {
            // Kept indented: the signature shows the class as written.
            True -> typescript_methods(rest, [strip_brace(line), ..acc])
            False -> typescript_methods(rest, acc)
          }
      }
  }
}

fn strip_brace(line: String) -> String {
  let trimmed = string.trim_end(line)
  case string.ends_with(trimmed, "{") {
    True -> trimmed |> string.drop_end(1) |> string.trim_end
    False -> trimmed
  }
}

const approaches_out_path = "../src/algodrill/problems/approaches.gleam"

/// The approach hint ladders: drills/approaches/<slug>.txt, sections split by
/// `== nudge` / `== steps` / `== pseudocode`, emitted as a generated module
/// keyed by title slug. MANIFEST (slug<TAB>title per line) is the census: a
/// catalog title with no ladder file fails the build here, not in the app.
fn generate_approaches() {
  let assert Ok(manifest) = simplifile.read("approaches/MANIFEST")
  let entries =
    manifest
    |> string.trim
    |> string.split("\n")
    |> list.map(fn(line) {
      let assert [slug, _title] = string.split(line, "\t")
      slug
    })

  let missing =
    list.filter(entries, fn(slug) {
      simplifile.read("approaches/" <> slug <> ".txt") == Error(simplifile.Enoent)
    })
  case missing {
    [] -> Nil
    _ -> {
      io.println("MISSING approach ladders: " <> string.join(missing, ", "))
      panic as "every MANIFEST title needs drills/approaches/<slug>.txt"
    }
  }

  let arms =
    entries
    |> list.filter(fn(slug) {
      simplifile.read("approaches/" <> slug <> ".txt") != Error(simplifile.Enoent)
    })
    |> list.map(fn(slug) {
      let assert Ok(text) = simplifile.read("approaches/" <> slug <> ".txt")
      "    \"" <> slug <> "\" -> [\n" <> approach_stages(slug, text) <> "    ]\n"
    })
    |> string.concat

  let source =
    "//// GENERATED by `gleam run -m generate` in drills/ — do not edit.\n"
    <> "//// Source of truth: drills/approaches/*.txt (see MANIFEST).\n\n"
    <> "import algodrill/problem.{type ApproachStage, Nudge, Pseudocode, Steps}\n"
    <> "import gleam/list\n"
    <> "import gleam/string\n\n"
    <> "/// The hint ladder for a problem title, vaguest stage first. Titles\n"
    <> "/// are slugged so every language mirror of a problem shares one ladder.\n"
    <> "pub fn for_title(title: String) -> List(ApproachStage) {\n"
    <> "  case slug(title) {\n"
    <> arms
    <> "    _ -> []\n  }\n}\n\n"
    <> "fn slug(title: String) -> String {\n"
    <> "  title\n"
    <> "  |> string.lowercase\n"
    <> "  |> string.to_graphemes\n"
    <> "  |> list.map(fn(g) {\n"
    <> "    case string.contains(\"abcdefghijklmnopqrstuvwxyz0123456789\", g) {\n"
    <> "      True -> g\n"
    <> "      False -> \"-\"\n"
    <> "    }\n"
    <> "  })\n"
    <> "  |> string.join(\"\")\n"
    <> "  |> collapse_dashes\n"
    <> "}\n\n"
    <> "fn collapse_dashes(text: String) -> String {\n"
    <> "  let squeezed = string.replace(text, \"--\", \"-\")\n"
    <> "  case squeezed == text {\n"
    <> "    True -> trim_dashes(text)\n"
    <> "    False -> collapse_dashes(squeezed)\n"
    <> "  }\n"
    <> "}\n\n"
    <> "fn trim_dashes(text: String) -> String {\n"
    <> "  let text = case string.starts_with(text, \"-\") {\n"
    <> "    True -> string.drop_start(text, 1)\n"
    <> "    False -> text\n"
    <> "  }\n"
    <> "  case string.ends_with(text, \"-\") {\n"
    <> "    True -> string.drop_end(text, 1)\n"
    <> "    False -> text\n"
    <> "  }\n"
    <> "}\n\n"
  let assert Ok(Nil) = simplifile.write(approaches_out_path, source)
  io.println(
    "approaches.gleam: "
    <> int.to_string(list.length(entries))
    <> " hint ladders -> "
    <> approaches_out_path,
  )
}

/// Parses one ladder file into emitted Gleam constructors, asserting the
/// format: >=2 sections, nudge first, pseudocode (when present) last, steps
/// lines starting "- ".
fn approach_stages(slug: String, text: String) -> String {
  let sections =
    { "\n" <> string.trim(text) }
    |> string.split("\n== ")
    |> list.filter(fn(part) { string.trim(part) != "" })
    |> list.map(fn(part) {
      let assert [header, ..body] = string.split(part, "\n")
      #(string.trim(header), string.join(body, "\n") |> string.trim)
    })

  let assert True = list.length(sections) >= 2
  let assert Ok(#(first_kind, _)) = list.first(sections)
  let assert "nudge" = first_kind
  let assert False =
    sections
    |> list.index_map(fn(section, index) { #(index, section.0) })
    |> list.any(fn(entry) {
      entry.1 == "pseudocode" && entry.0 != list.length(sections) - 1
    })

  sections
  |> list.map(fn(section) {
    let #(kind, body) = section
    case kind {
      "nudge" -> "      Nudge(\"" <> escape(body) <> "\"),\n"
      "pseudocode" -> "      Pseudocode(\"" <> escape(body) <> "\"),\n"
      "steps" -> {
        let items =
          body
          |> string.split("\n")
          |> list.map(string.trim)
          |> list.filter(fn(line) { line != "" })
          |> list.map(fn(line) {
            let assert True = string.starts_with(line, "- ")
            "        \"" <> escape(string.drop_start(line, 2)) <> "\",\n"
          })
          |> string.concat
        let assert True = items != ""
        "      Steps([\n" <> items <> "      ]),\n"
      }
      _ -> {
        io.println("unknown section '" <> kind <> "' in " <> slug)
        panic as "approach section must be nudge, steps or pseudocode"
      }
    }
  })
  |> string.concat
}

fn generate_gleam() {
  let assert Ok(entries) = simplifile.read_directory("harnesses")
  let assert Ok(sources) = simplifile.read_directory("src")
  let modules = module_names(entries, ".gleam")

  let header =
    "//// GENERATED by `gleam run -m generate` in drills/ — do not edit.\n"
    <> "//// Source of truth: drills/src/*.gleam and drills/harnesses/*.gleam.\n\n"
    <> "import algodrill/problem.{type Check, Check}\n\n"
    <> "pub type Embedded {\n  Embedded(solutions: List(#(String, String, String, String)), check: Check)\n}\n"

  let functions =
    list.map(modules, fn(module) {
      let sources = variant_sources(module, sources, "src/", ".gleam")
      let assert Ok(harness) =
        simplifile.read("harnesses/" <> module <> ".gleam")
      // The signature and starter always come from the bare-stem primary,
      // which ordering may have moved away from the head of the list.
      let assert Ok(primary) = simplifile.read("src/" <> module <> ".gleam")
      let surface = public_surface(primary)
      let assert True = list.any(surface, is_function)
      drill_function(
        module,
        sources,
        signature(surface),
        starter(surface),
        string.trim_end(harness),
      )
    })

  let assert Ok(Nil) =
    simplifile.write(
      out_path,
      string.join(
        [
          header,
          ..list.append(functions, [by_stem_function(modules, "Embedded")])
        ],
        "\n",
      ),
    )
  io.println(
    "embedded.gleam: "
    <> int.to_string(list.length(modules))
    <> " drills -> "
    <> out_path,
  )
}

fn generate_python() {
  let assert Ok(entries) = simplifile.read_directory("python/harnesses")
  let assert Ok(sources) = simplifile.read_directory("python/solutions")
  let modules = module_names(entries, ".py")

  let header =
    "//// GENERATED by `gleam run -m generate` in drills/ — do not edit.\n"
    <> "//// Source of truth: drills/python/solutions/*.py and drills/python/harnesses/*.py.\n\n"
    <> "import algodrill/problem.{Check}\n"
    <> "import algodrill/problems/embedded.{type Embedded, Embedded}\n"

  let functions =
    list.map(modules, fn(module) {
      let sources = variant_sources(module, sources, "python/solutions/", ".py")
      let assert Ok(harness) =
        simplifile.read("python/harnesses/" <> module <> ".py")
      let assert Ok(primary) =
        simplifile.read("python/solutions/" <> module <> ".py")
      let #(sig, stub) = python_surface(primary)
      drill_function(module, sources, sig, stub, string.trim_end(harness))
    })

  let assert Ok(Nil) =
    simplifile.write(
      python_out_path,
      string.join(
        [
          header,
          ..list.append(functions, [by_stem_function(modules, "Embedded")])
        ],
        "\n",
      ),
    )
  io.println(
    "embedded_python.gleam: "
    <> int.to_string(list.length(modules))
    <> " drills -> "
    <> python_out_path,
  )

  generate_python_verifier(variant_rows(modules, sources, ".py"))
}

/// python/verify_all.py — execs each solution then its harness in one fresh
/// namespace (the harnesses reference bare names, so sharing a dict is all it
/// takes) and compares the repr pairs the harness collects.
fn generate_python_verifier(rows: List(#(String, String, String))) -> Nil {
  let table =
    rows
    |> list.map(fn(row) {
      let #(module, label, stem) = row
      "    (\""
      <> escape(module)
      <> "\", \""
      <> escape(label)
      <> "\", \""
      <> escape(stem)
      <> "\"),\n"
    })
    |> string.concat

  let source =
    "# GENERATED by `gleam run -m generate` in drills/ - do not edit.\n"
    <> "# Runs every Python solution variant against its harness:\n"
    <> "#   python3 verify_all.py     (from drills/python)\n"
    <> "import os\n"
    <> "import sys\n\n"
    <> "VARIANTS = [\n"
    <> table
    <> "]\n\n"
    <> "def main():\n"
    <> "    root = os.path.dirname(os.path.abspath(__file__))\n"
    <> "    failures = []\n"
    <> "    for module, label, stem in VARIANTS:\n"
    <> "        with open(os.path.join(root, \"solutions\", stem + \".py\")) as handle:\n"
    <> "            solution = handle.read()\n"
    <> "        with open(os.path.join(root, \"harnesses\", module + \".py\")) as handle:\n"
    <> "            harness = handle.read()\n"
    <> "        namespace = {}\n"
    <> "        try:\n"
    <> "            exec(compile(solution, stem + \".py\", \"exec\"), namespace)\n"
    <> "            exec(compile(harness, module + \".py\", \"exec\"), namespace)\n"
    <> "        except Exception as error:\n"
    <> "            failures.append(\"%s [%s] raised %s: %s\" % (module, label, type(error).__name__, error))\n"
    <> "            continue\n"
    <> "        results = namespace.get(\"__results__\", [])\n"
    <> "        if not results:\n"
    <> "            failures.append(\"%s [%s] harness produced no cases\" % (module, label))\n"
    <> "        for case, expected, actual in results:\n"
    <> "            if expected != actual:\n"
    <> "                failures.append(\"%s [%s] %s: expected %s, got %s\" % (module, label, case, expected, actual))\n"
    <> "    for failure in failures:\n"
    <> "        print(\"FAIL \" + failure)\n"
    <> "    print(\"%d Python variants checked, %d failures\" % (len(VARIANTS), len(failures)))\n"
    <> "    sys.exit(1 if failures else 0)\n\n"
    <> "main()\n"

  let assert Ok(Nil) = simplifile.write("python/verify_all.py", source)
  io.println(
    "verify_all.py: " <> int.to_string(list.length(rows)) <> " Python variants",
  )
}

/// The `case` that lets the hand-written catalogue address a drill by its file
/// stem. Generated rather than written, because Gleam has no reflection: this
/// is the only way a string becomes a call, and at 150 problems it is not a
/// thing anyone should be maintaining by hand.
fn by_stem_function(modules: List(String), returns: String) -> String {
  let arms =
    modules
    |> list.map(fn(module) {
      "    \"" <> module <> "\" -> Ok(" <> module <> "())\n"
    })
    |> string.concat

  "pub fn by_stem(stem: String) -> Result("
  <> returns
  <> ", Nil) {\n  case stem {\n"
  <> arms
  <> "    _ -> Error(Nil)\n  }\n}\n"
}

fn module_names(entries: List(String), extension: String) -> List(String) {
  entries
  |> list.filter(string.ends_with(_, extension))
  |> list.map(string.drop_end(_, string.length(extension)))
  |> list.sort(string.compare)
}

fn drill_function(
  module: String,
  sources: List(#(String, String, String, String)),
  sig: String,
  stub: String,
  harness: String,
) -> String {
  let solutions =
    sources
    |> list.map(fn(entry) {
      "      #(\""
      <> escape(entry.0)
      <> "\", \""
      <> escape(entry.1)
      <> "\", \""
      <> escape(entry.2)
      <> "\", \""
      <> escape(entry.3)
      <> "\"),\n"
    })
    |> string.concat

  "pub fn "
  <> module
  <> "() -> Embedded {\n  Embedded(\n    solutions: [\n"
  <> solutions
  <> "    ],\n    check: Check(\n      signature: \""
  <> escape(sig)
  <> "\",\n      starter: \""
  <> escape(stub)
  <> "\",\n      harness: \""
  <> escape(harness)
  <> "\",\n    ),\n  )\n}\n"
}

/// A variant unordered sorts after every ordered one; among the unordered the
/// primary stays first and alternates keep filename order, which reproduces
/// the old numbering exactly for content that has not been annotated yet.
const default_order = 999

/// What a note's directive lines declare about a variant. `kind` names the
/// technique and becomes the button label ("Brute Force", "Hash Map", "Nifty
/// Python"); `complexity` is the Big-O line shown beside it; `order` places
/// the variant worst-to-best. All optional: prose-only notes still work.
type Meta {
  Meta(kind: String, complexity: String, order: Int, note: String)
}

/// The prose for one variant, keyed by its file stem so all four language
/// mirrors of a variant share a single write-up. Directive lines (`@kind`,
/// `@big-o`, `@order`) are metadata, stripped from the prose; a `@shared/<name>`
/// line resolves to notes/shared/<name>.txt — that one hop is the entire
/// mechanism for prose that repeats across problems. Missing file: no note.
fn note_meta(stem: String) -> Meta {
  case simplifile.read("notes/" <> stem <> ".txt") {
    Error(_) -> Meta(kind: "", complexity: "", order: default_order, note: "")
    Ok(text) -> {
      let #(directives, prose) =
        string.trim(text)
        |> string.split("\n")
        |> list.partition(fn(line) {
          string.starts_with(line, "@kind ")
          || string.starts_with(line, "@big-o ")
          || string.starts_with(line, "@order ")
        })
      let value = fn(prefix: String) {
        directives
        |> list.find_map(fn(line) {
          case string.starts_with(line, prefix) {
            True ->
              Ok(string.trim(string.drop_start(line, string.length(prefix))))
            False -> Error(Nil)
          }
        })
        |> result.unwrap("")
      }
      Meta(
        kind: value("@kind "),
        complexity: value("@big-o "),
        order: value("@order ") |> int.parse |> result.unwrap(default_order),
        note: resolve_note(string.join(prose, "\n")),
      )
    }
  }
}

/// The primary plus any `<module>__<variant>` alternates, as
/// #(label, complexity, file stem), ordered worst-to-best by each note's
/// `@order` directive. This is the single definition of what counts as a
/// variant; the embedded modules and both verifiers all derive from it.
///
/// The label is the note's `@kind` when declared; otherwise the old scheme
/// ("Solution 1", "Solution N · Variant name") derived from the filename.
fn variant_entries(
  module: String,
  files: List(String),
  extension: String,
) -> List(#(String, String, String)) {
  let prefix = module <> "__"
  let alternates =
    files
    |> list.filter(string.starts_with(_, prefix))
    |> list.filter(string.ends_with(_, extension))
    |> list.sort(string.compare)
    |> list.map(string.drop_end(_, string.length(extension)))

  [module, ..alternates]
  |> list.map(fn(stem) { #(stem, note_meta(stem)) })
  |> list.sort(fn(a, b) {
    let #(stem_a, meta_a) = a
    let #(stem_b, meta_b) = b
    case int.compare(meta_a.order, meta_b.order) {
      order.Eq ->
        // Unordered: primary first, then filename — the old presentation.
        case stem_a == module, stem_b == module {
          True, False -> order.Lt
          False, True -> order.Gt
          _, _ -> string.compare(stem_a, stem_b)
        }
      decided -> decided
    }
  })
  |> list.index_map(fn(entry, index) {
    let #(stem, meta) = entry
    let label = case meta.kind, stem == module {
      "", True -> "Solution " <> int.to_string(index + 1)
      "", False ->
        "Solution "
        <> int.to_string(index + 1)
        <> " \u{b7} "
        <> {
          stem
          |> string.drop_start(string.length(prefix))
          |> string.replace("_", " ")
          |> string.capitalise
        }
      kind, _ -> kind
    }
    #(label, meta.complexity, stem)
  })
}

/// Every variant as #(label, complexity, note, source). Alternates must pass
/// the same harness as the primary (enforced by `make verify`).
fn variant_sources(
  module: String,
  files: List(String),
  directory: String,
  extension: String,
) -> List(#(String, String, String, String)) {
  variant_entries(module, files, extension)
  |> list.map(fn(entry) {
    let #(label, complexity, stem) = entry
    let assert Ok(code) = simplifile.read(directory <> stem <> extension)
    #(label, complexity, note_meta(stem).note, string.trim_end(code))
  })
}

/// Each `@shared/<name>` line expands in place to notes/shared/<name>.txt;
/// every other line is kept as written. The parts join as paragraphs, so a note
/// reads as "here is the technique" followed by "here is what this variant does
/// with it" — the technique sentence written once, the specific one per variant.
fn resolve_note(text: String) -> String {
  text
  |> string.split("\n")
  |> list.map(fn(line) {
    case string.starts_with(line, "@shared/") {
      False -> line
      True -> {
        let name = line |> string.drop_start(8) |> string.trim
        case simplifile.read("notes/shared/" <> name <> ".txt") {
          Ok(shared) -> string.trim(shared)
          Error(_) -> ""
        }
      }
    }
  })
  |> list.filter(fn(part) { part != "" })
  |> string.join("\n\n")
}

/// Flattens every module's variants into #(module, label, file stem) rows.
fn variant_rows(
  modules: List(String),
  files: List(String),
  extension: String,
) -> List(#(String, String, String)) {
  list.flat_map(modules, fn(module) {
    variant_entries(module, files, extension)
    |> list.map(fn(entry) { #(module, entry.0, entry.2) })
  })
}

/// Python surface: top-level `def name(...):` headers and `class Name:` blocks
/// with their method headers. Signature keeps the headers verbatim; the starter
/// fills each body with `pass`. Assumes single-line def headers, which holds
/// for every drill source.
fn python_surface(source: String) -> #(String, String) {
  let items = python_items(string.split(source, "\n"), [])
  let sig =
    items
    |> list.map(fn(item) { string.join(item, "\n") })
    |> string.join("\n\n")
  let stub =
    items
    |> list.map(fn(item) {
      item
      |> list.map(fn(line) {
        case string.starts_with(line, "    def ") {
          True -> line <> "\n        pass"
          False ->
            case string.starts_with(line, "def ") {
              True -> line <> "\n    pass"
              False -> line
            }
        }
      })
      |> string.join("\n")
    })
    |> string.join("\n\n")
  #(sig, stub)
}

fn python_items(
  lines: List(String),
  acc: List(List(String)),
) -> List(List(String)) {
  case lines {
    [] -> list.reverse(acc)
    [line, ..rest] ->
      case
        string.starts_with(line, "def "),
        string.starts_with(line, "class ")
      {
        True, _ -> python_items(rest, [[line], ..acc])
        _, True -> {
          let #(methods, remaining) = python_methods(rest, [])
          python_items(remaining, [[line, ..methods], ..acc])
        }
        False, False -> python_items(rest, acc)
      }
  }
}

/// Collects the `    def ...` headers of a class body; stops at the first
/// unindented line.
fn python_methods(
  lines: List(String),
  acc: List(String),
) -> #(List(String), List(String)) {
  case lines {
    [] -> #(list.reverse(acc), [])
    [line, ..rest] ->
      case
        line == ""
        || string.starts_with(line, "    ")
        || string.starts_with(line, "\t")
      {
        False -> #(list.reverse(acc), lines)
        True ->
          case string.starts_with(line, "    def ") {
            True -> python_methods(rest, [line, ..acc])
            False -> python_methods(rest, acc)
          }
      }
  }
}

/// The public surface a solver must reproduce: `pub type` blocks verbatim, and
/// `pub fn` headers with the body stripped. Headers can span lines, so the scan
/// balances parentheses (types balance braces) — safe here because none of the
/// drill sources put brace or paren characters inside string literals in headers
/// or type definitions.
type Item {
  TypeItem(text: String)
  FnItem(text: String)
}

fn is_function(item: Item) -> Bool {
  case item {
    FnItem(_) -> True
    TypeItem(_) -> False
  }
}

fn public_surface(source: String) -> List(Item) {
  collect(string.split(source, "\n"), [])
}

fn collect(lines: List(String), acc: List(Item)) -> List(Item) {
  case lines {
    [] -> list.reverse(acc)
    [line, ..rest] ->
      case
        string.starts_with(line, "pub type "),
        string.starts_with(line, "pub fn ")
      {
        True, _ -> {
          let #(block, remaining) = balanced(lines, [], 0, "{", "}")
          collect(remaining, [TypeItem(block), ..acc])
        }
        _, True -> {
          let #(block, remaining) = balanced(lines, [], 0, "(", ")")
          collect(remaining, [FnItem(strip_body_opener(block)), ..acc])
        }
        False, False -> collect(rest, acc)
      }
  }
}

/// Consumes lines until the open/close delimiters balance out. For functions the
/// balance point is the header's closing paren, whose line also carries the ` {`
/// that opens the body.
fn balanced(
  lines: List(String),
  acc: List(String),
  depth: Int,
  open: String,
  close: String,
) -> #(String, List(String)) {
  case lines {
    [] -> #(done(acc), [])
    [line, ..rest] -> {
      let depth = depth + occurrences(line, open) - occurrences(line, close)
      let acc = [line, ..acc]
      case depth <= 0 {
        True -> #(done(acc), rest)
        False -> balanced(rest, acc, depth, open, close)
      }
    }
  }
}

fn done(acc: List(String)) -> String {
  acc |> list.reverse |> string.join("\n")
}

fn occurrences(line: String, needle: String) -> Int {
  list.length(string.split(line, needle)) - 1
}

fn strip_body_opener(header: String) -> String {
  let trimmed = string.trim_end(header)
  case string.ends_with(trimmed, "{") {
    True -> trimmed |> string.drop_end(1) |> string.trim_end
    False -> trimmed
  }
}

fn signature(surface: List(Item)) -> String {
  surface
  |> list.map(fn(item) {
    case item {
      TypeItem(text) -> text
      FnItem(text) -> text
    }
  })
  |> string.join("\n\n")
}

fn starter(surface: List(Item)) -> String {
  surface
  |> list.map(fn(item) {
    case item {
      TypeItem(text) -> text
      FnItem(text) -> text <> " {\n  todo\n}"
    }
  })
  |> string.join("\n\n")
}

fn escape(source: String) -> String {
  source
  |> string.replace("\\", "\\\\")
  |> string.replace("\"", "\\\"")
}
