//// Emits the generated content modules:
////   ../src/algodrill/problems/embedded.gleam         (Gleam drills)
////   ../src/algodrill/problems/embedded_python.gleam  (Python drills)
//// One function per drill returning the solution variants plus the Check
//// (signature, starter stub, test harness), derived from the real, runnable
//// sources under src/, harnesses/, python/solutions/ and python/harnesses/.
////
//// Run from drills/: `gleam run -m generate`

import gleam/int
import gleam/io
import gleam/list
import gleam/string
import simplifile

const out_path = "../src/algodrill/problems/embedded.gleam"

const python_out_path = "../src/algodrill/problems/embedded_python.gleam"

pub fn main() {
  generate_gleam()
  generate_python()
  generate_typescript()
}

fn generate_typescript() {
  let assert Ok(entries) = simplifile.read_directory("ts/harnesses")
  let assert Ok(sources) = simplifile.read_directory("ts/solutions")
  let modules = module_names(entries, ".ts")

  let header =
    "//// GENERATED by `gleam run -m generate` in drills/ — do not edit.\n"
    <> "//// Source of truth: drills/ts/solutions/*.ts and drills/ts/harnesses/*.ts.\n\n"
    <> "import algodrill/problem.{Check}\n"
    <> "import algodrill/problems/embedded.{type Embedded, Embedded}\n"

  let functions =
    list.map(modules, fn(module) {
      let sources = variant_sources(module, sources, "ts/solutions/", ".ts")
      let assert Ok(harness) =
        simplifile.read("ts/harnesses/" <> module <> ".ts")
      let assert [#(_, primary), ..] = sources
      let #(sig, stub) = typescript_surface(primary)
      drill_function(module, sources, sig, stub, string.trim_end(harness))
    })

  let assert Ok(Nil) =
    simplifile.write(
      "../src/algodrill/problems/embedded_ts.gleam",
      string.join([header, ..functions], "\n"),
    )
  io.println(
    "embedded_ts.gleam: " <> int.to_string(list.length(modules)) <> " drills",
  )
}

/// TypeScript surface: `export function name(...): ret` headers (single-line
/// in every drill source). Starter bodies get a `// todo` comment.
fn typescript_surface(source: String) -> #(String, String) {
  let headers =
    source
    |> string.split("\n")
    |> list.filter(string.starts_with(_, "export function "))
    |> list.map(fn(line) {
      let trimmed = string.trim_end(line)
      case string.ends_with(trimmed, "{") {
        True -> trimmed |> string.drop_end(1) |> string.trim_end
        False -> trimmed
      }
    })
  let sig = string.join(headers, "\n\n")
  let stub =
    headers
    |> list.map(fn(header) { header <> " {\n  // todo\n}" })
    |> string.join("\n\n")
  #(sig, stub)
}

fn generate_gleam() {
  let assert Ok(entries) = simplifile.read_directory("harnesses")
  let assert Ok(sources) = simplifile.read_directory("src")
  let modules = module_names(entries, ".gleam")

  let header =
    "//// GENERATED by `gleam run -m generate` in drills/ — do not edit.\n"
    <> "//// Source of truth: drills/src/*.gleam and drills/harnesses/*.gleam.\n\n"
    <> "import algodrill/problem.{type Check, Check}\n\n"
    <> "pub type Embedded {\n  Embedded(solutions: List(#(String, String)), check: Check)\n}\n"

  let functions =
    list.map(modules, fn(module) {
      let sources = variant_sources(module, sources, "src/", ".gleam")
      let assert Ok(harness) =
        simplifile.read("harnesses/" <> module <> ".gleam")
      let assert [#(_, primary), ..] = sources
      let surface = public_surface(primary)
      let assert True = list.any(surface, is_function)
      drill_function(
        module,
        sources,
        signature(surface),
        starter(surface),
        string.trim_end(harness),
      )
    })

  let assert Ok(Nil) =
    simplifile.write(out_path, string.join([header, ..functions], "\n"))
  io.println(
    "embedded.gleam: "
    <> int.to_string(list.length(modules))
    <> " drills -> "
    <> out_path,
  )
}

fn generate_python() {
  let assert Ok(entries) = simplifile.read_directory("python/harnesses")
  let assert Ok(sources) = simplifile.read_directory("python/solutions")
  let modules = module_names(entries, ".py")

  let header =
    "//// GENERATED by `gleam run -m generate` in drills/ — do not edit.\n"
    <> "//// Source of truth: drills/python/solutions/*.py and drills/python/harnesses/*.py.\n\n"
    <> "import algodrill/problem.{Check}\n"
    <> "import algodrill/problems/embedded.{type Embedded, Embedded}\n"

  let functions =
    list.map(modules, fn(module) {
      let sources = variant_sources(module, sources, "python/solutions/", ".py")
      let assert Ok(harness) =
        simplifile.read("python/harnesses/" <> module <> ".py")
      let assert [#(_, primary), ..] = sources
      let #(sig, stub) = python_surface(primary)
      drill_function(module, sources, sig, stub, string.trim_end(harness))
    })

  let assert Ok(Nil) =
    simplifile.write(python_out_path, string.join([header, ..functions], "\n"))
  io.println(
    "embedded_python.gleam: "
    <> int.to_string(list.length(modules))
    <> " drills -> "
    <> python_out_path,
  )
}

fn module_names(entries: List(String), extension: String) -> List(String) {
  entries
  |> list.filter(string.ends_with(_, extension))
  |> list.map(string.drop_end(_, string.length(extension)))
  |> list.sort(string.compare)
}

fn drill_function(
  module: String,
  sources: List(#(String, String)),
  sig: String,
  stub: String,
  harness: String,
) -> String {
  let solutions =
    sources
    |> list.map(fn(entry) {
      "      #(\"" <> escape(entry.0) <> "\", \"" <> escape(entry.1) <> "\"),\n"
    })
    |> string.concat

  "pub fn "
  <> module
  <> "() -> Embedded {\n  Embedded(\n    solutions: [\n"
  <> solutions
  <> "    ],\n    check: Check(\n      signature: \""
  <> escape(sig)
  <> "\",\n      starter: \""
  <> escape(stub)
  <> "\",\n      harness: \""
  <> escape(harness)
  <> "\",\n    ),\n  )\n}\n"
}

/// The primary plus any `<module>__<variant>` alternates, labelled
/// "Solution 1", "Solution 2 · Variant name", … Every alternate must pass the
/// same harness (enforced by the round-trip suites).
fn variant_sources(
  module: String,
  files: List(String),
  directory: String,
  extension: String,
) -> List(#(String, String)) {
  let assert Ok(primary) = simplifile.read(directory <> module <> extension)
  let alternates =
    files
    |> list.filter(string.starts_with(_, module <> "__"))
    |> list.filter(string.ends_with(_, extension))
    |> list.sort(string.compare)
    |> list.index_map(fn(file, index) {
      let assert Ok(code) = simplifile.read(directory <> file)
      let variant =
        file
        |> string.drop_start(string.length(module <> "__"))
        |> string.drop_end(string.length(extension))
        |> string.replace("_", " ")
        |> string.capitalise
      #(
        "Solution " <> int.to_string(index + 2) <> " \u{b7} " <> variant,
        string.trim_end(code),
      )
    })
  [#("Solution 1", string.trim_end(primary)), ..alternates]
}

/// Python surface: top-level `def name(...):` headers and `class Name:` blocks
/// with their method headers. Signature keeps the headers verbatim; the starter
/// fills each body with `pass`. Assumes single-line def headers, which holds
/// for every drill source.
fn python_surface(source: String) -> #(String, String) {
  let items = python_items(string.split(source, "\n"), [])
  let sig =
    items
    |> list.map(fn(item) { string.join(item, "\n") })
    |> string.join("\n\n")
  let stub =
    items
    |> list.map(fn(item) {
      item
      |> list.map(fn(line) {
        case string.starts_with(line, "    def ") {
          True -> line <> "\n        pass"
          False ->
            case string.starts_with(line, "def ") {
              True -> line <> "\n    pass"
              False -> line
            }
        }
      })
      |> string.join("\n")
    })
    |> string.join("\n\n")
  #(sig, stub)
}

fn python_items(
  lines: List(String),
  acc: List(List(String)),
) -> List(List(String)) {
  case lines {
    [] -> list.reverse(acc)
    [line, ..rest] ->
      case
        string.starts_with(line, "def "),
        string.starts_with(line, "class ")
      {
        True, _ -> python_items(rest, [[line], ..acc])
        _, True -> {
          let #(methods, remaining) = python_methods(rest, [])
          python_items(remaining, [[line, ..methods], ..acc])
        }
        False, False -> python_items(rest, acc)
      }
  }
}

/// Collects the `    def ...` headers of a class body; stops at the first
/// unindented line.
fn python_methods(
  lines: List(String),
  acc: List(String),
) -> #(List(String), List(String)) {
  case lines {
    [] -> #(list.reverse(acc), [])
    [line, ..rest] ->
      case
        line == ""
        || string.starts_with(line, "    ")
        || string.starts_with(line, "\t")
      {
        False -> #(list.reverse(acc), lines)
        True ->
          case string.starts_with(line, "    def ") {
            True -> python_methods(rest, [line, ..acc])
            False -> python_methods(rest, acc)
          }
      }
  }
}

/// The public surface a solver must reproduce: `pub type` blocks verbatim, and
/// `pub fn` headers with the body stripped. Headers can span lines, so the scan
/// balances parentheses (types balance braces) — safe here because none of the
/// drill sources put brace or paren characters inside string literals in headers
/// or type definitions.
type Item {
  TypeItem(text: String)
  FnItem(text: String)
}

fn is_function(item: Item) -> Bool {
  case item {
    FnItem(_) -> True
    TypeItem(_) -> False
  }
}

fn public_surface(source: String) -> List(Item) {
  collect(string.split(source, "\n"), [])
}

fn collect(lines: List(String), acc: List(Item)) -> List(Item) {
  case lines {
    [] -> list.reverse(acc)
    [line, ..rest] ->
      case
        string.starts_with(line, "pub type "),
        string.starts_with(line, "pub fn ")
      {
        True, _ -> {
          let #(block, remaining) = balanced(lines, [], 0, "{", "}")
          collect(remaining, [TypeItem(block), ..acc])
        }
        _, True -> {
          let #(block, remaining) = balanced(lines, [], 0, "(", ")")
          collect(remaining, [FnItem(strip_body_opener(block)), ..acc])
        }
        False, False -> collect(rest, acc)
      }
  }
}

/// Consumes lines until the open/close delimiters balance out. For functions the
/// balance point is the header's closing paren, whose line also carries the ` {`
/// that opens the body.
fn balanced(
  lines: List(String),
  acc: List(String),
  depth: Int,
  open: String,
  close: String,
) -> #(String, List(String)) {
  case lines {
    [] -> #(done(acc), [])
    [line, ..rest] -> {
      let depth = depth + occurrences(line, open) - occurrences(line, close)
      let acc = [line, ..acc]
      case depth <= 0 {
        True -> #(done(acc), rest)
        False -> balanced(rest, acc, depth, open, close)
      }
    }
  }
}

fn done(acc: List(String)) -> String {
  acc |> list.reverse |> string.join("\n")
}

fn occurrences(line: String, needle: String) -> Int {
  list.length(string.split(line, needle)) - 1
}

fn strip_body_opener(header: String) -> String {
  let trimmed = string.trim_end(header)
  case string.ends_with(trimmed, "{") {
    True -> trimmed |> string.drop_end(1) |> string.trim_end
    False -> trimmed
  }
}

fn signature(surface: List(Item)) -> String {
  surface
  |> list.map(fn(item) {
    case item {
      TypeItem(text) -> text
      FnItem(text) -> text
    }
  })
  |> string.join("\n\n")
}

fn starter(surface: List(Item)) -> String {
  surface
  |> list.map(fn(item) {
    case item {
      TypeItem(text) -> text
      FnItem(text) -> text <> " {\n  todo\n}"
    }
  })
  |> string.join("\n\n")
}

fn escape(source: String) -> String {
  source
  |> string.replace("\\", "\\\\")
  |> string.replace("\"", "\\\"")
}
