//// GENERATED by `gleam run -m generate` in drills/ — do not edit.
//// Source of truth: drills/haskell/solutions/*.hs and drills/haskell/harnesses/*.hs.

import gleamdrill/problem.{Check}
import gleamdrill/problems/embedded.{type Embedded, Embedded}

pub fn nc01_contains_duplicate() -> Embedded {
  Embedded(
    solutions: [
      #(
        "Hash Set",
        "O(n) time · O(n) space",
        "A set answers the whole question. Walk once, and the moment a value is already in the set you are done — no need to finish the pass, and no need to know where the duplicate was.",
        "module Solution where

import qualified Data.Set as Set

containsDuplicate :: [Int] -> Bool
containsDuplicate nums = go Set.empty nums
  where
    go _ [] = False
    go seen (n : rest)
      | Set.member n seen = True
      | otherwise = go (Set.insert n seen) rest",
      ),
    ],
    check: Check(
      signature: "containsDuplicate :: [Int] -> Bool",
      starter: "module Solution where

import qualified Data.Set as Set

containsDuplicate :: [Int] -> Bool
containsDuplicate = error \"todo\"",
      harness: "module Main where

import Drill
import Solution

main :: IO ()
main =
  runCases
    (pure
       [ tc \"containsDuplicate [1, 2, 3, 1]\" True (containsDuplicate [1, 2, 3, 1])
       , tc \"containsDuplicate [1, 2, 3, 4]\" False (containsDuplicate [1, 2, 3, 4])
       , tc \"containsDuplicate []\" False (containsDuplicate [])
       , tc \"containsDuplicate [7, 7]\" True (containsDuplicate [7, 7])
       ])",
      graded: True,
    ),
  )
}

pub fn by_stem(stem: String) -> Result(Embedded, Nil) {
  case stem {
    "nc01_contains_duplicate" -> Ok(nc01_contains_duplicate())
    _ -> Error(Nil)
  }
}
