//// GENERATED by `gleam run -m generate` in drills/ — do not edit.
//// Source of truth: drills/tour/*/*/{code.gleam,en.html}, vendored from
//// gleam-lang/language-tour (Apache-2.0); see drills/tour/UPSTREAM.

pub type Lesson {
  Lesson(chapter: String, title: String, prose: String, code: String)
}

pub fn lessons() -> List(Lesson) {
  [
  Lesson(
    chapter: "Basics",
    title: "Hello world",
    prose: "<p>
  Here is a tiny program that prints out the text \"Hello, Joe!\". We'll explain
  how it works shortly.
</p>
<p>
  In a normal Gleam project this program would be run using the command
  <code>gleam run</code> on the command line, but here in this tour the program
  is compiled and run inside your web browser, allowing you to try Gleam without
  installing anything on your computer.
</p>
<p>
  Try changing the text being printed to <code>Hello, Mike!</code> and see what
  happens.
</p>",
    code: "import gleam/io

pub fn main() {
  io.println(\"Hello, Joe!\")
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Modules",
    prose: "<p>
  Gleam code is organized into units called <em>modules</em>. A module is a
  bunch of definitions (of types, functions, etc.) that seem to belong together.
  For example, the
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/io.html\" target=\"_blank\">
    <code>gleam/io</code>
  </a>
  module contains a variety of functions for printing, like
  <a
    href=\"https://hexdocs.pm/gleam_stdlib/gleam/io.html#println\"
    target=\"_blank\"
  >
    <code>println</code> </a
  >.
</p>
<p>
  All gleam code is in <i>some</i> module or other, whose name comes from the
  name of the file it's in. For example,
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/io.html\" target=\"_blank\">
    <code>gleam/io</code>
  </a>
  is in a file called <code>io.gleam</code> in a directory called
  <code>gleam</code>.
</p>
<p>
  For code in one module to access code in another module, we import it using
  the <code>import</code> keyword, and the name used to refer to it is the last
  part of the module name. For example, the
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/io.html\" target=\"_blank\">
    <code>gleam/io</code>
  </a>
  module is referred to as <code>io</code> once imported.
</p>
<p>
  The <code>as</code> keyword can be used to refer to a module by a different
  name. See how the
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/string.html\" target=\"_blank\">
    <code>gleam/string</code>
  </a>
  module is referred to as <code>text</code> here.
</p>
<p>
  Comments in Gleam start with <code>//</code> and continue to the end of the
  line. Comments go on the line before the item they are about, not after.
</p>",
    code: "import gleam/io
import gleam/string as text

pub fn main() {
  // Use a function from the `gleam/io` module
  io.println(\"Hello, Mike!\")

  // Use a function from the `gleam/string` module
  io.println(text.reverse(\"Hello, Joe!\"))
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Unqualified imports",
    prose: "<p>
  Normally functions from other modules are used in a
  <em>qualified</em> fashion, meaning the name used to refer the module goes
  before function name with a dot between them. For example,
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/io.html#println\" target=\"_blank\">
    <code>io.println(\"Hello!\")</code>
  </a>.
</p>
<p>
  It is also possible to specify a list of functions to import from a module in
  an <em>unqualified</em> fashion, meaning the function name can be used without
  the module <em>qualifier</em> (the name and the dot) before it.
</p>
<p>
  Generally it is best to use qualified imports, as this makes it clear where
  the function is defined, making the code easier to read.
</p>",
    code: "// Import the module and one of its functions
import gleam/io.{println}

pub fn main() {
  // Use the function in a qualified fashion
  io.println(\"This is qualified\")

  // Or an unqualified fashion
  println(\"This is unqualified\")
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Type checking",
    prose: "<p>
  Gleam has a robust static type system that helps you as you write and edit
  code, catching mistakes and showing you where to make changes.
</p>
<p>
  Uncomment the line 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/io.html#println\" target=\"_blank\">
    <code>io.println(4)</code>
  </a> 
  and see how a compile time error
  is reported as the 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/io.html#println\" target=\"_blank\">
    <code>io.println</code>
  </a> 
  function only works with strings, not ints.
</p>
<p>
  If you need to debug print something you can use the <code>echo</code>
  keyword instead, as it will print a value of any type.
</p>
<p>
  Gleam has no <code>null</code>, no implicit conversions, no exceptions, and
  always performs full type checking. If the code compiles you can be reasonably
  confident it does not have any inconsistencies that may cause bugs or crashes.
</p>",
    code: "import gleam/io

pub fn main() {
  io.println(\"My lucky number is:\")
  // io.println(4)
  // 👆️ Uncomment this line to see the error

  // echo 4
  // 👆️ You can use `echo` to debug print a value of any type!
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Ints",
    prose: "<p>Gleam's <code>Int</code> type represents whole numbers.</p>
<p>
  There are arithmetic and comparison operators for ints, as well as the
  equality operator which works on all types.
</p>
<p>
  When running on the Erlang virtual machine ints have no maximum and minimum
  size. When running on JavaScript runtimes ints are represented using
  JavaScript's 64 bit floating point numbers.
</p>
<p>
  The 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/int.html\" target=\"_blank\">
    <code>gleam/int</code>
  </a>
  standard library module contains functions for working with ints.
</p>",
    code: "import gleam/int

pub fn main() {
  // Int arithmetic
  echo 1 + 1
  echo 5 - 1
  echo 5 / 2
  echo 3 * 3
  echo 5 % 2

  // Int comparisons
  echo 3 > 1 + 1
  echo 2 < 1 - 1
  echo 8 >= 1 + 3
  echo 8 <= 5 - 3

  // Equality works for any type
  echo 2 == 1 + 1
  echo 2 == 1 - 1

  // Standard library int functions
  echo int.max(42, 77)
  echo int.clamp(5, 10, 20)
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Floats",
    prose: "<p>Gleam's <code>Float</code> type represents numbers that are not integers.</p>
<p>
  Gleam's numerical operators are not overloaded, so there are dedicated
  operators for working with floats.
</p>
<p>
  Floats are represented as 64 bit floating point numbers on both the Erlang and
  JavaScript runtimes. The floating point behaviour is native to their
  respective runtimes, so their exact behaviour will be slightly different
  on the two runtimes.
</p>
<p>
  Under the JavaScript runtime, exceeding the maximum (or minimum) representable
  value for a floating point value will result in <code>Infinity</code> (or
  <code>-Infinity</code>). Should you try to divide two infinities you will
  get <code>NaN</code> as a result.
</p>
<p>
  When running on the BEAM any overflow will raise an error. So there is
  no <code>NaN</code> or <code>Infinity</code> float value in the Erlang
  runtime.
</p>
<p>
  Division by zero will not overflow, but is instead defined to be zero.
</p>
<p>
  The 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/float.html\" target=\"_blank\">
    <code>gleam/float</code>
  </a> 
  standard library module contains functions for working with floats.
</p>",
    code: "import gleam/float

pub fn main() {
  // Float arithmetic
  echo 1.0 +. 1.5
  echo 5.0 -. 1.5
  echo 5.0 /. 2.5
  echo 3.0 *. 3.5

  // Float comparisons
  let one = 1.0
  echo 2.2 >. one
  echo 2.2 <. one
  echo 2.2 >=. one
  echo 2.2 <=. one

  // Equality works for any type
  echo 3.0 == 1.5 *. 2.0
  echo 2.1 == 1.2 +. 1.0

  // Division by zero is not an error
  echo 3.14 /. 0.0

  // Standard library float functions
  echo float.max(2.0, 9.5)
  echo float.ceiling(5.4)
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Number formats",
    prose: "<p>
  Underscores can be added to numbers for clarity. For example, 
  <code>1000000</code> can be tricky to read quickly, while 
  <code>1_000_000</code> can be easier.
</p>
<p>
  Ints can be written in binary, octal, or hexadecimal formats using the
  <code>0b</code>, <code>0o</code>, and <code>0x</code> prefixes respectively.
</p>
<p>
  Floats can be written in a scientific notation.
</p>",
    code: "pub fn main() {
  // Underscores
  echo 1_000_000
  echo 10_000.01

  // Binary, octal, and hex Int literals
  echo 0b00001111
  echo 0o17
  echo 0xF

  // Scientific notation Float literals
  echo 7.0e7
  echo 3.0e-4
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Equality",
    prose: "<p>
  Gleam has the <code>==</code> and <code>!=</code> operators for checking
  equality.
</p>
<p>
  The operators can be used with values of any type, but both sides of the
  operator must be of the same type.
</p>
<p>
  Equality is checked <em>structurally</em>, meaning that two values are equal
  if they have the same structure rather than if they are at the same memory
  location.
</p>",
    code: "pub fn main() {
  echo 100 == 50 + 50
  echo 1.5 != 0.1 *. 10.0
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Strings",
    prose: "<p>
  In Gleam strings are written as text surrounded by double quotes, and
  can span multiple lines and contain unicode characters.
</p>
<p>
  The <code>&lt;&gt;</code> operator can be used to concatenate strings.
</p>
<p>
  Several escape sequences are supported:
</p>
<ul>
  <li><code>\\\"</code> - double quote</li>
  <li><code>\\\\</code> - backslash</li>
  <li><code>\\f</code> - form feed</li>
  <li><code>\\n</code> - newline</li>
  <li><code>\\r</code> - carriage return</li>
  <li><code>\\t</code> - tab</li>
  <li><code>\\u{xxxxxx}</code> - unicode codepoint</li>
</ul>
<p>
  The 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/string.html\" target=\"_blank\">
    <code>gleam/string</code>
  </a> 
  standard library module contains functions for working with strings.
</p>",
    code: "import gleam/io
import gleam/string

pub fn main() {
  // String literals
  io.println(\"👩‍💻 こんにちは Gleam 🏳️‍🌈\")
  io.println(
    \"multi
    line
    string\",
  )
  io.println(\"\\u{1F600}\")

  // Double quote can be escaped
  io.println(\"\\\"X\\\" marks the spot\")

  // String concatenation
  io.println(\"One \" <> \"Two\")

  // String functions
  io.println(string.reverse(\"1 2 3 4 5\"))
  io.println(string.append(\"abc\", \"def\"))
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Bools",
    prose: "<p>
  A <code>Bool</code> is either <code>True</code> or <code>False</code>.
</p>
<p>
  The <code>||</code>, <code>&&</code>, and <code>!</code> operators can be used
  to manipulate bools.
</p>
<p>
  The <code>||</code> and <code>&&</code> operators are short-circuiting,
  meaning that if the left hand side of the operator is <code>True</code> for
  <code>||</code> or <code>False</code> for <code>&&</code> then the right hand
  side of the operator will not be evaluated.
</p>
<p>
  The 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/bool.html\" target=\"_blank\">
    <code>gleam/bool</code>
  </a> 
  standard library module contains functions for working with bools.
</p>",
    code: "import gleam/bool

pub fn main() {
  // Bool operators
  echo True && False
  echo True && True
  echo False || False
  echo False || True

  // Bool functions
  echo bool.to_string(True)
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Assignments",
    prose: "<p>A value can be assigned to a variable using <code>let</code>.</p>
<p>
  Variable names can be reused by later let bindings, but the values they
  reference are immutable, so the values themselves are not changed or mutated
  in any way.
</p>
<p>
  In Gleam variable and function names are written in <code>snake_case</code>.
</p>",
    code: "import gleam/io

pub fn main() {
  let x = \"Original\"
  io.println(x)

  // Assign `y` to the value of `x`
  let y = x
  io.println(y)

  // Assign `x` to a new value
  let x = \"New\"
  io.println(x)

  // The `y` still refers to the original value
  io.println(y)
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Discard patterns",
    prose: "<p>
  If a variable is assigned but not used then Gleam will emit a warning.
</p>
<p>
  If a variable is intended to not be used, then the name can be prefixed with an
  underscore, silencing the warning.
</p>
<p>
  Try changing the variable name to <code>score</code> to see the warning.
</p>",
    code: "pub fn main() {
  // This variable is never used
  let _score = 1000
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Type annotations",
    prose: "<p>
  Let assignments can be written with a type annotation after the name.
</p>
<p>
  Type annotations may be useful for documentation purposes, but they do not
  change how Gleam type checks the code beyond ensuring that the annotation is
  correct.
</p>
<p>
  Typically Gleam code will not have type annotations for assignments.
</p>
<p>
  Try changing a type annotation to something incorrect to see the compile
  error.
</p>",
    code: "pub fn main() {
  let _name: String = \"Gleam\"

  let _is_cool: Bool = True

  let _version: Int = 1
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Type imports",
    prose: "<p>
  Other modules may also define types that we wish to refer to. In this case we
  need to import them.
</p>
<p>
  Like functions, types can be referred to in a <em>qualified</em> way by
  putting the imported module name and a dot before the type name. For example,
  <code>bytes_tree.BytesTree</code>
</p>
<p>
  Types can also be imported in an <em>unqualified</em> way by listing them in
  the import statement with the word <code>type</code> before the type name.
</p>
<p>
  Unlike functions, Gleam types are commonly imported in an unqualified way.
</p>",
    code: "import gleam/bytes_tree
import gleam/string_tree.{type StringTree}

pub fn main() {
  // Referring to a type in a qualified way
  let _bytes: bytes_tree.BytesTree = bytes_tree.new()

  // Refering to a type in an unqualified way
  let _text: StringTree = string_tree.new()
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Type aliases",
    prose: "<p>
  A type alias can be used to refer to a type by a different name. Giving a type
  an alias doesn't make a new type, it is still the same type.
</p>
<p>
  A type's name always starts with a capital letter, contrasting to variables
  and functions, which start with a lowercase letter.
</p>
<p>
  When the <code>pub</code> keyword is used the type alias is public and can be
  referred to by other modules.
</p>
<p>
  Type aliases should be used <b>rarely</b>. Aliasing a type makes it
  less clear what it is, and does not provide the type safety benefits that
  using a custom type would give.
</p>",
    code: "pub type Number =
  Int

pub fn main() {
  let one: Number = 1
  let two: Int = 2

  // Number and Int are two names for the same type
  echo one == two
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Blocks",
    prose: "<p>
  Blocks are one or more expressions grouped together with curly braces. Each
  expression is evaluated in order and the value of the last expression is
  returned.
</p>
<p>
  Any variables assigned within the block can only be used within the block.
</p>
<p>
  Try uncommenting <code>echo degrees</code> to see the compile error from
  trying to use a variable that is not in scope.
</p>
<p>
  Blocks can also be used to change the order of evaluation of binary operators
  expressions. 
</p>
<p>
 <code>*</code> binds more tightly than <code>+</code> so the expression
 <code>1 + 2 * 3</code> evaluates to 7. If the <code>1 + 2</code> should be
 evaluated first to make the expression evaluate to 9 then the expression can be
 wrapped in a block: <code>{ 1 + 2 } * 3</code>. This is similar to grouping
 with parentheses in some other languages.
</p>",
    code: "pub fn main() {
  let fahrenheit = {
    let degrees = 64
    degrees
  }
  // echo degrees 
  //      ^^^^^^^ This will not compile

  // Changing order of evaluation
  let celsius = { fahrenheit - 32 } * 5 / 9
  echo celsius
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Lists",
    prose: "<p>
  Lists are ordered collections of values.
</p>
<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/list.html\" target=\"_blank\">
    <code>List</code>
  </a> 
  is a generic type, having a type parameter for the type of values it contains. 
  A list of ints has the type <code>List(Int)</code>, and a list of strings has the type
  <code>List(String)</code>.
</p>
<p>
  Lists are immutable single-linked lists, meaning they are very efficient to
  add and remove elements from the front of the list.
</p>
<p>
  Counting the length of a list or getting elements from other positions in the
  list is expensive and rarely done. It is rare to write algorithms that index
  into sequences in Gleam, but when they are written a list is not the right
  choice of data structure.
</p>",
    code: "pub fn main() {
  let ints = [1, 2, 3]

  echo ints

  // Immutably prepend
  echo [-1, 0, ..ints]

  // Uncomment this to see the error
  // echo [\"zero\", ..ints]

  // The original lists are unchanged
  echo ints
}",
  ),
  Lesson(
    chapter: "Basics",
    title: "Constants",
    prose: "<p>
  As well as let assignments Gleam also has constants, which are defined at the
  top level of a module.
</p>
<p>
  Constants must be literal values, functions cannot be used in their
  definitions.
</p>
<p>
  Constants may be useful for values that are used throughout your program,
  permitting them to be named and to ensure there are no differences in the
  definition between each use.
</p>
<p>
  Using a constant may be more efficient than creating the same value in
  multiple functions, though the exact performance characteristics will depend
  on the runtime and whether compiling to Erlang or JavaScript.
</p>",
    code: "const ints: List(Int) = [1, 2, 3]

const floats = [1.1, 2.2, 3.3]

pub fn main() {
  echo ints
  echo ints == [1, 2, 3]

  echo floats
  echo floats == [1.1, 2.2, 3.3]
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Functions",
    prose: "<p>
  The <code>fn</code> keyword is used to define new functions.
</p>
<p>
  Similar to blocks, each expression in the function body is evaluated in order
  and the value of the last expression is returned from the function. Gleam is
  an expression based language so there is no <code>return</code> operator, but
  there are ways to conditionally return early from a function, which will be
  introduced in a later section.
</p>
<p>
  The <code>double</code> and <code>multiply</code> functions are defined
  without the <code>pub</code> keyword. This makes them <em>private</em>
  functions, they can only be used within this module. If another module
  attempted to use them it would result in a compiler error.
</p>
<p>
  Like with assignments, type annotations are optional for function arguments
  and return values. It is considered good practice to use type annotations for
  functions, for clarity and to encourage intentional and thoughtful design.
</p>",
    code: "pub fn main() {
  echo double(10)
}

fn double(a: Int) -> Int {
  multiply(a, 2)
}

fn multiply(a: Int, b: Int) -> Int {
  a * b
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Higher order functions",
    prose: "<p>
  In Gleam functions are values. They can be assigned to variables, passed to
  other functions, and anything else you can do with values.
</p>
<p>
  Here the function <code>add_one</code> is being passed as an argument to the
  <code>twice</code> function.
</p>
<p>
  Notice the <code>fn</code> keyword is also used to describe the type of the
  function that <code>twice</code> takes as its second argument.
</p>",
    code: "pub fn main() {
  // Call a function with another function
  echo twice(1, add_one)

  // Functions can be assigned to variables
  let my_function = add_one
  echo my_function(100)
}

fn twice(argument: Int, passed_function: fn(Int) -> Int) -> Int {
  passed_function(passed_function(argument))
}

fn add_one(argument: Int) -> Int {
  argument + 1
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Anonymous functions",
    prose: "<p>
  As well as module-level named functions, Gleam has anonymous function
  literals, written with the <code>fn() { ... }</code> syntax.
</p>
<p>Anonymous functions can be used interchangeably with named functions.</p>
<p>
  Anonymous functions can reference variables that were in scope when they were
  defined, making them <em>closures</em>.
</p>",
    code: "pub fn main() {
  // Assign an anonymous function to a variable
  let add_one = fn(a) { a + 1 }
  echo twice(1, add_one)

  // Pass an anonymous function as an argument
  echo twice(1, fn(a) { a * 2 })

  let secret_number = 42
  // This anonymous function always returns 42
  let secret = fn() { secret_number }
  echo secret()
}

fn twice(argument: Int, my_function: fn(Int) -> Int) -> Int {
  my_function(my_function(argument))
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Function captures",
    prose: "<p>
  Gleam has a shorthand syntax for creating anonymous functions that take one
  argument and immediately call another function with that argument: the
  function capture syntax.
</p>
<p>
  The anonymous function <code>fn(a) { some_function(..., a, ...) }</code> can
  be written as <code>some_function(..., _, ...)</code>, with any number of
  other arguments passed directly to the inner function. The underscore
  <code>_</code> is a placeholder for the argument, equivalent to
  <code>a</code> in <code>fn(a) { some_function(..., a, ...) }</code>.
</p>",
    code: "pub fn main() {
  // These two statements are equivalent
  let add_one_v1 = fn(x) { add(1, x) }
  let add_one_v2 = add(1, _)

  echo add_one_v1(10)
  echo add_one_v2(10)
}

fn add(a: Int, b: Int) -> Int {
  a + b
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Generic functions",
    prose: "<p>
  Up until now each function has accepted precisely one type for each of its
  arguments.
</p>
<p>
  The <code>twice</code> function in the previous lesson on
  <i>higher order functions</i> only worked with functions that would take and
  return ints. This is overly restrictive, it should be possible to use this
  function with any type, so long as the function and the initial value are
  compatible.
</p>
<p>
  To enable this, Gleam supports <em>generics</em>, also known as
  <em>parametric polymorphism</em>.
</p>
<p>
  This works by using a type variable instead of specifying a concrete type. It
  stands in for whatever specific type is being used when the function is
  called. These type variables are written with a lowercase name.
</p>
<p>
  Type variables are not like an <code>any</code> type, they get replaced with a
  specific type each time the function is called. Try uncommenting
  <code>twice(10, exclaim)</code> to see the compiler error from trying to use a
  type variable as an int and a string at the same time.
</p>",
    code: "pub fn main() {
  let add_one = fn(x) { x + 1 }
  let exclaim = fn(x) { x <> \"!\" }

  // Invalid, Int and String are not the same type
  // twice(10, exclaim)

  // Here the type variable is replaced by the type Int
  echo twice(10, add_one)

  // Here the type variable is replaced by the type String
  echo twice(\"Hello\", exclaim)
}

// The name `value` refers to the same type multiple times
fn twice(argument: value, my_function: fn(value) -> value) -> value {
  my_function(my_function(argument))
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Pipelines",
    prose: "<p>
  It's common to want to call a series of functions, passing the result of one
  to the next. With the regular function call syntax this can be a little
  difficult to read as you have to read the code from the inside out.
</p>
<p>
  Gleam's pipe operator <code>|></code> helps with this problem by allowing you
  to write code top-to-bottom.
</p>
<p>
  The pipe operator takes the result of the expression on its left and passes it
  as an argument to the function on its right.
</p>
<p>
  If the right-hand expression is a function call then then the left-hand value
  will be used as the first argument to the call. For example,
  <code>rocket |> launch(1, 2)</code> would become
  <code>launch(rocket, 1, 2)</code>.
</p>
<p>
  If the right-hand expression is not a function call then then it will become
  one, and the left-hand value will be the sole argument to the call. For
  example, <code>rocket |> launch</code> would become
  <code>launch(rocket)</code>.
</p>
<p>
  Gleam code is typically written with the \"subject\" of the function as the
  first argument, to make it easier to pipe. If you wish to pipe to a different
  position then a function capture can be used to insert the argument to the
  desired position.
</p>
<p>
  If you need to debug print a value in the middle of a pipeline you can use
  <code>|> echo</code> to do it.
</p>",
    code: "import gleam/io
import gleam/string

pub fn main() {
  // Without the pipe operator
  io.println(string.drop_start(string.drop_end(\"Hello, Joe!\", 1), 7))

  // With the pipe operator
  \"Hello, Mike!\"
  |> string.drop_end(1)
  |> string.drop_start(7)
  |> io.println

  // Changing order with function capturing
  \"1\"
  |> string.append(\"2\")
  |> string.append(\"3\", _)
  |> io.println
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Labelled arguments",
    prose: "<p>
  When functions take several arguments it can be difficult to remember what the
  arguments are, and what order they are expected in.
</p>
<p>
  To help with this Gleam supports labelled arguments, where function arguments
  are given an external label in addition to their internal name. These labels
  are written before the argument name in the function definition.
</p>
<p>
  When labelled arguments are used the order of the arguments does not matter,
  but all unlabelled arguments must come before labelled arguments.
</p>
<p>
  There is no performance cost to using labelled arguments, it does not allocate
  a dictionary or perform any other runtime work.
</p>
<p>
  Labels are optional when calling a function, it is up to the programmer to
  decide what is clearest in their code.
</p>",
    code: "pub fn main() {
  // Without using labels
  echo calculate(1, 2, 3)

  // Using the labels
  echo calculate(1, add: 2, multiply: 3)

  // Using the labels in a different order
  echo calculate(1, multiply: 3, add: 2)
}

fn calculate(value: Int, add addend: Int, multiply multiplier: Int) {
  value * multiplier + addend
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Label shorthand syntax",
    prose: "<p>
  When local variables have the same names as a function's labelled arguments,
  the variable names can be omitted when calling the function. This is known as
  shorthand syntax for labels.
</p>
<p>The shorthand syntax can also be used for record constructor arguments.</p>",
    code: "pub fn main() {
  let quantity = 5.0
  let unit_price = 10.0
  let discount = 0.2

  // Using the regular label syntax
  echo calculate_total_cost(
    quantity: quantity,
    unit_price: unit_price,
    discount: discount,
  )

  // Using the shorthand syntax
  echo calculate_total_cost(quantity:, unit_price:, discount:)
}

fn calculate_total_cost(
  quantity quantity: Float,
  unit_price price: Float,
  discount discount: Float,
) -> Float {
  let subtotal = quantity *. price
  let discount = subtotal *. discount
  subtotal -. discount
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Documentation comments",
    prose: "<p>
  Documentation and comments are important tools for making your code easier to
  work with and understand.
</p>
<p>
  As well as regular <code>//</code> comments Gleam has <code>///</code> and
  <code>////</code> comments which are used for attaching documentation to code.
</p>
<p>
  <code>///</code> is used for documenting types and functions, and should be
  placed immediately before the type or function it is documenting.
</p>
<p>
  <code>////</code> is used for documenting modules, and should be placed
  at the top of the module.
</p>",
    code: "//// A module containing some unusual functions and types.

/// A type where the value can never be constructed.
/// Can you work out why?
pub type Never {
  Never(Never)
}

/// Call a function twice with an initial value.
///
pub fn twice(argument: value, my_function: fn(value) -> value) -> value {
  my_function(my_function(argument))
}

/// Call a function three times with an initial value.
///
pub fn thrice(argument: value, my_function: fn(value) -> value) -> value {
  my_function(my_function(my_function(argument)))
}",
  ),
  Lesson(
    chapter: "Functions",
    title: "Deprecations",
    prose: "<p>
  Functions and other definitions can be marked as deprecated using the
  <code>@deprecated</code>
  attribute.
</p>
<p>
  If a deprecated function is referenced the compiler will emit a warning,
  letting the programmer know they ought to update their code.
</p>
<p>
  The deprecation attribute takes a message and this will be displayed to the
  user in the warning. In the message explain to the user the new approach or
  replacement function, or direct them to documentation on how to upgrade.
</p>",
    code: "pub fn main() {
  echo old_function()
  echo new_function()
}

@deprecated(\"Use new_function instead\")
fn old_function() {
  Nil
}

fn new_function() {
  Nil
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "Case expressions",
    prose: "<p>
  The case expression is the most common kind of flow control in Gleam code. It
  is similar to <code>switch</code> in some other languages, but more powerful
  than most.
</p>
<p>
  It allows the programmer to say \"if the data has this shape then run this
  code\", a process called <em>pattern matching</em>.
</p>
<p>
  Gleam performs <em>exhaustiveness checking</em> to ensure that the patterns in
  a case expression cover all possible values. With this you can have confidence
  that your logic is up-to-date for the design of the data you are working with.
</p>
<p>
  Try commenting out patterns or adding new redundant ones, and see what
  problems the compiler reports.
</p>",
    code: "import gleam/int

pub fn main() {
  let x = int.random(5)
  echo x

  let result = case x {
    // Match specific values
    0 -> \"Zero\"
    1 -> \"One\"

    // Match any other value
    _ -> \"Other\"
  }
  echo result
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "Variable patterns",
    prose: "<p>
  Patterns in case expressions can also assign variables.
</p>
<p>
  When a variable name is used in a pattern the value that is matched against is
  assigned to that name, and can be used in the body of that clause.
</p>",
    code: "import gleam/int

pub fn main() {
  let result = case int.random(5) {
    // Match specific values
    0 -> \"Zero\"
    1 -> \"One\"

    // Match any other value and assign it to a variable
    other -> \"It is \" <> int.to_string(other)
  }
  echo result
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "String patterns",
    prose: "<p>
  When pattern matching on strings the <code>&lt;&gt;</code> operator can be
  used to match on strings with a specific prefix.
</p>
<p>
  The pattern <code>\"Hello, \" <> name</code> matches any string that starts with
  <code>\"Hello, \"</code> and assigns the rest of the string to the variable
  <code>name</code>.
</p>",
    code: "pub fn main() {
  echo get_name(\"Hello, Joe\")
  echo get_name(\"Hello, Mike\")
  echo get_name(\"System still working?\")
}

fn get_name(x: String) -> String {
  case x {
    \"Hello, \" <> name -> name
    _ -> \"Unknown\"
  }
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "List patterns",
    prose: "<p>
  Lists and the values they contain can be pattern matched on in case
  expressions.
</p>
<p>
  List patterns match on specific lengths of lists. The pattern <code>[]</code>
  matches an empty list, and the pattern <code>[_]</code> matches a list with
  one element. They will not match on lists with other lengths.
</p>
<p>
  The list append pattern <code>..</code> can be used to match the rest of the
  list. The pattern <code>[1, ..]</code> matches any list that starts with
  <code>1</code>. The pattern <code>[_, _, ..]</code> matches any list that has
  at least two elements.
</p>",
    code: "import gleam/int
import gleam/list

pub fn main() {
  let x = list.repeat(int.random(5), times: int.random(3))
  echo x

  let result = case x {
    [] -> \"Empty list\"
    [1] -> \"List of just 1\"
    [4, ..] -> \"List starting with 4\"
    [_, _] -> \"List of 2 elements\"
    _ -> \"Some other list\"
  }
  echo result
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "Recursion",
    prose: "<p>
  Gleam doesn't have loops, instead iteration is done through recursion, that is
  through top-level functions calling themselves with different arguments.
</p>
<p>
  A recursive function needs to have at least one <em>base case</em> and at
  least one <em>recursive case</em>. A base case returns a value without calling
  the function again. A recursive case calls the function again with different
  inputs, looping again.
</p>
<p>
  The Gleam standard library has functions for various common looping patterns,
  some of which will be introduced in later lessons, however for more complex
  loops manual recursion is often the clearest way to write it.
</p>
<p>
  Recursion can seem daunting or unclear at first if you are more familiar with
  languages that have special looping features, but stick with it! With time
  it'll become just as familiar and comfortable as any other way of iterating.
</p>",
    code: "pub fn main() {
  echo factorial(5)
  echo factorial(7)
}

// A recursive functions that calculates factorial
pub fn factorial(x: Int) -> Int {
  case x {
    // Base case
    0 -> 1
    1 -> 1

    // Recursive case
    _ -> x * factorial(step_towards_zero(x))
  }
}

fn step_towards_zero(x: Int) -> Int {
  case x >= 0 {
    True -> x - 1
    False -> x + 1
  }
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "Tail calls",
    prose: "<p>
  When a function is called a new stack frame is created in memory to store the
  arguments and local variables of the function. If lots of these frames are
  created during recursion then the program would use a large amount of memory,
  or even crash the program if some limit is hit.
</p>
<p>
  To avoid this problem Gleam supports <em>tail call optimisation</em>, which
  allows the stack frame for the current function to be reused if a function
  call is the last thing the function does, removing the memory cost.
</p>

<p>
  Unoptimised recursive functions can often be rewritten into tail call
  optimised functions by using an accumulator. An accumulator is a variable that
  is passed along in addition to the data, similar to a mutable variable in a
  language with <code>while</code> loops.
</p>
<p>
  Accumulators should be hidden away from the users of your code; they are
  internal implementation details. To do this write a public function that calls
  a recursive private function with the initial accumulator value.
</p>",
    code: "pub fn main() {
  echo factorial(5)
  echo factorial(7)
}

pub fn factorial(x: Int) -> Int {
  // The public function calls the private tail recursive function
  factorial_loop(x, 1)
}

fn factorial_loop(x: Int, accumulator: Int) -> Int {
  case x {
    0 -> accumulator
    1 -> accumulator

    // The last thing this function does is call itself
    // In the previous lesson the last thing it did was multiply two ints
    _ -> factorial_loop(x - 1, accumulator * x)
  }
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "List recursion",
    prose: "<p>
  While it is more common to use functions in the
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/list.html\" target=\"_blank\">
    <code>gleam/list</code>
  </a> 
  module to iterate across a list, at times you may prefer to work
  with the list directly.
</p>
<p>
  The <code>[first, ..rest]</code> pattern matches on a list with at least one
  element, assigning the first element to the variable <code>first</code> and
  the rest of the list to the variable <code>rest</code>. By using this pattern
  and a pattern for the empty list <code>[]</code> a function can run code on
  each element of a list until the end is reached.
</p>
<p>
  This code sums a list by recursing over the list and adding each int to a
  <code>total</code> argument, returning it when the end is reached.
</p>",
    code: "pub fn main() {
  let sum = sum_list([18, 56, 35, 85, 91], 0)
  echo sum
}

fn sum_list(list: List(Int), total: Int) -> Int {
  case list {
    [first, ..rest] -> sum_list(rest, total + first)
    [] -> total
  }
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "Multiple subjects",
    prose: "<p>
  Sometimes it is useful to pattern match on multiple values at the same time in
  one case expression.
</p>
<p>
  To do this, you can give multiple subjects and multiple patterns, separated by
  commas.
</p>
<p>
  When matching on multiple subjects there must be the same number of patterns
  as there are subjects. Try removing one of the <code>_,</code> sub-patterns to
  see the compile time error that is returned.
</p>",
    code: "import gleam/int

pub fn main() {
  let x = int.random(2)
  let y = int.random(2)
  echo x
  echo y

  let result = case x, y {
    0, 0 -> \"Both are zero\"
    0, _ -> \"First is zero\"
    _, 0 -> \"Second is zero\"
    _, _ -> \"Neither are zero\"
  }
  echo result
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "Alternative patterns",
    prose: "<p>
  Alternative patterns can be given for a case clause using the
  <code>|</code> operator. If any of the patterns match then the clause matches.
</p>
<p>
  If a pattern defines a variable then all of the alternative patterns for that
  clause must also define a variable with the same name and same type.
</p>
<p>
  Currently it is not possible to have nested alternative patterns, so the
  pattern <code>[1 | 2 | 3]</code> is not valid.
</p>",
    code: "import gleam/int

pub fn main() {
  let number = int.random(10)
  echo number

  let result = case number {
    2 | 4 | 6 | 8 -> \"This is an even number\"
    1 | 3 | 5 | 7 -> \"This is an odd number\"
    _ -> \"I'm not sure\"
  }
  echo result
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "Pattern aliases",
    prose: "<p>
  The <code>as</code> operator can be used to assign sub patterns to variables.
</p>
<p>
  The pattern <code>[_, ..] as first</code> will match any non-empty list and
  assign that list to the variable <code>first</code>.
</p>",
    code: "pub fn main() {
  echo get_first_non_empty([[], [1, 2, 3], [4, 5]])
  echo get_first_non_empty([[1, 2], [3, 4, 5], []])
  echo get_first_non_empty([[], [], []])
}

fn get_first_non_empty(lists: List(List(t))) -> List(t) {
  case lists {
    [[_, ..] as first, ..] -> first
    [_, ..rest] -> get_first_non_empty(rest)
    [] -> []
  }
}",
  ),
  Lesson(
    chapter: "Flow control",
    title: "Guards",
    prose: "<p>
  The <code>if</code> keyword can be used with case expressions to add a
  <em>guard</em> to a pattern. A guard is an expression that must evaluate to
  <code>True</code> for the pattern to match.
</p>
<p>
  Guard expressions <em>cannot</em> contain function calls, case expressions, or blocks.
</p>",
    code: "pub fn main() {
  let numbers = [1, 2, 3, 4, 5]
  echo get_first_larger(numbers, 3)
  echo get_first_larger(numbers, 5)
}

fn get_first_larger(numbers: List(Int), limit: Int) -> Int {
  case numbers {
    [first, ..] if first > limit -> first
    [_, ..rest] -> get_first_larger(rest, limit)
    [] -> 0
  }
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Tuples",
    prose: "<p>
  Lists are good for when we want a collection of one type, but sometimes we
  want to combine multiple values of different types. In this case tuples are a
  quick and convenient option.
</p>
<p>
  The tuple access syntax can be used to get elements from a tuple without
  pattern matching. <code>some_tuple.0</code> gets the first element,
  <code>some_tuple.1</code> gets the second element, etc.
</p>
<p>
  Tuples are generic types, they have type parameters for the types they
  contain. <code>#(1, \"Hi!\")</code> has the type <code>#(Int, String)</code>,
  and <code>#(1.4, 10, 48)</code> has the type <code>#(Float, Int, Int)</code>.
</p>
<p>
  Tuples are most commonly used to return 2 or 3 values from a function. Often
  it is clearer to use a <em>custom type</em> where a tuple could be used. We
  will cover custom types next.
</p>",
    code: "pub fn main() {
  let triple = #(1, 2.2, \"three\")
  echo triple

  let #(a, _, _) = triple
  echo a
  echo triple.1
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Custom types",
    prose: "<p>
  Gleam has a few built in types such as <code>Int</code> and
  <code>String</code>, but custom types allow the creation of entirely new
  types.
</p>
<p>
  A custom type is defined with the <code>type</code> keyword followed by the
  name of the type and a constructor for each <em>variant</em> of the type. Both
  the type name and the names of the constructors start with uppercase letters.
</p>
<p>Custom type variants can be pattern matched on using a case expression.</p>",
    code: "pub type Season {
  Spring
  Summer
  Autumn
  Winter
}

pub fn main() {
  echo weather(Spring)
  echo weather(Autumn)
}

fn weather(season: Season) -> String {
  case season {
    Spring -> \"Mild\"
    Summer -> \"Hot\"
    Autumn -> \"Windy\"
    Winter -> \"Cold\"
  }
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Records",
    prose: "<p>
  A variant of a custom type can hold other data within it. In this case
  the variant is called a record.
</p>
<p>
  The fields of a record can be given labels, and like function argument labels they can
  be optionally used when calling the record constructor. Typically labels will
  be used for variants that define them.
</p>
<p>
  It is common to have a custom type with one variant that holds data, this is
  the Gleam equivalent of a struct or object in other languages.
</p>
<p>
  When defining custom types with one variant, the single variant is often named the
  same as the custom type, although it doesn't have to be.
</p>",
    code: "pub type Person {
  Person(name: String, age: Int, needs_glasses: Bool)
}

pub fn main() {
  let amy = Person(\"Amy\", 26, True)
  let jared = Person(name: \"Jared\", age: 31, needs_glasses: True)
  let tom = Person(\"Tom\", 28, needs_glasses: False)

  let friends = [amy, jared, tom]
  echo friends
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Record accessors",
    prose: "<p>
  The record accessor syntax <code>record.field_label</code> can be used to get
  contained values from a custom type record.
</p>
<p>
  The accessor syntax can always be used for fields with the same name that are
  in the same position and have the same type for all variants of the custom
  type. Other fields can only be accessed when the compiler can tell which
  variant the value is, such as after pattern matching in a <code>case</code> expression.
</p>
<p>
  The <code>name</code> field is in the first position and has type
  <code>String</code> for all variants, so it can be accessed.
</p>
<p>
  The <code>subject</code> field is absent on the <code>Student</code> variant,
  so it cannot be used on all values of type <code>SchoolPerson</code>.
  Uncomment the <code>student.subject</code> line to see the compile error from
  trying to use this accessor.
</p>",
    code: "pub type SchoolPerson {
  Teacher(name: String, subject: String)
  Student(name: String)
}

pub fn main() {
  let teacher = Teacher(\"Mr Schofield\", \"Physics\")
  let student = Student(\"Koushiar\")

  echo teacher.name
  echo student.name
  // echo student.subject
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Record pattern matching",
    prose: "<p>
  It is possible to pattern match on a record, this allows for the extraction of
  multiple field values from a record into distinct variables, similar to
  matching on a tuple or a list.
</p>
<p>
  The <code>let</code> keyword can only match on single variant custom types, or
  when the variant is known, such as after pattern matching with a case
  expression.
</p>
<p>
  It is possible to use underscore <code>_</code> or the <code>..</code> syntax
  to discard fields that are not required.
</p>",
    code: "import gleam/io

pub type Fish {
  Starfish(name: String, favourite_colour: String)
  Jellyfish(name: String, jiggly: Bool)
}

pub type IceCream {
  IceCream(flavour: String)
}

pub fn main() {
  handle_fish(Starfish(\"Lucy\", \"Pink\"))
  handle_ice_cream(IceCream(\"strawberry\"))
}

fn handle_fish(fish: Fish) {
  case fish {
    Starfish(_, favourite_colour) -> io.println(favourite_colour)
    Jellyfish(name, ..) -> io.println(name)
  }
}

fn handle_ice_cream(ice_cream: IceCream) {
  // if the custom type has a single variant you can
  // destructure it using `let` instead of a case expression!
  let IceCream(flavour) = ice_cream
  io.println(flavour)
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Record updates",
    prose: "<p>
  The record update syntax can be used to create a new record from an existing
  one of the same type, but with some fields changed.
</p>
<p>
  Gleam is an immutable language, so using the record update syntax does not
  mutate or otherwise change the original record.
</p>",
    code: "pub type SchoolPerson {
  Teacher(name: String, subject: String, floor: Int, room: Int)
}

pub fn main() {
  let teacher1 = Teacher(name: \"Mr Dodd\", subject: \"ICT\", floor: 2, room: 2)

  // Use the update syntax
  let teacher2 = Teacher(..teacher1, subject: \"PE\", room: 6)

  echo teacher1
  echo teacher2
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Generic custom types",
    prose: "<p>
  Like functions, custom types can also be generic, taking contained types as
  parameters.
</p>
<p>
  Here a generic <code>Option</code> type is defined, which is used to represent
  a value that is either present or absent. This type is quite useful! The 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/option.html\" target=\"_blank\">
    <code>gleam/option</code>
  </a> 
  module defines it so you can use it in your Gleam projects.
</p>",
    code: "pub type Option(inner) {
  Some(inner)
  None
}

// An option of string
pub const name: Option(String) = Some(\"Annah\")

// An option of int
pub const level: Option(Int) = Some(10)",
  ),
  Lesson(
    chapter: "Data types",
    title: "Nil",
    prose: "<p>
  <code>Nil</code> is Gleam's unit type. It is a value that is returned by
  functions that have nothing else to return, as all functions must return
  something.
</p>
<p>
  <code>Nil</code> is not a valid value of any other types. Therefore, values in
  Gleam are not nullable. If the type of a value is <code>Nil</code> then it is
  the value <code>Nil</code>. If it is some other type then the value is not
  <code>Nil</code>.
</p>
<p>
  Uncomment the line that assigns <code>Nil</code> to a variable with an
  incompatible type annotation to see the compile time error it produces.
</p>",
    code: "import gleam/io

pub fn main() {
  let x = Nil
  echo x

  // let y: List(String) = Nil

  let result = io.println(\"Hello!\")
  echo result == Nil
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Results",
    prose: "<p>
  Gleam doesn't use exceptions, instead computations that can either succeed or
  fail return a value of the built-in <code>Result(value, error)</code> type. It
  has two variants:
</p>
<ul>
  <li>
    <code>Ok</code>, which contains the return value of a successful
    computation.
  </li>
  <li>
    <code>Error</code>, which contains the reason for a failed computation.
  </li>
</ul>
<p>
  The type is generic with two type parameters, one for the success value and
  one for the error. With these the result can hold any type for success and
  failure.
</p>
<p>
  Commonly a Gleam program or library will define a custom type with a variant
  for each possible problem that can arise, along with any error information
  that would be useful to the programmer.
</p>
<p>
  This is advantageous over exceptions as you can immediately see what if any
  errors a function can return, and the compiler will ensure they are handled.
  No nasty surprises with unexpected exceptions!
</p>
<p>
  A result value can be handled by pattern matching with a
  <code>case</code> expression, but given how frequently results are returned
  this can become unwieldy. Gleam code commonly uses the 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/result.html\" target=\"_blank\">
    <code>gleam/result</code>
  </a> 
  standard library module and <code>use</code> expressions when working with results, 
  both of which will be covered in later chapters.
</p>",
    code: "import gleam/int

pub fn main() {
  let _ = echo buy_pastry(10)
  let _ = echo buy_pastry(8)
  let _ = echo buy_pastry(5)
  let _ = echo buy_pastry(3)
}

pub type PurchaseError {
  NotEnoughMoney(required: Int)
  NotLuckyEnough
}

fn buy_pastry(money: Int) -> Result(Int, PurchaseError) {
  case money >= 5 {
    True ->
      case int.random(4) == 0 {
        True -> Error(NotLuckyEnough)
        False -> Ok(money - 5)
      }
    False -> Error(NotEnoughMoney(required: 5))
  }
}",
  ),
  Lesson(
    chapter: "Data types",
    title: "Bit arrays",
    prose: "<p>
  Bit arrays represent a sequence of 1s and 0s, and are a convenient syntax for
  constructing and manipulating binary data.
</p>
<p>
  Each segment of a bit array can be given options to specify the representation
  used for that segment.
</p>
<ul>
  <li><code>size</code>: the size of the segment in `unit`s.</li>
  <li>
    <code>unit</code>: the number of bits that the <code>size</code> value is a
    multiple of, by default 1.
  </li>
  <li><code>bits</code>: a nested bit array of any size.</li>
  <li><code>bytes</code>: a nested byte-aligned bit array.</li>
  <li><code>float</code>: a floating point number with a default size of 64 bits.</li>
  <li><code>int</code>: an int with a default size of 8 bits.</li>
  <li><code>big</code>: big endian.</li>
  <li><code>little</code>: little endian.</li>
  <li><code>native</code>: the endianness of the processor.</li>
  <li><code>utf8</code>: utf8 encoded text.</li>
  <li><code>utf16</code>: utf16 encoded text.</li>
  <li><code>utf32</code>: utf32 encoded text.</li>
  <li><code>utf8_codepoint</code>: a utf8 codepoint.</li>
  <li><code>utf16_codepoint</code>: a utf16 codepoint.</li>
  <li><code>utf32_codepoint</code>: a utf32 codepoint.</li>
  <li><code>signed</code>: a signed number.</li>
  <li><code>unsigned</code>: an unsigned number.</li>
</ul>
<p>
  Multiple options can be given to a segment by separating each with a dash:
  <code>x:unsigned-little-size(2)</code>.
</p>
<p>
  Bit arrays have limited support when compiling to JavaScript, not all options
  can be used. Full bit array support will be implemented in the future.
</p>
<p>
  For more information on bit arrays see the
  <a target=\"_blank\" rel=\"noopener\" href=\"https://www.erlang.org/doc/programming_examples/bit_syntax.html\"
    >Erlang bit syntax documentation</a
  >.
</p>",
    code: "pub fn main() {
  // 8 bit int. In binary: 00000011
  echo <<3>>
  echo <<3>> == <<3:size(8)>>

  // 16 bit int. In binary: 0001100000000011
  echo <<6147:size(16)>>

  // A bit array of UTF8 data
  echo <<\"Hello, Joe!\":utf8>>

  // Concatenation
  let first = <<4>>
  let second = <<2>>
  echo <<first:bits, second:bits>>
}",
  ),
  Lesson(
    chapter: "Standard library",
    title: "Standard library package",
    prose: "<p>
  The Gleam standard library is a regular Gleam package that has been published
  to the <a target=\"_blank\" rel=\"noopener\" href=\"https://hex.pm\">Hex</a> package repository. You could opt to
  not use it if you wish, though almost all Gleam projects depend on it.
</p>
<p>
  All of the modules imported so far in this guide, such as 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/io.html\" target=\"_blank\">
    <code>gleam/io</code>
  </a>, 
  are from the standard library.
</p>
<p>
  All of the documentation for the standard library is available on
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/\">HexDocs</a>. We will go over some
  of the most commonly used modules now.
</p>",
    code: "import gleam/io

pub fn main() {
  io.println(\"Hello, Joe!\")
  io.println(\"Hello, Mike!\")
}",
  ),
  Lesson(
    chapter: "Standard library",
    title: "List module",
    prose: "<p>
  The
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/list.html\" target=\"_blank\">
    <code>gleam/list</code>
  </a>
  standard library module contains functions for working with lists. A Gleam
  program will likely make heavy use of this module, the various functions
  serving as different types of loops over lists.
</p>

<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/list.html#map\" target=\"_blank\">
    <code>map</code>
  </a>
  makes a new list by running a function on each element in a list.
</p>
<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/list.html#filter\" target=\"_blank\">
    <code>filter</code>
  </a>
  makes a new list containing only the elements for which a function returns
  true.
</p>
<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/list.html#fold\" target=\"_blank\">
    <code>fold</code>
  </a>
  combines all the elements in a list into a single value by running a function
  left-to-right on each element, passing the result of the previous call to the
  next call.
</p>
<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/list.html#find\" target=\"_blank\">
    <code>find</code>
  </a>
  returns the first element in a list for which a function returns
  <code>True</code>.
</p>
<p>
  It's worth getting familiar with all the functions in this module when writing
  Gleam code, you'll be using them a lot!
</p>",
    code: "import gleam/io
import gleam/list

pub fn main() {
  let ints = [0, 1, 2, 3, 4, 5]

  io.println(\"=== map ===\")
  echo list.map(ints, fn(x) { x * 2 })

  io.println(\"=== filter ===\")
  echo list.filter(ints, fn(x) { x % 2 == 0 })

  io.println(\"=== fold ===\")
  echo list.fold(ints, 0, fn(count, e) { count + e })

  io.println(\"=== find ===\")
  let _ = echo list.find(ints, fn(x) { x > 3 })
  echo list.find(ints, fn(x) { x > 13 })
}",
  ),
  Lesson(
    chapter: "Standard library",
    title: "Result module",
    prose: "<p>
  The
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/result.html\" target=\"_blank\">
    <code>gleam/result</code>
  </a>
  standard library module contains functions for working with results. Gleam
  programs will make heavy use of this module to avoid excessive nested case
  expressions when calling multiple functions that can fail.
</p>

<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/result.html#map\" target=\"_blank\">
    <code>map</code>
  </a>
  updates a value held within the Ok of a result by calling a given function on
  it. If the result is an error then the function is not called.
</p>

<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/result.html#try\" target=\"_blank\">
    <code>try</code>
  </a>
  runs a result-returning function on the value held within an Ok of a result.
  If the result is an error then the function is not called. This is useful for
  chaining together multiple function calls that can fail, one after the other,
  stopping at the first error.
</p>

<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/result.html#unwrap\" target=\"_blank\">
    <code>unwrap</code>
  </a>
  extracts the success value from a result, or returning a default value if the
  result is an error.
</p>

<p>
  Result functions are often used with pipelines to chain together multiple
  calls to result-returning functions.
</p>",
    code: "import gleam/int
import gleam/io
import gleam/result

pub fn main() {
  io.println(\"=== map ===\")
  let _ = echo result.map(Ok(1), fn(x) { x * 2 })
  let _ = echo result.map(Error(1), fn(x) { x * 2 })

  io.println(\"=== try ===\")
  let _ = echo result.try(Ok(\"1\"), int.parse)
  let _ = echo result.try(Ok(\"no\"), int.parse)
  let _ = echo result.try(Error(Nil), int.parse)

  io.println(\"=== unwrap ===\")
  echo result.unwrap(Ok(\"1234\"), \"default\")
  echo result.unwrap(Error(Nil), \"default\")

  io.println(\"=== pipeline ===\")
  int.parse(\"-1234\")
  |> result.map(int.absolute_value)
  |> result.try(int.remainder(_, 42))
  |> echo
}",
  ),
  Lesson(
    chapter: "Standard library",
    title: "Dict module",
    prose: "<p>
  The
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/dict.html\"
    ><code>gleam/dict</code></a
  >
  standard library module defines Gleam's <code>Dict</code> type and functions
  for working with it. A dict is a collection of keys and values which other
  languages may call a hashmap or table.
</p>

<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/dict.html#new\" target=\"_blank\">
    <code>new</code>
  </a>
  and
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/dict.html#from_list\" target=\"_blank\">
    <code>from_list</code>
  </a>
  can be used to create new dicts.
</p>

<p>
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/dict.html#insert\" target=\"_blank\">
    <code>insert</code>
  </a>
  and
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/dict.html#delete\" target=\"_blank\">
    <code>delete</code>
  </a>
  are used to add and remove items from a dict.
</p>
<p>
  Like lists, dicts are immutable. Inserting or deleting an item from a dict
  will return a new dict with the item added or removed.
</p>
<p>
  Dicts are unordered! If it appears that the items in a dict are in a certain
  order, it is incidental and should not be relied upon. Any ordering may
  change without warning in future versions or on different runtimes.
</p>",
    code: "import gleam/dict

pub fn main() {
  let scores = dict.from_list([#(\"Lucy\", 13), #(\"Drew\", 15)])
  echo dict.to_list(scores)

  let scores =
    scores
    |> dict.insert(\"Bushra\", 16)
    |> dict.insert(\"Darius\", 14)
    |> dict.delete(\"Drew\")
  echo dict.to_list(scores)
}",
  ),
  Lesson(
    chapter: "Standard library",
    title: "Option module",
    prose: "<p>
  Values in Gleam are not nullable, so the
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/option.html\" target=\"_blank\">
    <code>gleam/option</code>
  </a>
  standard library module defines Gleam's 
  <a target=\"_blank\" rel=\"noopener\" href=\"https://hexdocs.pm/gleam_stdlib/gleam/option.html#Option\" target=\"_blank\">
    <code>Option</code>
  </a> 
  type, which can be used to represent a value that is either present or absent.
</p>

<p>
  The option type is very similar to the result type, but it does not have an
  error value. Some languages have functions that return an option when there is
  no extra error detail to give, but Gleam always uses result. This makes all
  fallible functions consistent and removes any boilerplate that would be
  required when mixing functions that use each type.
</p>",
    code: "import gleam/option.{type Option, None, Some}

pub type Person {
  Person(name: String, pet: Option(String))
}

pub fn main() {
  let person_with_pet = Person(\"Al\", Some(\"Nubi\"))
  let person_without_pet = Person(\"Maria\", None)

  echo person_with_pet
  echo person_without_pet
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "Opaque types",
    prose: "<p>
  <em>Opaque types</em> are types where a custom type itself is public and can
  be used by other modules, but the constructors for the type are private and
  can only be used by the module that defines the type. This prevents other
  modules from constructing or pattern matching on the type.
</p>
<p>
  This is useful for creating types with <em>smart constructors</em>. A smart
  constructor is a function that constructs a value of a type, but is more
  restrictive than if the programmer were to use one of the type's constructors
  directly. This can be useful for ensuring that the type is used correctly.
</p>
<p>
  For example, this <code>PositiveInt</code> custom type is opaque. If other
  modules want to construct one they have to use the <code>new</code> function,
  which ensures that the integer is positive.
</p>",
    code: "pub fn main() {
  let positive = new(1)
  let zero = new(0)
  let negative = new(-1)

  echo to_int(positive)
  echo to_int(zero)
  echo to_int(negative)
}

pub opaque type PositiveInt {
  PositiveInt(inner: Int)
}

pub fn new(i: Int) -> PositiveInt {
  case i >= 0 {
    True -> PositiveInt(i)
    False -> PositiveInt(0)
  }
}

pub fn to_int(i: PositiveInt) -> Int {
  i.inner
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "Use",
    prose: "<p>
  Gleam lacks exceptions, macros, type classes, early returns, and a variety of
  other features, instead going all-in with just first-class-functions and
  pattern matching. This makes Gleam code easier to understand, but it can
  sometimes result in excessive indentation.
</p>
<p>
  Gleam's <code>use</code> expression is for calling functions that take a
  callback as an argument without increasing the indentation of the code.
</p>

<p>
  All the code below the <code>use</code> becomes an anonymous function, and
  the assigned variables become the arguments to the anonymous function.
</p>
<p>
  If the right hand side of <code>&lt;-</code> is a function call then the new
  anonymous function is inserted as a final argument to the call, otherwise the
  expression on the right hand side must return a function that takes the
  anonymous function as an argument.
</p>

<p>This code:</p>
<pre>
pub fn main() -> Nil {
  use a, b <- my_function
  next(a)
  next(b)
}
</pre>

<p>Expands into this code:</p>
<pre>
pub fn main() -> Nil {
  my_function(fn(a, b) {
    next(a)
    next(b)
  })
}
</pre>

<p>
  To ensure that your <code>use</code> code works and is as understandable as
  possible, the right-hand-side ideally should be a regular function call
  rather than a more complex expression, which would be more difficult to
  read.
</p>
<p>
  This is a very capable and useful feature, but excessive application of
  <code>use</code> may result in unclear code, especially to beginners. Usually
  the regular function call syntax results in more approachable code!
</p>",
    code: "import gleam/result

pub fn main() {
  // These two functions do exactly the same thing, but one is written with
  // `use`, and one without.
  let _ = echo with_use()
  let _ = echo without_use()
}

pub fn with_use() -> Result(String, Nil) {
  use username <- result.try(get_username())
  use password <- result.try(get_password())
  use greeting <- result.map(log_in(username, password))
  greeting <> \", \" <> username
}

pub fn without_use() -> Result(String, Nil) {
  result.try(get_username(), fn(username) {
    result.try(get_password(), fn(password) {
      result.map(log_in(username, password), fn(greeting) {
        greeting <> \", \" <> username
      })
    })
  })
}

// Here are some pretend functions for this example:

fn get_username() -> Result(String, Nil) {
  Ok(\"alice\")
}

fn get_password() -> Result(String, Nil) {
  Ok(\"hunter2\")
}

fn log_in(_username: String, _password: String) -> Result(String, Nil) {
  Ok(\"Welcome\")
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "Todo",
    prose: "<p>
  The <code>todo</code> keyword is used to specify that some code is not yet
  implemented.
</p>
<p>
  The <code>as \"some string\"</code> is optional, though you may wish to include
  the message if you have more than one code block marked as
  <code>todo</code> in your code.
</p>
<p>
  When used the Gleam compiler will print a warning to remind you the code is
  unfinished, and if the code is run then the program will crash with the given
  message.
</p>",
    code: "pub fn main() {
  todo as \"I haven't written this code yet!\"
}

pub fn todo_without_reason() {
  todo
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "Panic",
    prose: "<p>
  The <code>panic</code> keyword is similar to the <code>todo</code> keyword,
  but it is used to crash the program when the program has reached a point that
  should never be reached.
</p>
<p>
  This keyword should almost never be used! It may be useful in initial
  prototypes and scripts, but its use in a library or production application is
  a sign that the design could be improved. With well designed types the type
  system can typically be used to make these invalid states unrepresentable.
</p>",
    code: "import gleam/io

pub fn main() {
  print_score(10)
  print_score(100_000)
  print_score(-1)
}

pub fn print_score(score: Int) {
  case score {
    score if score > 1000 -> io.println(\"High score!\")
    score if score > 0 -> io.println(\"Still working on it\")
    _ -> panic as \"Scores should never be negative!\"
  }
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "Let assert",
    prose: "<p>
  <code>let assert</code> is another way to intentionally crash your Gleam
  program. It is similar to the <code>panic</code> keyword in that it crashes
  when the program has reached a point that should never be reached.
</p>
<p>
  <code>let assert</code> is similar to <code>let</code> in that it is a way to
  assign values to variables, but it is different in that the pattern can be
  <i>partial</i>. The pattern does not need to match every possible value of the
  type being assigned.
</p>
<p>
  Just like <code>panic</code> and <code>todo</code>, the <code>as</code> keyword
  can be used with <code>let assert</code> to supply a custom panic message if
  the pattern fails to match and the program crashes.
</p>
<p>
  Like <code>panic</code> this feature should be used sparingly, and likely not
  at all in libraries.
</p>",
    code: "pub fn main() {
  let a = unsafely_get_first_element([123])
  echo a

  let b = unsafely_get_first_element([])
  echo b
}

pub fn unsafely_get_first_element(items: List(a)) -> a {
  // This will panic if the list is empty.
  // A regular `let` would not permit this partial pattern
  let assert [first, ..] = items as \"List should not be empty\"
  first
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "Bool assert",
    prose: "<p>
  Bool <code>assert</code> is the final way to cause a panic in Gleam, used for
  writing test assertions. It is similar to <code>let assert</code>, except instead
  of asserting that a value matches a specific pattern, it asserts that a boolean
  value evaluates to <code>True</code>.
</p>
<p>
  Like the other panicking keywords, the <code>as</code> keyword can be used to
  add a custom message to an assertion. This will be shown instead of the generic
  \"Assertion failed\" message if the value evaluates to <code>False</code>.
</p>
<p>
  Bool <code>assert</code> is designed to be used in test code, and should almost
  never be used in applications or libraries.
</p>",
    code: "pub fn main() {
  assert add(1, 2) == 3

  assert add(1, 2) < add(1, 3)

  assert add(6, 2) == add(2, 6) as \"Addition should be commutative\"

  assert add(2, 2) == 5
}

fn add(a: Int, b: Int) -> Int {
  a + b
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "Externals",
    prose: "<p>
  Sometimes in our projects we want to use code written in other languages, most
  commonly Erlang and JavaScript, depending on which runtime is being used.
  Gleam's <em>external functions</em> and <em>external types</em> allow us to
  import and use this non-Gleam code.
</p>
<p>
  An external type is one that has no constructors. Gleam doesn't know what
  shape it has or how to create one, it only knows that it exists.
</p>
<p>
  An external function is one that has the <code>@external</code> attribute on
  it, directing the compiler to use the specified module function as the
  implementation, instead of Gleam code.
</p>
<p>
  The compiler can't tell the types of functions written in other languages, so
  when the external attribute is given type annotations must be provided. Gleam
  trusts that the type given is correct so an inaccurate type annotation can
  result in unexpected behaviour and crashes at runtime. Be careful!
</p>
<p>
  External functions are useful but should be used sparingly. Prefer to write
  Gleam code where possible.
</p>",
    code: "// A type with no Gleam constructors
pub type DateTime

// An external function that creates an instance of the type
@external(javascript, \"./my_package_ffi.mjs\", \"now\")
pub fn now() -> DateTime

// The `now` function in `./my_package_ffi.mjs` looks like this:
// export function now() {
//   return new Date();
// }

pub fn main() {
  echo now()
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "Multi target externals",
    prose: "<p>
  Multiple external implementations can be specified for the same function,
  enabling the function to work on both Erlang and JavaScript.
</p>
<p>
  If a function doesn't have an implementation for the currently compiled-for
  target then the compiler will return an error.
</p>
<p>
  You should try to implement functions for all targets, but this isn't always
  possible due to incompatibilities in how IO and concurrency works in Erlang and
  JavaScript. With Erlang concurrent IO is handled transparently by the runtime,
  while in JavaScript concurrent IO requires the use of promises or callbacks.
  If your code uses the Erlang style it is typically not possible to implement
  in JavaScript, while if callbacks are used then it won't be compatible with
  most Gleam and Erlang code as it forces any code that calls the function to
  also use callbacks.
</p>
<p>
  Libraries that make use of concurrent IO will typically have to decide whether
  they support Erlang or JavaScript, and document this in their README.
</p>",
    code: "pub type DateTime

@external(erlang, \"calendar\", \"local_time\")
@external(javascript, \"./my_package_ffi.mjs\", \"now\")
pub fn now() -> DateTime

pub fn main() {
  echo now()
}",
  ),
  Lesson(
    chapter: "Advanced features",
    title: "External gleam fallbacks",
    prose: "<p>
  It's possible for a function to have both a Gleam implementation and an
  external implementation. If there exists an external implementation for the
  currently compiled-for target then it will be used, otherwise the Gleam
  implementation is used.
</p>
<p>
  This may be useful if you have a function that can be implemented in Gleam,
  but there is an optimised implementation that can be used for one target. For
  example, the Erlang virtual machine has a built-in list reverse function that
  is implemented in native code. The code here uses this implementation when
  running on Erlang, as it is then available.
</p>
<p>
  For further information on externals see the
  <a target=\"_blank\" rel=\"noopener\" href=\"https://gleam.run/documentation/externals/\" target=\"_blank\"
    >externals guide</a> on the Gleam website.
</p>",
    code: "@external(erlang, \"lists\", \"reverse\")
pub fn reverse_list(items: List(e)) -> List(e) {
  tail_recursive_reverse(items, [])
}

fn tail_recursive_reverse(items: List(e), reversed: List(e)) -> List(e) {
  case items {
    [] -> reversed
    [first, ..rest] -> tail_recursive_reverse(rest, [first, ..reversed])
  }
}

pub fn main() {
  echo reverse_list([1, 2, 3, 4, 5])
  echo reverse_list([\"a\", \"b\", \"c\", \"d\", \"e\"])
}",
  ),
  ]
}
