//// GENERATED by `gleam run -m generate` in drills/ — do not edit.
//// Source of truth: drills/src/*.gleam and drills/harnesses/*.gleam.

import algodrill/problem.{type Check, Check}

pub type Embedded {
  Embedded(solution: String, check: Check)
}

pub fn nc01_contains_duplicate() -> Embedded {
  Embedded(
    solution: "import gleam/set

pub fn contains_duplicate(nums: List(Int)) -> Bool {
  check(nums, set.new())
}

fn check(nums: List(Int), seen: set.Set(Int)) -> Bool {
  case nums {
    [] -> False
    [n, ..rest] ->
      case set.contains(seen, n) {
        True -> True
        False -> check(rest, set.insert(seen, n))
      }
  }
}",
    check: Check(
      signature: "pub fn contains_duplicate(nums: List(Int)) -> Bool",
      starter: "pub fn contains_duplicate(nums: List(Int)) -> Bool {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"contains_duplicate([1, 2, 3, 1])\",
      string.inspect(True),
      string.inspect(solution.contains_duplicate([1, 2, 3, 1])),
    ),
    #(
      \"contains_duplicate([1, 2, 3, 4])\",
      string.inspect(False),
      string.inspect(solution.contains_duplicate([1, 2, 3, 4])),
    ),
    #(
      \"contains_duplicate([])\",
      string.inspect(False),
      string.inspect(solution.contains_duplicate([])),
    ),
    #(
      \"contains_duplicate([7, 7])\",
      string.inspect(True),
      string.inspect(solution.contains_duplicate([7, 7])),
    ),
  ]
}",
    ),
  )
}

pub fn nc02_valid_anagram() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/list
import gleam/option
import gleam/string

pub fn is_anagram(s: String, t: String) -> Bool {
  counts(s) == counts(t)
}

fn counts(word: String) -> dict.Dict(String, Int) {
  string.to_graphemes(word)
  |> list.fold(dict.new(), fn(acc, g) {
    dict.upsert(acc, g, fn(n) { option.unwrap(n, 0) + 1 })
  })
}",
    check: Check(
      signature: "pub fn is_anagram(s: String, t: String) -> Bool",
      starter: "pub fn is_anagram(s: String, t: String) -> Bool {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"is_anagram(\\\"anagram\\\", \\\"nagaram\\\")\",
      string.inspect(True),
      string.inspect(solution.is_anagram(\"anagram\", \"nagaram\")),
    ),
    #(
      \"is_anagram(\\\"rat\\\", \\\"car\\\")\",
      string.inspect(False),
      string.inspect(solution.is_anagram(\"rat\", \"car\")),
    ),
    #(
      \"is_anagram(\\\"\\\", \\\"\\\")\",
      string.inspect(True),
      string.inspect(solution.is_anagram(\"\", \"\")),
    ),
    #(
      \"is_anagram(\\\"a\\\", \\\"ab\\\")\",
      string.inspect(False),
      string.inspect(solution.is_anagram(\"a\", \"ab\")),
    ),
  ]
}",
    ),
  )
}

pub fn nc03_two_sum() -> Embedded {
  Embedded(
    solution: "import gleam/dict

pub fn two_sum(nums: List(Int), target: Int) -> Result(#(Int, Int), Nil) {
  find_pair(nums, target, 0, dict.new())
}

fn find_pair(
  nums: List(Int),
  target: Int,
  i: Int,
  seen: dict.Dict(Int, Int),
) -> Result(#(Int, Int), Nil) {
  case nums {
    [] -> Error(Nil)
    [n, ..rest] ->
      case dict.get(seen, target - n) {
        Ok(j) -> Ok(#(j, i))
        Error(Nil) -> find_pair(rest, target, i + 1, dict.insert(seen, n, i))
      }
  }
}",
    check: Check(
      signature: "pub fn two_sum(nums: List(Int), target: Int) -> Result(#(Int, Int), Nil)",
      starter: "pub fn two_sum(nums: List(Int), target: Int) -> Result(#(Int, Int), Nil) {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"two_sum([2, 7, 11, 15], 9)\",
      string.inspect(Ok(#(0, 1))),
      string.inspect(solution.two_sum([2, 7, 11, 15], 9)),
    ),
    #(
      \"two_sum([3, 2, 4], 6)\",
      string.inspect(Ok(#(1, 2))),
      string.inspect(solution.two_sum([3, 2, 4], 6)),
    ),
    #(
      \"two_sum([3, 3], 6)\",
      string.inspect(Ok(#(0, 1))),
      string.inspect(solution.two_sum([3, 3], 6)),
    ),
    #(
      \"two_sum([1, 2], 7)\",
      string.inspect(Error(Nil)),
      string.inspect(solution.two_sum([1, 2], 7)),
    ),
  ]
}",
    ),
  )
}

pub fn nc04_group_anagrams() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/list
import gleam/option
import gleam/string

pub fn group_anagrams(strs: List(String)) -> List(List(String)) {
  strs
  |> list.fold(dict.new(), fn(acc, s) {
    let key =
      string.to_graphemes(s)
      |> list.sort(string.compare)
      |> string.concat
    dict.upsert(acc, key, fn(group) {
      case group {
        option.Some(members) -> [s, ..members]
        option.None -> [s]
      }
    })
  })
  |> dict.values
  |> list.map(list.reverse)
}",
    check: Check(
      signature: "pub fn group_anagrams(strs: List(String)) -> List(List(String))",
      starter: "pub fn group_anagrams(strs: List(String)) -> List(List(String)) {
  todo
}",
      harness: "import gleam/list
import gleam/string
import solution

/// Groups may come back in any order, and so may their members.
fn normalise(groups: List(List(String))) -> List(String) {
  groups
  |> list.map(fn(group) {
    group |> list.sort(string.compare) |> string.join(\",\")
  })
  |> list.sort(string.compare)
}

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"group_anagrams([\\\"eat\\\", \\\"tea\\\", \\\"tan\\\", \\\"ate\\\", \\\"nat\\\", \\\"bat\\\"])\",
      string.inspect([\"ate,eat,tea\", \"bat\", \"nat,tan\"]),
      string.inspect(
        normalise(solution.group_anagrams([
          \"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\",
        ])),
      ),
    ),
    #(
      \"group_anagrams([])\",
      string.inspect([]),
      string.inspect(normalise(solution.group_anagrams([]))),
    ),
    #(
      \"group_anagrams([\\\"a\\\"])\",
      string.inspect([\"a\"]),
      string.inspect(normalise(solution.group_anagrams([\"a\"]))),
    ),
  ]
}",
    ),
  )
}

pub fn nc05_top_k_frequent() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/int
import gleam/list
import gleam/option

pub fn top_k_frequent(nums: List(Int), k: Int) -> List(Int) {
  nums
  |> list.fold(dict.new(), fn(acc, n) {
    dict.upsert(acc, n, fn(count) { option.unwrap(count, 0) + 1 })
  })
  |> dict.to_list
  |> list.sort(fn(a, b) { int.compare(b.1, a.1) })
  |> list.take(k)
  |> list.map(fn(pair) { pair.0 })
}",
    check: Check(
      signature: "pub fn top_k_frequent(nums: List(Int), k: Int) -> List(Int)",
      starter: "pub fn top_k_frequent(nums: List(Int), k: Int) -> List(Int) {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"top_k_frequent([1, 1, 1, 2, 2, 3], 2)\",
      string.inspect([1, 2]),
      string.inspect(solution.top_k_frequent([1, 1, 1, 2, 2, 3], 2)),
    ),
    #(
      \"top_k_frequent([1], 1)\",
      string.inspect([1]),
      string.inspect(solution.top_k_frequent([1], 1)),
    ),
    #(
      \"top_k_frequent([5, 5, 4, 4, 4, 3], 1)\",
      string.inspect([4]),
      string.inspect(solution.top_k_frequent([5, 5, 4, 4, 4, 3], 1)),
    ),
  ]
}",
    ),
  )
}

pub fn nc06_product_except_self() -> Embedded {
  Embedded(
    solution: "import gleam/list

pub fn product_except_self(nums: List(Int)) -> List(Int) {
  let n = list.length(nums)
  let prefixes =
    [1, ..list.take(list.scan(nums, 1, fn(acc, x) { acc * x }), n - 1)]
  let suffixes =
    list.reverse(nums)
    |> list.scan(1, fn(acc, x) { acc * x })
    |> list.take(n - 1)
    |> fn(scanned) { [1, ..scanned] }
    |> list.reverse
  list.map2(prefixes, suffixes, fn(prefix, suffix) { prefix * suffix })
}",
    check: Check(
      signature: "pub fn product_except_self(nums: List(Int)) -> List(Int)",
      starter: "pub fn product_except_self(nums: List(Int)) -> List(Int) {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"product_except_self([1, 2, 3, 4])\",
      string.inspect([24, 12, 8, 6]),
      string.inspect(solution.product_except_self([1, 2, 3, 4])),
    ),
    #(
      \"product_except_self([-1, 1, 0, -3, 3])\",
      string.inspect([0, 0, 9, 0, 0]),
      string.inspect(solution.product_except_self([-1, 1, 0, -3, 3])),
    ),
    #(
      \"product_except_self([2, 3])\",
      string.inspect([3, 2]),
      string.inspect(solution.product_except_self([2, 3])),
    ),
  ]
}",
    ),
  )
}

pub fn nc07_longest_consecutive() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/list
import gleam/set

pub fn longest_consecutive(nums: List(Int)) -> Int {
  let all = set.from_list(nums)
  all
  |> set.to_list
  |> list.fold(0, fn(best, n) {
    case set.contains(all, n - 1) {
      True -> best
      False -> int.max(best, run_length(all, n, 0))
    }
  })
}

fn run_length(all: set.Set(Int), n: Int, count: Int) -> Int {
  case set.contains(all, n) {
    True -> run_length(all, n + 1, count + 1)
    False -> count
  }
}",
    check: Check(
      signature: "pub fn longest_consecutive(nums: List(Int)) -> Int",
      starter: "pub fn longest_consecutive(nums: List(Int)) -> Int {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"longest_consecutive([100, 4, 200, 1, 3, 2])\",
      string.inspect(4),
      string.inspect(solution.longest_consecutive([100, 4, 200, 1, 3, 2])),
    ),
    #(
      \"longest_consecutive([0, 3, 7, 2, 5, 8, 4, 6, 0, 1])\",
      string.inspect(9),
      string.inspect(
        solution.longest_consecutive([0, 3, 7, 2, 5, 8, 4, 6, 0, 1]),
      ),
    ),
    #(
      \"longest_consecutive([])\",
      string.inspect(0),
      string.inspect(solution.longest_consecutive([])),
    ),
  ]
}",
    ),
  )
}

pub fn nc08_valid_palindrome() -> Embedded {
  Embedded(
    solution: "import gleam/list
import gleam/string

pub fn is_palindrome(s: String) -> Bool {
  let cleaned =
    string.lowercase(s)
    |> string.to_graphemes
    |> list.filter(is_alphanumeric)
  cleaned == list.reverse(cleaned)
}

fn is_alphanumeric(g: String) -> Bool {
  case string.to_utf_codepoints(g) {
    [c] -> {
      let n = string.utf_codepoint_to_int(c)
      is_digit(n) || is_lowercase_letter(n)
    }
    _ -> False
  }
}

fn is_digit(n: Int) -> Bool {
  n >= 48 && n <= 57
}

fn is_lowercase_letter(n: Int) -> Bool {
  n >= 97 && n <= 122
}",
    check: Check(
      signature: "pub fn is_palindrome(s: String) -> Bool",
      starter: "pub fn is_palindrome(s: String) -> Bool {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"is_palindrome(\\\"A man, a plan, a canal: Panama\\\")\",
      string.inspect(True),
      string.inspect(solution.is_palindrome(\"A man, a plan, a canal: Panama\")),
    ),
    #(
      \"is_palindrome(\\\"race a car\\\")\",
      string.inspect(False),
      string.inspect(solution.is_palindrome(\"race a car\")),
    ),
    #(
      \"is_palindrome(\\\" \\\")\",
      string.inspect(True),
      string.inspect(solution.is_palindrome(\" \")),
    ),
    #(
      \"is_palindrome(\\\"0P\\\")\",
      string.inspect(False),
      string.inspect(solution.is_palindrome(\"0P\")),
    ),
  ]
}",
    ),
  )
}

pub fn nc09_two_sum_sorted() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/list
import gleam/order

pub fn two_sum_sorted(
  numbers: List(Int),
  target: Int,
) -> Result(#(Int, Int), Nil) {
  search(numbers, list.reverse(numbers), 1, list.length(numbers), target)
}

fn search(
  from_left: List(Int),
  from_right: List(Int),
  lo: Int,
  hi: Int,
  target: Int,
) -> Result(#(Int, Int), Nil) {
  case from_left, from_right {
    [left, ..left_rest], [right, ..right_rest] ->
      case lo >= hi {
        True -> Error(Nil)
        False ->
          case int.compare(left + right, target) {
            order.Eq -> Ok(#(lo, hi))
            order.Lt -> search(left_rest, from_right, lo + 1, hi, target)
            order.Gt -> search(from_left, right_rest, lo, hi - 1, target)
          }
      }
    _, _ -> Error(Nil)
  }
}",
    check: Check(
      signature: "pub fn two_sum_sorted(
  numbers: List(Int),
  target: Int,
) -> Result(#(Int, Int), Nil)",
      starter: "pub fn two_sum_sorted(
  numbers: List(Int),
  target: Int,
) -> Result(#(Int, Int), Nil) {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"two_sum_sorted([2, 7, 11, 15], 9)\",
      string.inspect(Ok(#(1, 2))),
      string.inspect(solution.two_sum_sorted([2, 7, 11, 15], 9)),
    ),
    #(
      \"two_sum_sorted([2, 3, 4], 6)\",
      string.inspect(Ok(#(1, 3))),
      string.inspect(solution.two_sum_sorted([2, 3, 4], 6)),
    ),
    #(
      \"two_sum_sorted([-1, 0], -1)\",
      string.inspect(Ok(#(1, 2))),
      string.inspect(solution.two_sum_sorted([-1, 0], -1)),
    ),
    #(
      \"two_sum_sorted([1, 2, 3], 100)\",
      string.inspect(Error(Nil)),
      string.inspect(solution.two_sum_sorted([1, 2, 3], 100)),
    ),
  ]
}",
    ),
  )
}

pub fn nc10_three_sum() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/list
import gleam/order
import gleam/set

pub fn three_sum(nums: List(Int)) -> List(#(Int, Int, Int)) {
  let sorted = list.sort(nums, int.compare)
  outer(sorted, set.new())
  |> set.to_list
}

fn outer(
  nums: List(Int),
  acc: set.Set(#(Int, Int, Int)),
) -> set.Set(#(Int, Int, Int)) {
  case nums {
    [] -> acc
    [first, ..rest] ->
      outer(rest, inner(first, rest, list.reverse(rest), list.length(rest), acc))
  }
}

fn inner(
  first: Int,
  from_left: List(Int),
  from_right: List(Int),
  remaining: Int,
  acc: set.Set(#(Int, Int, Int)),
) -> set.Set(#(Int, Int, Int)) {
  case remaining < 2 {
    True -> acc
    False ->
      case from_left, from_right {
        [left, ..left_rest], [right, ..right_rest] ->
          case int.compare(first + left + right, 0) {
            order.Eq ->
              inner(
                first,
                left_rest,
                from_right,
                remaining - 1,
                set.insert(acc, #(first, left, right)),
              )
            order.Lt -> inner(first, left_rest, from_right, remaining - 1, acc)
            order.Gt -> inner(first, from_left, right_rest, remaining - 1, acc)
          }
        _, _ -> acc
      }
  }
}",
    check: Check(
      signature: "pub fn three_sum(nums: List(Int)) -> List(#(Int, Int, Int))",
      starter: "pub fn three_sum(nums: List(Int)) -> List(#(Int, Int, Int)) {
  todo
}",
      harness: "import gleam/list
import gleam/string
import solution

/// Triples come back in set order, which is not meaningful.
fn normalise(triples: List(#(Int, Int, Int))) -> List(String) {
  triples |> list.map(string.inspect) |> list.sort(string.compare)
}

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"three_sum([-1, 0, 1, 2, -1, -4])\",
      string.inspect([\"#(-1, -1, 2)\", \"#(-1, 0, 1)\"]),
      string.inspect(normalise(solution.three_sum([-1, 0, 1, 2, -1, -4]))),
    ),
    #(
      \"three_sum([0, 1, 1])\",
      string.inspect([]),
      string.inspect(normalise(solution.three_sum([0, 1, 1]))),
    ),
    #(
      \"three_sum([0, 0, 0])\",
      string.inspect([\"#(0, 0, 0)\"]),
      string.inspect(normalise(solution.three_sum([0, 0, 0]))),
    ),
  ]
}",
    ),
  )
}

pub fn nc11_container_water() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/list

pub fn max_area(heights: List(Int)) -> Int {
  converge(heights, list.reverse(heights), list.length(heights) - 1, 0)
}

fn converge(
  from_left: List(Int),
  from_right: List(Int),
  width: Int,
  best: Int,
) -> Int {
  case width <= 0 {
    True -> best
    False ->
      case from_left, from_right {
        [left, ..left_rest], [right, ..right_rest] -> {
          let area = int.min(left, right) * width
          let best = int.max(best, area)
          case left < right {
            True -> converge(left_rest, from_right, width - 1, best)
            False -> converge(from_left, right_rest, width - 1, best)
          }
        }
        _, _ -> best
      }
  }
}",
    check: Check(
      signature: "pub fn max_area(heights: List(Int)) -> Int",
      starter: "pub fn max_area(heights: List(Int)) -> Int {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"max_area([1, 8, 6, 2, 5, 4, 8, 3, 7])\",
      string.inspect(49),
      string.inspect(solution.max_area([1, 8, 6, 2, 5, 4, 8, 3, 7])),
    ),
    #(
      \"max_area([1, 1])\",
      string.inspect(1),
      string.inspect(solution.max_area([1, 1])),
    ),
    #(
      \"max_area([])\",
      string.inspect(0),
      string.inspect(solution.max_area([])),
    ),
  ]
}",
    ),
  )
}

pub fn nc12_best_time_stock() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/list

pub fn max_profit(prices: List(Int)) -> Int {
  case prices {
    [] -> 0
    [first, ..rest] -> {
      let #(_, best) =
        list.fold(rest, #(first, 0), fn(acc, price) {
          let #(min_price, best) = acc
          #(int.min(min_price, price), int.max(best, price - min_price))
        })
      best
    }
  }
}",
    check: Check(
      signature: "pub fn max_profit(prices: List(Int)) -> Int",
      starter: "pub fn max_profit(prices: List(Int)) -> Int {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"max_profit([7, 1, 5, 3, 6, 4])\",
      string.inspect(5),
      string.inspect(solution.max_profit([7, 1, 5, 3, 6, 4])),
    ),
    #(
      \"max_profit([7, 6, 4, 3, 1])\",
      string.inspect(0),
      string.inspect(solution.max_profit([7, 6, 4, 3, 1])),
    ),
    #(
      \"max_profit([])\",
      string.inspect(0),
      string.inspect(solution.max_profit([])),
    ),
  ]
}",
    ),
  )
}

pub fn nc13_longest_substring() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/int
import gleam/list
import gleam/string

pub fn length_of_longest_substring(s: String) -> Int {
  let #(_, _, best) =
    string.to_graphemes(s)
    |> list.index_fold(#(dict.new(), 0, 0), fn(acc, g, i) {
      let #(last_seen, start, best) = acc
      let start = case dict.get(last_seen, g) {
        Ok(j) if j >= start -> j + 1
        _ -> start
      }
      #(dict.insert(last_seen, g, i), start, int.max(best, i - start + 1))
    })
  best
}",
    check: Check(
      signature: "pub fn length_of_longest_substring(s: String) -> Int",
      starter: "pub fn length_of_longest_substring(s: String) -> Int {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"length_of_longest_substring(\\\"abcabcbb\\\")\",
      string.inspect(3),
      string.inspect(solution.length_of_longest_substring(\"abcabcbb\")),
    ),
    #(
      \"length_of_longest_substring(\\\"bbbbb\\\")\",
      string.inspect(1),
      string.inspect(solution.length_of_longest_substring(\"bbbbb\")),
    ),
    #(
      \"length_of_longest_substring(\\\"pwwkew\\\")\",
      string.inspect(3),
      string.inspect(solution.length_of_longest_substring(\"pwwkew\")),
    ),
    #(
      \"length_of_longest_substring(\\\"\\\")\",
      string.inspect(0),
      string.inspect(solution.length_of_longest_substring(\"\")),
    ),
  ]
}",
    ),
  )
}

pub fn nc14_character_replacement() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/int
import gleam/list
import gleam/option
import gleam/string

pub fn character_replacement(s: String, k: Int) -> Int {
  let #(_, _, best) =
    string.to_graphemes(s)
    |> list.fold(#(dict.new(), [], 0), fn(acc, g) {
      let #(counts, window, best) = acc
      let counts = dict.upsert(counts, g, fn(n) { option.unwrap(n, 0) + 1 })
      let window = list.append(window, [g])
      let #(counts, window) = shrink(counts, window, k)
      #(counts, window, int.max(best, list.length(window)))
    })
  best
}

fn shrink(
  counts: dict.Dict(String, Int),
  window: List(String),
  k: Int,
) -> #(dict.Dict(String, Int), List(String)) {
  let size = list.length(window)
  let max_count = dict.fold(counts, 0, fn(top, _, count) { int.max(top, count) })
  case size - max_count > k, window {
    True, [oldest, ..rest] ->
      shrink(
        dict.upsert(counts, oldest, fn(n) { option.unwrap(n, 1) - 1 }),
        rest,
        k,
      )
    _, _ -> #(counts, window)
  }
}",
    check: Check(
      signature: "pub fn character_replacement(s: String, k: Int) -> Int",
      starter: "pub fn character_replacement(s: String, k: Int) -> Int {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"character_replacement(\\\"ABAB\\\", 2)\",
      string.inspect(4),
      string.inspect(solution.character_replacement(\"ABAB\", 2)),
    ),
    #(
      \"character_replacement(\\\"AABABBA\\\", 1)\",
      string.inspect(4),
      string.inspect(solution.character_replacement(\"AABABBA\", 1)),
    ),
    #(
      \"character_replacement(\\\"AAAA\\\", 0)\",
      string.inspect(4),
      string.inspect(solution.character_replacement(\"AAAA\", 0)),
    ),
  ]
}",
    ),
  )
}

pub fn nc15_permutation_in_string() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/list
import gleam/option
import gleam/string

pub fn check_inclusion(s1: String, s2: String) -> Bool {
  let needle = counts(string.to_graphemes(s1))
  let size = string.length(s1)
  let graphemes = string.to_graphemes(s2)
  slide(
    graphemes,
    list.drop(graphemes, size),
    counts(list.take(graphemes, size)),
    needle,
  )
}

fn counts(graphemes: List(String)) -> dict.Dict(String, Int) {
  list.fold(graphemes, dict.new(), fn(acc, g) {
    dict.upsert(acc, g, fn(n) { option.unwrap(n, 0) + 1 })
  })
}

fn slide(
  window_start: List(String),
  upcoming: List(String),
  window: dict.Dict(String, Int),
  needle: dict.Dict(String, Int),
) -> Bool {
  case window == needle {
    True -> True
    False ->
      case window_start, upcoming {
        [oldest, ..rest_start], [next, ..rest_upcoming] ->
          slide(
            rest_start,
            rest_upcoming,
            window
              |> remove_one(oldest)
              |> dict.upsert(next, fn(n) { option.unwrap(n, 0) + 1 }),
            needle,
          )
        _, _ -> False
      }
  }
}

fn remove_one(
  window: dict.Dict(String, Int),
  g: String,
) -> dict.Dict(String, Int) {
  case dict.get(window, g) {
    Ok(1) -> dict.delete(window, g)
    Ok(n) -> dict.insert(window, g, n - 1)
    Error(Nil) -> window
  }
}",
    check: Check(
      signature: "pub fn check_inclusion(s1: String, s2: String) -> Bool",
      starter: "pub fn check_inclusion(s1: String, s2: String) -> Bool {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"check_inclusion(\\\"ab\\\", \\\"eidbaooo\\\")\",
      string.inspect(True),
      string.inspect(solution.check_inclusion(\"ab\", \"eidbaooo\")),
    ),
    #(
      \"check_inclusion(\\\"ab\\\", \\\"eidboaoo\\\")\",
      string.inspect(False),
      string.inspect(solution.check_inclusion(\"ab\", \"eidboaoo\")),
    ),
    #(
      \"check_inclusion(\\\"adc\\\", \\\"dcda\\\")\",
      string.inspect(True),
      string.inspect(solution.check_inclusion(\"adc\", \"dcda\")),
    ),
  ]
}",
    ),
  )
}

pub fn nc16_valid_parentheses() -> Embedded {
  Embedded(
    solution: "import gleam/string

pub fn is_valid(s: String) -> Bool {
  check(string.to_graphemes(s), [])
}

fn check(graphemes: List(String), stack: List(String)) -> Bool {
  case graphemes, stack {
    [], [] -> True
    [], _ -> False
    [\"(\", ..rest], _ -> check(rest, [\")\", ..stack])
    [\"[\", ..rest], _ -> check(rest, [\"]\", ..stack])
    [\"{\", ..rest], _ -> check(rest, [\"}\", ..stack])
    [close, ..rest], [expected, ..stack_rest] ->
      close == expected && check(rest, stack_rest)
    _, _ -> False
  }
}",
    check: Check(
      signature: "pub fn is_valid(s: String) -> Bool",
      starter: "pub fn is_valid(s: String) -> Bool {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"is_valid(\\\"()[]{}\\\")\",
      string.inspect(True),
      string.inspect(solution.is_valid(\"()[]{}\")),
    ),
    #(
      \"is_valid(\\\"(]\\\")\",
      string.inspect(False),
      string.inspect(solution.is_valid(\"(]\")),
    ),
    #(
      \"is_valid(\\\"([)]\\\")\",
      string.inspect(False),
      string.inspect(solution.is_valid(\"([)]\")),
    ),
    #(
      \"is_valid(\\\"{[]}\\\")\",
      string.inspect(True),
      string.inspect(solution.is_valid(\"{[]}\")),
    ),
    #(\"is_valid(\\\"(\\\")\", string.inspect(False), string.inspect(solution.is_valid(\"(\"))),
  ]
}",
    ),
  )
}

pub fn nc17_min_stack() -> Embedded {
  Embedded(
    solution: "import gleam/int

pub type MinStack {
  MinStack(entries: List(#(Int, Int)))
}

pub fn new() -> MinStack {
  MinStack([])
}

pub fn push(stack: MinStack, value: Int) -> MinStack {
  let min = case stack.entries {
    [#(_, current_min), ..] -> int.min(value, current_min)
    [] -> value
  }
  MinStack([#(value, min), ..stack.entries])
}

pub fn pop(stack: MinStack) -> MinStack {
  case stack.entries {
    [_, ..rest] -> MinStack(rest)
    [] -> stack
  }
}

pub fn top(stack: MinStack) -> Result(Int, Nil) {
  case stack.entries {
    [#(value, _), ..] -> Ok(value)
    [] -> Error(Nil)
  }
}

pub fn get_min(stack: MinStack) -> Result(Int, Nil) {
  case stack.entries {
    [#(_, min), ..] -> Ok(min)
    [] -> Error(Nil)
  }
}",
    check: Check(
      signature: "pub type MinStack {
  MinStack(entries: List(#(Int, Int)))
}

pub fn new() -> MinStack

pub fn push(stack: MinStack, value: Int) -> MinStack

pub fn pop(stack: MinStack) -> MinStack

pub fn top(stack: MinStack) -> Result(Int, Nil)

pub fn get_min(stack: MinStack) -> Result(Int, Nil)",
      starter: "pub type MinStack {
  MinStack(entries: List(#(Int, Int)))
}

pub fn new() -> MinStack {
  todo
}

pub fn push(stack: MinStack, value: Int) -> MinStack {
  todo
}

pub fn pop(stack: MinStack) -> MinStack {
  todo
}

pub fn top(stack: MinStack) -> Result(Int, Nil) {
  todo
}

pub fn get_min(stack: MinStack) -> Result(Int, Nil) {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  let stack =
    solution.new()
    |> solution.push(-2)
    |> solution.push(0)
    |> solution.push(-3)
  let popped = solution.pop(stack)

  [
    #(
      \"get_min() after push -2, 0, -3\",
      string.inspect(Ok(-3)),
      string.inspect(solution.get_min(stack)),
    ),
    #(\"top() after pop()\", string.inspect(Ok(0)), string.inspect(solution.top(popped))),
    #(
      \"get_min() after pop()\",
      string.inspect(Ok(-2)),
      string.inspect(solution.get_min(popped)),
    ),
    #(
      \"top() on an empty stack\",
      string.inspect(Error(Nil)),
      string.inspect(solution.top(solution.new())),
    ),
  ]
}",
    ),
  )
}

pub fn nc18_daily_temperatures() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/list

pub fn daily_temperatures(temps: List(Int)) -> List(Int) {
  let #(answers, _) =
    temps
    |> list.index_fold(#(dict.new(), []), fn(acc, temp, i) {
      let #(answers, stack) = acc
      let #(answers, stack) = pop_colder(answers, stack, temp, i)
      #(answers, [#(i, temp), ..stack])
    })
  list.index_map(temps, fn(_, i) {
    case dict.get(answers, i) {
      Ok(days) -> days
      Error(Nil) -> 0
    }
  })
}

fn pop_colder(
  answers: dict.Dict(Int, Int),
  stack: List(#(Int, Int)),
  temp: Int,
  i: Int,
) -> #(dict.Dict(Int, Int), List(#(Int, Int))) {
  case stack {
    [#(j, colder), ..rest] if colder < temp ->
      pop_colder(dict.insert(answers, j, i - j), rest, temp, i)
    _ -> #(answers, stack)
  }
}",
    check: Check(
      signature: "pub fn daily_temperatures(temps: List(Int)) -> List(Int)",
      starter: "pub fn daily_temperatures(temps: List(Int)) -> List(Int) {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"daily_temperatures([73, 74, 75, 71, 69, 72, 76, 73])\",
      string.inspect([1, 1, 4, 2, 1, 1, 0, 0]),
      string.inspect(
        solution.daily_temperatures([73, 74, 75, 71, 69, 72, 76, 73]),
      ),
    ),
    #(
      \"daily_temperatures([30, 40, 50, 60])\",
      string.inspect([1, 1, 1, 0]),
      string.inspect(solution.daily_temperatures([30, 40, 50, 60])),
    ),
    #(
      \"daily_temperatures([30, 30, 30])\",
      string.inspect([0, 0, 0]),
      string.inspect(solution.daily_temperatures([30, 30, 30])),
    ),
  ]
}",
    ),
  )
}

pub fn nc19_binary_search() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/list
import gleam/order

pub fn search(nums: List(Int), target: Int) -> Result(Int, Nil) {
  halve(nums, target, 0)
}

fn halve(nums: List(Int), target: Int, offset: Int) -> Result(Int, Nil) {
  case nums {
    [] -> Error(Nil)
    _ -> {
      let half = list.length(nums) / 2
      let #(left, right) = list.split(nums, half)
      case right {
        [mid, ..after] ->
          case int.compare(target, mid) {
            order.Eq -> Ok(offset + half)
            order.Lt -> halve(left, target, offset)
            order.Gt -> halve(after, target, offset + half + 1)
          }
        [] -> Error(Nil)
      }
    }
  }
}",
    check: Check(
      signature: "pub fn search(nums: List(Int), target: Int) -> Result(Int, Nil)",
      starter: "pub fn search(nums: List(Int), target: Int) -> Result(Int, Nil) {
  todo
}",
      harness: "import gleam/string
import solution

const no_ints: List(Int) = []

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"search([-1, 0, 3, 5, 9, 12], 9)\",
      string.inspect(Ok(4)),
      string.inspect(solution.search([-1, 0, 3, 5, 9, 12], 9)),
    ),
    #(
      \"search([-1, 0, 3, 5, 9, 12], 2)\",
      string.inspect(Error(Nil)),
      string.inspect(solution.search([-1, 0, 3, 5, 9, 12], 2)),
    ),
    #(\"search([5], 5)\", string.inspect(Ok(0)), string.inspect(solution.search([5], 5))),
    #(
      \"search([], 1)\",
      string.inspect(Error(Nil)),
      string.inspect(solution.search(no_ints, 1)),
    ),
  ]
}",
    ),
  )
}

pub fn nc20_find_min_rotated() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/list
import gleam/result

pub fn find_min(nums: List(Int)) -> Result(Int, Nil) {
  case nums {
    [] -> Error(Nil)
    [only] -> Ok(only)
    [a, b] -> Ok(int.min(a, b))
    _ -> {
      use first <- result.try(list.first(nums))
      use last <- result.try(list.last(nums))
      case first <= last {
        // This segment is fully sorted: the rotation point is not inside it.
        True -> Ok(first)
        False -> {
          let half = list.length(nums) / 2
          let #(left, right) = list.split(nums, half)
          case right {
            [mid, ..after] ->
              case mid >= first {
                // Left half sorted: the minimum is past the midpoint.
                True -> find_min(after)
                // Rotation point is in the left half, up to and including mid.
                False -> find_min(list.append(left, [mid]))
              }
            [] -> Error(Nil)
          }
        }
      }
    }
  }
}",
    check: Check(
      signature: "pub fn find_min(nums: List(Int)) -> Result(Int, Nil)",
      starter: "pub fn find_min(nums: List(Int)) -> Result(Int, Nil) {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"find_min([3, 4, 5, 1, 2])\",
      string.inspect(Ok(1)),
      string.inspect(solution.find_min([3, 4, 5, 1, 2])),
    ),
    #(
      \"find_min([4, 5, 6, 7, 0, 1, 2])\",
      string.inspect(Ok(0)),
      string.inspect(solution.find_min([4, 5, 6, 7, 0, 1, 2])),
    ),
    #(
      \"find_min([11, 13, 15, 17])\",
      string.inspect(Ok(11)),
      string.inspect(solution.find_min([11, 13, 15, 17])),
    ),
    #(\"find_min([2, 1])\", string.inspect(Ok(1)), string.inspect(solution.find_min([2, 1]))),
  ]
}",
    ),
  )
}

pub fn nc21_search_rotated() -> Embedded {
  Embedded(
    solution: "import gleam/list
import gleam/result

pub fn search_rotated(nums: List(Int), target: Int) -> Result(Int, Nil) {
  halve(nums, target, 0)
}

fn halve(nums: List(Int), target: Int, offset: Int) -> Result(Int, Nil) {
  case nums {
    [] -> Error(Nil)
    [only] ->
      case only == target {
        True -> Ok(offset)
        False -> Error(Nil)
      }
    _ -> {
      let half = list.length(nums) / 2
      let #(left, right) = list.split(nums, half)
      use first <- result.try(list.first(nums))
      use last <- result.try(list.last(nums))
      case right {
        [mid, ..after] ->
          case mid == target {
            True -> Ok(offset + half)
            False ->
              case first <= mid {
                // Left half is sorted.
                True ->
                  case first <= target && target < mid {
                    True -> halve(left, target, offset)
                    False -> halve(after, target, offset + half + 1)
                  }
                // Right half is sorted.
                False ->
                  case mid < target && target <= last {
                    True -> halve(after, target, offset + half + 1)
                    False -> halve(left, target, offset)
                  }
              }
          }
        [] -> Error(Nil)
      }
    }
  }
}",
    check: Check(
      signature: "pub fn search_rotated(nums: List(Int), target: Int) -> Result(Int, Nil)",
      starter: "pub fn search_rotated(nums: List(Int), target: Int) -> Result(Int, Nil) {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"search_rotated([4, 5, 6, 7, 0, 1, 2], 0)\",
      string.inspect(Ok(4)),
      string.inspect(solution.search_rotated([4, 5, 6, 7, 0, 1, 2], 0)),
    ),
    #(
      \"search_rotated([4, 5, 6, 7, 0, 1, 2], 3)\",
      string.inspect(Error(Nil)),
      string.inspect(solution.search_rotated([4, 5, 6, 7, 0, 1, 2], 3)),
    ),
    #(
      \"search_rotated([1], 1)\",
      string.inspect(Ok(0)),
      string.inspect(solution.search_rotated([1], 1)),
    ),
    #(
      \"search_rotated([4, 5, 6, 7, 0, 1, 2], 6)\",
      string.inspect(Ok(2)),
      string.inspect(solution.search_rotated([4, 5, 6, 7, 0, 1, 2], 6)),
    ),
  ]
}",
    ),
  )
}

pub fn tip01_list_patterns() -> Embedded {
  Embedded(
    solution: "pub fn length(items: List(a)) -> Int {
  case items {
    [] -> 0
    [_, ..rest] -> 1 + length(rest)
  }
}

pub fn last(items: List(a)) -> Result(a, Nil) {
  case items {
    [] -> Error(Nil)
    [only] -> Ok(only)
    [_, ..rest] -> last(rest)
  }
}",
    check: Check(
      signature: "pub fn length(items: List(a)) -> Int

pub fn last(items: List(a)) -> Result(a, Nil)",
      starter: "pub fn length(items: List(a)) -> Int {
  todo
}

pub fn last(items: List(a)) -> Result(a, Nil) {
  todo
}",
      harness: "import gleam/string
import solution

const no_ints: List(Int) = []

pub fn run() -> List(#(String, String, String)) {
  [
    #(\"length([1, 2, 3])\", string.inspect(3), string.inspect(solution.length([1, 2, 3]))),
    #(\"length([])\", string.inspect(0), string.inspect(solution.length(no_ints))),
    #(\"last([1, 2, 3])\", string.inspect(Ok(3)), string.inspect(solution.last([1, 2, 3]))),
    #(
      \"last([])\",
      string.inspect(Error(Nil)),
      string.inspect(solution.last(no_ints)),
    ),
  ]
}",
    ),
  )
}

pub fn tip02_tail_recursion() -> Embedded {
  Embedded(
    solution: "pub fn reverse(items: List(a)) -> List(a) {
  reverse_loop(items, [])
}

fn reverse_loop(items: List(a), acc: List(a)) -> List(a) {
  case items {
    [] -> acc
    [first, ..rest] -> reverse_loop(rest, [first, ..acc])
  }
}

pub fn sum(numbers: List(Int)) -> Int {
  sum_loop(numbers, 0)
}

fn sum_loop(numbers: List(Int), acc: Int) -> Int {
  case numbers {
    [] -> acc
    [first, ..rest] -> sum_loop(rest, acc + first)
  }
}",
    check: Check(
      signature: "pub fn reverse(items: List(a)) -> List(a)

pub fn sum(numbers: List(Int)) -> Int",
      starter: "pub fn reverse(items: List(a)) -> List(a) {
  todo
}

pub fn sum(numbers: List(Int)) -> Int {
  todo
}",
      harness: "import gleam/string
import solution

const no_ints: List(Int) = []

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"reverse([1, 2, 3])\",
      string.inspect([3, 2, 1]),
      string.inspect(solution.reverse([1, 2, 3])),
    ),
    #(
      \"reverse([])\",
      string.inspect(no_ints),
      string.inspect(solution.reverse(no_ints)),
    ),
    #(\"sum([1, 2, 3])\", string.inspect(6), string.inspect(solution.sum([1, 2, 3]))),
    #(\"sum([])\", string.inspect(0), string.inspect(solution.sum([]))),
  ]
}",
    ),
  )
}

pub fn tip03_fold() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/list

pub fn max(numbers: List(Int)) -> Result(Int, Nil) {
  case numbers {
    [] -> Error(Nil)
    [first, ..rest] -> Ok(list.fold(rest, first, int.max))
  }
}

pub fn count_if(items: List(a), predicate: fn(a) -> Bool) -> Int {
  list.fold(items, 0, fn(count, item) {
    case predicate(item) {
      True -> count + 1
      False -> count
    }
  })
}

pub fn running_total(numbers: List(Int)) -> List(Int) {
  list.scan(numbers, 0, fn(acc, n) { acc + n })
}",
    check: Check(
      signature: "pub fn max(numbers: List(Int)) -> Result(Int, Nil)

pub fn count_if(items: List(a), predicate: fn(a) -> Bool) -> Int

pub fn running_total(numbers: List(Int)) -> List(Int)",
      starter: "pub fn max(numbers: List(Int)) -> Result(Int, Nil) {
  todo
}

pub fn count_if(items: List(a), predicate: fn(a) -> Bool) -> Int {
  todo
}

pub fn running_total(numbers: List(Int)) -> List(Int) {
  todo
}",
      harness: "import gleam/string
import solution

const no_ints: List(Int) = []

pub fn run() -> List(#(String, String, String)) {
  [
    #(\"max([3, 1, 2])\", string.inspect(Ok(3)), string.inspect(solution.max([3, 1, 2]))),
    #(\"max([])\", string.inspect(Error(Nil)), string.inspect(solution.max(no_ints))),
    #(
      \"count_if([1, 2, 3, 4], is_even)\",
      string.inspect(2),
      string.inspect(solution.count_if([1, 2, 3, 4], fn(n) { n % 2 == 0 })),
    ),
    #(
      \"running_total([1, 2, 3])\",
      string.inspect([1, 3, 6]),
      string.inspect(solution.running_total([1, 2, 3])),
    ),
  ]
}",
    ),
  )
}

pub fn tip04_frequency_maps() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/list
import gleam/option
import gleam/string

pub fn word_frequencies(text: String) -> dict.Dict(String, Int) {
  text
  |> string.lowercase
  |> string.split(\" \")
  |> list.filter(fn(word) { word != \"\" })
  |> list.fold(dict.new(), fn(counts, word) {
    dict.upsert(counts, word, fn(n) { option.unwrap(n, 0) + 1 })
  })
}",
    check: Check(
      signature: "pub fn word_frequencies(text: String) -> dict.Dict(String, Int)",
      starter: "pub fn word_frequencies(text: String) -> dict.Dict(String, Int) {
  todo
}",
      harness: "import gleam/dict
import gleam/list
import gleam/string
import solution

/// Dicts have no meaningful order, so compare a sorted association list.
fn normalise(counts: dict.Dict(String, Int)) -> List(#(String, Int)) {
  counts
  |> dict.to_list
  |> list.sort(fn(a, b) { string.compare(a.0, b.0) })
}

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"word_frequencies(\\\"the cat and the hat\\\")\",
      string.inspect([#(\"and\", 1), #(\"cat\", 1), #(\"hat\", 1), #(\"the\", 2)]),
      string.inspect(normalise(solution.word_frequencies(\"the cat and the hat\"))),
    ),
    #(
      \"word_frequencies(\\\"\\\")\",
      string.inspect([]),
      string.inspect(normalise(solution.word_frequencies(\"\"))),
    ),
    #(
      \"word_frequencies(\\\"Go go GO\\\")\",
      string.inspect([#(\"go\", 3)]),
      string.inspect(normalise(solution.word_frequencies(\"Go go GO\"))),
    ),
  ]
}",
    ),
  )
}

pub fn tip05_result_chains() -> Embedded {
  Embedded(
    solution: "import gleam/int
import gleam/result

pub type Config {
  Config(host: String, port: Int, timeout: Int)
}

pub fn parse_config(
  host: String,
  port: String,
  timeout: String,
) -> Result(Config, Nil) {
  use port <- result.try(int.parse(port))
  use timeout <- result.try(int.parse(timeout))
  case host {
    \"\" -> Error(Nil)
    _ -> Ok(Config(host, port, timeout))
  }
}",
    check: Check(
      signature: "pub type Config {
  Config(host: String, port: Int, timeout: Int)
}

pub fn parse_config(
  host: String,
  port: String,
  timeout: String,
) -> Result(Config, Nil)",
      starter: "pub type Config {
  Config(host: String, port: Int, timeout: Int)
}

pub fn parse_config(
  host: String,
  port: String,
  timeout: String,
) -> Result(Config, Nil) {
  todo
}",
      harness: "import gleam/result
import gleam/string
import solution

/// Compared field-by-field rather than by inspecting the record, so the check does
/// not depend on how the constructor renders. The annotation is required: Gleam
/// cannot infer a record type from field access alone.
fn fields(
  parsed: Result(solution.Config, Nil),
) -> Result(#(String, Int, Int), Nil) {
  result.map(parsed, fn(config) {
    #(config.host, config.port, config.timeout)
  })
}

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"parse_config(\\\"localhost\\\", \\\"8080\\\", \\\"30\\\")\",
      string.inspect(Ok(#(\"localhost\", 8080, 30))),
      string.inspect(fields(solution.parse_config(\"localhost\", \"8080\", \"30\"))),
    ),
    #(
      \"parse_config(\\\"localhost\\\", \\\"oops\\\", \\\"30\\\")\",
      string.inspect(Error(Nil)),
      string.inspect(fields(solution.parse_config(\"localhost\", \"oops\", \"30\"))),
    ),
    #(
      \"parse_config(\\\"\\\", \\\"8080\\\", \\\"30\\\")\",
      string.inspect(Error(Nil)),
      string.inspect(fields(solution.parse_config(\"\", \"8080\", \"30\"))),
    ),
  ]
}",
    ),
  )
}

pub fn tip06_option() -> Embedded {
  Embedded(
    solution: "import gleam/dict
import gleam/option

pub fn port_description(config: dict.Dict(String, String)) -> String {
  let port =
    dict.get(config, \"port\")
    |> option.from_result
    |> option.map(fn(raw) { raw <> \" (configured)\" })
    |> option.unwrap(\"8080 (default)\")
  \"port: \" <> port
}",
    check: Check(
      signature: "pub fn port_description(config: dict.Dict(String, String)) -> String",
      starter: "pub fn port_description(config: dict.Dict(String, String)) -> String {
  todo
}",
      harness: "import gleam/dict
import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"port_description(dict with port 9000\",
      string.inspect(\"port: 9000 (configured)\"),
      string.inspect(
        solution.port_description(dict.from_list([#(\"port\", \"9000\")])),
      ),
    ),
    #(
      \"port_description(empty dict)\",
      string.inspect(\"port: 8080 (default)\"),
      string.inspect(solution.port_description(dict.new())),
    ),
  ]
}",
    ),
  )
}

pub fn tip07_string_patterns() -> Embedded {
  Embedded(
    solution: "import gleam/list
import gleam/string

pub fn strip_comment(line: String) -> String {
  case line {
    \"# \" <> rest -> rest
    \"#\" <> rest -> rest
    _ -> line
  }
}

pub fn initials(name: String) -> String {
  name
  |> string.split(\" \")
  |> list.filter_map(fn(word) { list.first(string.to_graphemes(word)) })
  |> string.concat
  |> string.uppercase
}",
    check: Check(
      signature: "pub fn strip_comment(line: String) -> String

pub fn initials(name: String) -> String",
      starter: "pub fn strip_comment(line: String) -> String {
  todo
}

pub fn initials(name: String) -> String {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"strip_comment(\\\"# hello\\\")\",
      string.inspect(\"hello\"),
      string.inspect(solution.strip_comment(\"# hello\")),
    ),
    #(
      \"strip_comment(\\\"code\\\")\",
      string.inspect(\"code\"),
      string.inspect(solution.strip_comment(\"code\")),
    ),
    #(
      \"initials(\\\"ada lovelace\\\")\",
      string.inspect(\"AL\"),
      string.inspect(solution.initials(\"ada lovelace\")),
    ),
    #(
      \"initials(\\\"grace brewster murray hopper\\\")\",
      string.inspect(\"GBMH\"),
      string.inspect(solution.initials(\"grace brewster murray hopper\")),
    ),
  ]
}",
    ),
  )
}

pub fn tip08_pipelines() -> Embedded {
  Embedded(
    solution: "import gleam/list
import gleam/string

pub fn slug(title: String) -> String {
  title
  |> string.trim
  |> string.lowercase
  |> string.split(\" \")
  |> list.filter(fn(word) { word != \"\" })
  |> string.join(\"-\")
}",
    check: Check(
      signature: "pub fn slug(title: String) -> String",
      starter: "pub fn slug(title: String) -> String {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"slug(\\\"  Hello   Brave World \\\")\",
      string.inspect(\"hello-brave-world\"),
      string.inspect(solution.slug(\"  Hello   Brave World \")),
    ),
    #(\"slug(\\\"Gleam\\\")\", string.inspect(\"gleam\"), string.inspect(solution.slug(\"Gleam\"))),
    #(\"slug(\\\"\\\")\", string.inspect(\"\"), string.inspect(solution.slug(\"\"))),
  ]
}",
    ),
  )
}

pub fn tip09_records() -> Embedded {
  Embedded(
    solution: "pub type Player {
  Player(name: String, score: Int, level: Int)
}

pub fn new_player(name: String) -> Player {
  Player(name: name, score: 0, level: 1)
}

pub fn add_points(player: Player, points: Int) -> Player {
  Player(..player, score: player.score + points)
}

pub fn level_up(player: Player) -> Player {
  Player(..player, level: player.level + 1, score: 0)
}",
    check: Check(
      signature: "pub type Player {
  Player(name: String, score: Int, level: Int)
}

pub fn new_player(name: String) -> Player

pub fn add_points(player: Player, points: Int) -> Player

pub fn level_up(player: Player) -> Player",
      starter: "pub type Player {
  Player(name: String, score: Int, level: Int)
}

pub fn new_player(name: String) -> Player {
  todo
}

pub fn add_points(player: Player, points: Int) -> Player {
  todo
}

pub fn level_up(player: Player) -> Player {
  todo
}",
      harness: "import gleam/string
import solution

pub fn run() -> List(#(String, String, String)) {
  let player = solution.new_player(\"lucy\") |> solution.add_points(10)
  let levelled = solution.level_up(player)

  [
    #(
      \"new_player(\\\"lucy\\\") fields\",
      string.inspect(#(\"lucy\", 0, 1)),
      string.inspect({
        let fresh = solution.new_player(\"lucy\")
        #(fresh.name, fresh.score, fresh.level)
      }),
    ),
    #(
      \"add_points(player, 10) score\",
      string.inspect(10),
      string.inspect(player.score),
    ),
    #(
      \"level_up(player) level and score\",
      string.inspect(#(2, 0)),
      string.inspect(#(levelled.level, levelled.score)),
    ),
    #(\"level_up keeps the name\", string.inspect(\"lucy\"), string.inspect(levelled.name)),
  ]
}",
    ),
  )
}

pub fn tip10_set_dedupe() -> Embedded {
  Embedded(
    solution: "import gleam/list
import gleam/set

pub fn dedupe(items: List(a)) -> List(a) {
  let #(kept, _) =
    list.fold(items, #([], set.new()), fn(acc, item) {
      let #(kept, seen) = acc
      case set.contains(seen, item) {
        True -> #(kept, seen)
        False -> #([item, ..kept], set.insert(seen, item))
      }
    })
  list.reverse(kept)
}",
    check: Check(
      signature: "pub fn dedupe(items: List(a)) -> List(a)",
      starter: "pub fn dedupe(items: List(a)) -> List(a) {
  todo
}",
      harness: "import gleam/string
import solution

const no_ints: List(Int) = []

pub fn run() -> List(#(String, String, String)) {
  [
    #(
      \"dedupe([1, 2, 1, 3, 2])\",
      string.inspect([1, 2, 3]),
      string.inspect(solution.dedupe([1, 2, 1, 3, 2])),
    ),
    #(
      \"dedupe([]) \",
      string.inspect(no_ints),
      string.inspect(solution.dedupe(no_ints)),
    ),
    #(
      \"dedupe([\\\"b\\\", \\\"a\\\", \\\"b\\\"])\",
      string.inspect([\"b\", \"a\"]),
      string.inspect(solution.dedupe([\"b\", \"a\", \"b\"])),
    ),
  ]
}",
    ),
  )
}
