//// GENERATED by `gleam run -m generate` in drills/ — do not edit.
//// Source of truth: drills/python/solutions/*.py and drills/python/harnesses/*.py.

import algodrill/problem.{Check}
import algodrill/problems/embedded.{type Embedded, Embedded}

pub fn nc01_contains_duplicate() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def containsDuplicate(nums):
    seen = set()
    for num in nums:
        if num in seen:
            return True
        seen.add(num)
    return False"),
      #("Solution 2 · Sorting", "def containsDuplicate(nums):
    # Duplicates are adjacent once sorted, so one pass over the sorted copy
    # answers it — O(n log n) time but no extra structure to hold every value.
    ordered = sorted(nums)
    for i in range(1, len(ordered)):
        if ordered[i] == ordered[i - 1]:
            return True
    return False"),
    ],
    check: Check(
      signature: "def containsDuplicate(nums):",
      starter: "def containsDuplicate(nums):
    pass",
      harness: "try:
    (containsDuplicate)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"containsDuplicate([1, 2, 3, 1])\", True, containsDuplicate([1, 2, 3, 1]))
__case__(\"containsDuplicate([1, 2, 3, 4])\", False, containsDuplicate([1, 2, 3, 4]))
__case__(\"containsDuplicate([])\", False, containsDuplicate([]))",
    ),
  )
}

pub fn nc02_valid_anagram() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def isAnagram(s, t):
    if len(s) != len(t):
        return False

    count = {}
    for char in s:
        count[char] = count.get(char, 0) + 1

    for char in t:
        if char not in count:
            return False
        count[char] -= 1
        if count[char] < 0:
            return False

    return True"),
      #("Solution 2 · Sorting", "def isAnagram(s, t):
    # Two words are anagrams exactly when their sorted letters match. One line,
    # O(n log n), and nothing to get wrong in the counting.
    return sorted(s) == sorted(t)"),
    ],
    check: Check(
      signature: "def isAnagram(s, t):",
      starter: "def isAnagram(s, t):
    pass",
      harness: "try:
    (isAnagram)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"isAnagram('anagram', 'nagaram')\", True, isAnagram(\"anagram\", \"nagaram\"))
__case__(\"isAnagram('rat', 'car')\", False, isAnagram(\"rat\", \"car\"))
__case__(\"isAnagram('', '')\", True, isAnagram(\"\", \"\"))
__case__(\"isAnagram('a', 'ab')\", False, isAnagram(\"a\", \"ab\"))",
    ),
  )
}

pub fn nc03_two_sum() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def twoSum(nums, target):
    seen = {}
    for i, num in enumerate(nums):
        complement = target - num
        if complement in seen:
            return [seen[complement], i]
        seen[num] = i
    return []"),
      #("Solution 2 · Brute force", "def twoSum(nums, target):
    for i in range(len(nums)):
        for j in range(i + 1, len(nums)):
            if nums[i] + nums[j] == target:
                return [i, j]
    return []"),
      #("Solution 3 · Sorted two pointer", "def twoSum(nums, target):
    # Sorting loses the original positions, so carry them along, then walk one
    # pointer in from each end: too small lifts the low end, too large drops
    # the high end.
    ordered = sorted((num, i) for i, num in enumerate(nums))
    left, right = 0, len(ordered) - 1

    while left < right:
        total = ordered[left][0] + ordered[right][0]
        if total == target:
            return sorted([ordered[left][1], ordered[right][1]])
        if total < target:
            left += 1
        else:
            right -= 1

    return []"),
    ],
    check: Check(
      signature: "def twoSum(nums, target):",
      starter: "def twoSum(nums, target):
    pass",
      harness: "try:
    (twoSum)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"twoSum([2, 7, 11, 15], 9)\", [0, 1], twoSum([2, 7, 11, 15], 9))
__case__(\"twoSum([3, 2, 4], 6)\", [1, 2], twoSum([3, 2, 4], 6))
__case__(\"twoSum([3, 3], 6)\", [0, 1], twoSum([3, 3], 6))
__case__(\"twoSum([1, 2], 7)\", [], twoSum([1, 2], 7))",
    ),
  )
}

pub fn nc04_group_anagrams() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "from collections import defaultdict

def groupAnagrams(strs):
    groups = defaultdict(list)
    for s in strs:
        key = [0] * 26
        for c in s:
            key[ord(c) - ord('a')] += 1
        groups[tuple(key)].append(s)
    return list(groups.values())"),
      #("Solution 2 · Sorted key", "from collections import defaultdict

def groupAnagrams(strs):
    # The sorted word itself is an anagram-invariant key. Shorter than tallying
    # letters, and it works for any alphabet rather than just a-z.
    groups = defaultdict(list)
    for s in strs:
        groups[\"\".join(sorted(s))].append(s)
    return list(groups.values())"),
    ],
    check: Check(
      signature: "def groupAnagrams(strs):",
      starter: "def groupAnagrams(strs):
    pass",
      harness: "try:
    (groupAnagrams)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__normalised__ = sorted(sorted(group) for group in groupAnagrams([\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"]))
__case__(\"groupAnagrams(['eat','tea','tan','ate','nat','bat'])\", [[\"ate\", \"eat\", \"tea\"], [\"bat\"], [\"nat\", \"tan\"]], __normalised__)
__case__(\"groupAnagrams([])\", [], sorted(groupAnagrams([])))
__case__(\"groupAnagrams(['a'])\", [[\"a\"]], sorted(groupAnagrams([\"a\"])))",
    ),
  )
}

pub fn nc05_top_k_frequent() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "from collections import Counter

def topKFrequent(nums, k):
    counts = Counter(nums)
    buckets = [[] for _ in range(len(nums) + 1)]
    for num, freq in counts.items():
        buckets[freq].append(num)

    result = []
    for freq in range(len(buckets) - 1, 0, -1):
        for num in buckets[freq]:
            result.append(num)
            if len(result) == k:
                return result
    return result"),
      #("Solution 2 · Heapq", "import heapq
from collections import Counter

def topKFrequent(nums, k):
    counts = Counter(nums)
    return heapq.nlargest(k, counts.keys(), key=counts.get)"),
      #("Solution 3 · Sorting", "def topKFrequent(nums, k):
    # Straight sort by frequency: O(n log n) rather than the bucket version's
    # O(n), but it is the version you can write without thinking.
    counts = {}
    for num in nums:
        counts[num] = counts.get(num, 0) + 1

    ordered = sorted(counts.items(), key=lambda entry: entry[1], reverse=True)
    return [num for num, _ in ordered[:k]]"),
    ],
    check: Check(
      signature: "def topKFrequent(nums, k):",
      starter: "def topKFrequent(nums, k):
    pass",
      harness: "try:
    (topKFrequent)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"topKFrequent([1, 1, 1, 2, 2, 3], 2)\", [1, 2], topKFrequent([1, 1, 1, 2, 2, 3], 2))
__case__(\"topKFrequent([1], 1)\", [1], topKFrequent([1], 1))
__case__(\"topKFrequent([5, 5, 4, 4, 4, 3], 1)\", [4], topKFrequent([5, 5, 4, 4, 4, 3], 1))",
    ),
  )
}

pub fn nc06_product_except_self() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def productExceptSelf(nums):
    n = len(nums)
    result = [1] * n

    prefix = 1
    for i in range(n):
        result[i] = prefix
        prefix *= nums[i]

    suffix = 1
    for i in range(n - 1, -1, -1):
        result[i] *= suffix
        suffix *= nums[i]

    return result"),
      #("Solution 2 · Brute force", "def productExceptSelf(nums):
    # The obvious O(n^2) reading of the problem: for each slot, multiply
    # everything that is not in it. Worth knowing as the thing prefix/suffix
    # beats.
    result = []
    for i in range(len(nums)):
        product = 1
        for j, num in enumerate(nums):
            if i != j:
                product *= num
        result.append(product)
    return result"),
    ],
    check: Check(
      signature: "def productExceptSelf(nums):",
      starter: "def productExceptSelf(nums):
    pass",
      harness: "try:
    (productExceptSelf)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"productExceptSelf([1, 2, 3, 4])\", [24, 12, 8, 6], productExceptSelf([1, 2, 3, 4]))
__case__(\"productExceptSelf([-1, 1, 0, -3, 3])\", [0, 0, 9, 0, 0], productExceptSelf([-1, 1, 0, -3, 3]))
__case__(\"productExceptSelf([2, 3])\", [3, 2], productExceptSelf([2, 3]))",
    ),
  )
}

pub fn nc07_longest_consecutive() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def longestConsecutive(nums):
    num_set = set(nums)
    longest = 0

    for num in num_set:
        # only start counting from the beginning of a run
        if num - 1 not in num_set:
            length = 1
            while num + length in num_set:
                length += 1
            longest = max(longest, length)

    return longest"),
      #("Solution 2 · Sorting", "def longestConsecutive(nums):
    # No set: sort, then walk once counting runs. O(n log n) rather than O(n),
    # but it needs no extra structure and the run logic reads straight through.
    if not nums:
        return 0

    ordered = sorted(nums)
    longest = 1
    run = 1

    for i in range(1, len(ordered)):
        step = ordered[i] - ordered[i - 1]
        if step == 0:
            continue  # duplicates neither extend nor break a run
        if step == 1:
            run += 1
            longest = max(longest, run)
        else:
            run = 1

    return longest"),
    ],
    check: Check(
      signature: "def longestConsecutive(nums):",
      starter: "def longestConsecutive(nums):
    pass",
      harness: "try:
    (longestConsecutive)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"longestConsecutive([100, 4, 200, 1, 3, 2])\", 4, longestConsecutive([100, 4, 200, 1, 3, 2]))
__case__(\"longestConsecutive([0, 3, 7, 2, 5, 8, 4, 6, 0, 1])\", 9, longestConsecutive([0, 3, 7, 2, 5, 8, 4, 6, 0, 1]))
__case__(\"longestConsecutive([])\", 0, longestConsecutive([]))",
    ),
  )
}

pub fn nc08_valid_palindrome() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def isPalindrome(s):
    left, right = 0, len(s) - 1

    while left < right:
        while left < right and not s[left].isalnum():
            left += 1
        while left < right and not s[right].isalnum():
            right -= 1

        if s[left].lower() != s[right].lower():
            return False

        left += 1
        right -= 1

    return True"),
      #("Solution 2 · Cleaned reverse", "def isPalindrome(s):
    cleaned = [c.lower() for c in s if c.isalnum()]
    return cleaned == cleaned[::-1]"),
    ],
    check: Check(
      signature: "def isPalindrome(s):",
      starter: "def isPalindrome(s):
    pass",
      harness: "try:
    (isPalindrome)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"isPalindrome('A man, a plan, a canal: Panama')\", True, isPalindrome(\"A man, a plan, a canal: Panama\"))
__case__(\"isPalindrome('race a car')\", False, isPalindrome(\"race a car\"))
__case__(\"isPalindrome(' ')\", True, isPalindrome(\" \"))
__case__(\"isPalindrome('0P')\", False, isPalindrome(\"0P\"))",
    ),
  )
}

pub fn nc09_two_sum_sorted() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def twoSum(numbers, target):
    left, right = 0, len(numbers) - 1

    while left < right:
        total = numbers[left] + numbers[right]
        if total == target:
            return [left + 1, right + 1]
        elif total < target:
            left += 1
        else:
            right -= 1

    return []"),
      #("Solution 2 · Binary search", "def twoSum(numbers, target):
    # Instead of converging two pointers, fix each number and binary search the
    # tail for its complement. O(n log n), and it reuses a search you already
    # know rather than a second pointer discipline.
    for i, number in enumerate(numbers):
        wanted = target - number
        lo, hi = i + 1, len(numbers) - 1
        while lo <= hi:
            mid = lo + (hi - lo) // 2
            if numbers[mid] == wanted:
                return [i + 1, mid + 1]
            if numbers[mid] < wanted:
                lo = mid + 1
            else:
                hi = mid - 1
    return []"),
    ],
    check: Check(
      signature: "def twoSum(numbers, target):",
      starter: "def twoSum(numbers, target):
    pass",
      harness: "try:
    (twoSum)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"twoSum([2, 7, 11, 15], 9)\", [1, 2], twoSum([2, 7, 11, 15], 9))
__case__(\"twoSum([2, 3, 4], 6)\", [1, 3], twoSum([2, 3, 4], 6))
__case__(\"twoSum([-1, 0], -1)\", [1, 2], twoSum([-1, 0], -1))
__case__(\"twoSum([1, 2, 3], 100)\", [], twoSum([1, 2, 3], 100))",
    ),
  )
}

pub fn nc10_three_sum() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def threeSum(nums):
    nums.sort()
    result = []

    for i, a in enumerate(nums):
        if i > 0 and a == nums[i - 1]:
            continue

        left, right = i + 1, len(nums) - 1
        while left < right:
            total = a + nums[left] + nums[right]
            if total < 0:
                left += 1
            elif total > 0:
                right -= 1
            else:
                result.append([a, nums[left], nums[right]])
                left += 1
                while left < right and nums[left] == nums[left - 1]:
                    left += 1

    return result"),
      #("Solution 2 · Brute force", "def threeSum(nums):
    # Every triple, checked. Sorting first means each triple comes out in
    # ascending order, so duplicates are literal list equality.
    ordered = sorted(nums)
    result = []

    for i in range(len(ordered)):
        for j in range(i + 1, len(ordered)):
            for k in range(j + 1, len(ordered)):
                triple = [ordered[i], ordered[j], ordered[k]]
                if sum(triple) == 0 and triple not in result:
                    result.append(triple)

    return result"),
    ],
    check: Check(
      signature: "def threeSum(nums):",
      starter: "def threeSum(nums):
    pass",
      harness: "try:
    (threeSum)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"threeSum([-1, 0, 1, 2, -1, -4])\", [[-1, -1, 2], [-1, 0, 1]], threeSum([-1, 0, 1, 2, -1, -4]))
__case__(\"threeSum([0, 1, 1])\", [], threeSum([0, 1, 1]))
__case__(\"threeSum([0, 0, 0])\", [[0, 0, 0]], threeSum([0, 0, 0]))",
    ),
  )
}

pub fn nc11_container_water() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def maxArea(height):
    left, right = 0, len(height) - 1
    best = 0

    while left < right:
        area = (right - left) * min(height[left], height[right])
        best = max(best, area)

        if height[left] < height[right]:
            left += 1
        else:
            right -= 1

    return best"),
      #("Solution 2 · Brute force", "def maxArea(height):
    # Every pair of lines, measured. O(n^2), but it makes what the two-pointer
    # sweep is maximising explicit: shorter line times distance.
    best = 0
    for left in range(len(height)):
        for right in range(left + 1, len(height)):
            best = max(best, (right - left) * min(height[left], height[right]))
    return best"),
    ],
    check: Check(
      signature: "def maxArea(height):",
      starter: "def maxArea(height):
    pass",
      harness: "try:
    (maxArea)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"maxArea([1, 8, 6, 2, 5, 4, 8, 3, 7])\", 49, maxArea([1, 8, 6, 2, 5, 4, 8, 3, 7]))
__case__(\"maxArea([1, 1])\", 1, maxArea([1, 1]))",
    ),
  )
}

pub fn nc12_best_time_stock() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def maxProfit(prices):
    lowest = float('inf')
    profit = 0

    for price in prices:
        lowest = min(lowest, price)
        profit = max(profit, price - lowest)

    return profit"),
      #("Solution 2 · Brute force", "def maxProfit(prices):
    profit = 0
    for buy in range(len(prices)):
        for sell in range(buy + 1, len(prices)):
            profit = max(profit, prices[sell] - prices[buy])
    return profit"),
    ],
    check: Check(
      signature: "def maxProfit(prices):",
      starter: "def maxProfit(prices):
    pass",
      harness: "try:
    (maxProfit)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"maxProfit([7, 1, 5, 3, 6, 4])\", 5, maxProfit([7, 1, 5, 3, 6, 4]))
__case__(\"maxProfit([7, 6, 4, 3, 1])\", 0, maxProfit([7, 6, 4, 3, 1]))
__case__(\"maxProfit([])\", 0, maxProfit([]))",
    ),
  )
}

pub fn nc13_longest_substring() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def lengthOfLongestSubstring(s):
    window = set()
    left = 0
    longest = 0

    for right in range(len(s)):
        while s[right] in window:
            window.remove(s[left])
            left += 1
        window.add(s[right])
        longest = max(longest, right - left + 1)

    return longest"),
      #("Solution 2 · Index scan", "def lengthOfLongestSubstring(s):
    # No set, no dict: ask the string itself whether this character already
    # appeared inside the current window, and if so start just past it.
    longest = 0
    start = 0

    for right, char in enumerate(s):
        found = s.find(char, start, right)
        if found != -1:
            start = found + 1
        longest = max(longest, right - start + 1)

    return longest"),
    ],
    check: Check(
      signature: "def lengthOfLongestSubstring(s):",
      starter: "def lengthOfLongestSubstring(s):
    pass",
      harness: "try:
    (lengthOfLongestSubstring)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"lengthOfLongestSubstring('abcabcbb')\", 3, lengthOfLongestSubstring(\"abcabcbb\"))
__case__(\"lengthOfLongestSubstring('bbbbb')\", 1, lengthOfLongestSubstring(\"bbbbb\"))
__case__(\"lengthOfLongestSubstring('pwwkew')\", 3, lengthOfLongestSubstring(\"pwwkew\"))
__case__(\"lengthOfLongestSubstring('')\", 0, lengthOfLongestSubstring(\"\"))",
    ),
  )
}

pub fn nc14_character_replacement() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def characterReplacement(s, k):
    count = {}
    left = 0
    max_count = 0
    longest = 0

    for right in range(len(s)):
        count[s[right]] = count.get(s[right], 0) + 1
        max_count = max(max_count, count[s[right]])

        while (right - left + 1) - max_count > k:
            count[s[left]] -= 1
            left += 1

        longest = max(longest, right - left + 1)

    return longest"),
      #("Solution 2 · Per character", "ALPHABET = \"ABCDEFGHIJKLMNOPQRSTUVWXYZ\"

def characterReplacement(s, k):
    # One sweep per letter, asking a much simpler question each time: how long
    # a window can I hold if *this* is the letter I keep? No running frequency
    # map and no max-count bookkeeping — 26 easy passes instead of one subtle
    # one.
    longest = 0

    for target in ALPHABET:
        left = 0
        others = 0
        for right, char in enumerate(s):
            if char != target:
                others += 1
            while others > k:
                if s[left] != target:
                    others -= 1
                left += 1
            longest = max(longest, right - left + 1)

    return longest"),
    ],
    check: Check(
      signature: "def characterReplacement(s, k):",
      starter: "def characterReplacement(s, k):
    pass",
      harness: "try:
    (characterReplacement)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"characterReplacement('ABAB', 2)\", 4, characterReplacement(\"ABAB\", 2))
__case__(\"characterReplacement('AABABBA', 1)\", 4, characterReplacement(\"AABABBA\", 1))
__case__(\"characterReplacement('AAAA', 0)\", 4, characterReplacement(\"AAAA\", 0))",
    ),
  )
}

pub fn nc15_permutation_in_string() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "from collections import Counter

def checkInclusion(s1, s2):
    if len(s1) > len(s2):
        return False

    need = Counter(s1)
    window = Counter(s2[:len(s1)])

    if window == need:
        return True

    for i in range(len(s1), len(s2)):
        window[s2[i]] += 1
        left_char = s2[i - len(s1)]
        window[left_char] -= 1
        if window[left_char] == 0:
            del window[left_char]
        if window == need:
            return True

    return False"),
      #("Solution 2 · Sorted windows", "def checkInclusion(s1, s2):
    # Every window of the right length, sorted and compared. Slower than
    # sliding counts, but there is no incremental state to get wrong: the whole
    # method is \"is this window an anagram?\".
    if len(s1) > len(s2):
        return False

    needle = sorted(s1)
    size = len(s1)

    for start in range(len(s2) - size + 1):
        if sorted(s2[start:start + size]) == needle:
            return True

    return False"),
    ],
    check: Check(
      signature: "def checkInclusion(s1, s2):",
      starter: "def checkInclusion(s1, s2):
    pass",
      harness: "try:
    (checkInclusion)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"checkInclusion('ab', 'eidbaooo')\", True, checkInclusion(\"ab\", \"eidbaooo\"))
__case__(\"checkInclusion('ab', 'eidboaoo')\", False, checkInclusion(\"ab\", \"eidboaoo\"))
__case__(\"checkInclusion('adc', 'dcda')\", True, checkInclusion(\"adc\", \"dcda\"))",
    ),
  )
}

pub fn nc16_valid_parentheses() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def isValid(s):
    pairs = {')': '(', ']': '[', '}': '{'}
    stack = []

    for char in s:
        if char in pairs:
            if not stack or stack.pop() != pairs[char]:
                return False
        else:
            stack.append(char)

    return not stack"),
      #("Solution 2 · Reduction", "def isValid(s):
    # No stack: strip every matched pair, over and over, until nothing more can
    # go. Whatever survives is unmatched. This is also why \"([)]\" fails —
    # neither pair is ever adjacent.
    previous = None
    while previous != s:
        previous = s
        s = s.replace(\"()\", \"\").replace(\"[]\", \"\").replace(\"{}\", \"\")
    return s == \"\""),
    ],
    check: Check(
      signature: "def isValid(s):",
      starter: "def isValid(s):
    pass",
      harness: "try:
    (isValid)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"isValid('()[]{}')\", True, isValid(\"()[]{}\"))
__case__(\"isValid('(]')\", False, isValid(\"(]\"))
__case__(\"isValid('([)]')\", False, isValid(\"([)]\"))
__case__(\"isValid('{[]}')\", True, isValid(\"{[]}\"))
__case__(\"isValid('(')\", False, isValid(\"(\"))",
    ),
  )
}

pub fn nc17_min_stack() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "class MinStack:
    def __init__(self):
        self.stack = []
        self.mins = []

    def push(self, val):
        self.stack.append(val)
        current_min = val if not self.mins else min(val, self.mins[-1])
        self.mins.append(current_min)

    def pop(self):
        self.stack.pop()
        self.mins.pop()

    def top(self):
        return self.stack[-1]

    def getMin(self):
        return self.mins[-1]"),
      #("Solution 2 · Pair stack", "class MinStack:
    # Each entry carries the minimum of everything at or below it, so getMin is
    # a peek. One list instead of two, at the cost of storing a second int per
    # value.

    def __init__(self):
        self.entries = []

    def push(self, val):
        current_min = val if not self.entries else min(val, self.entries[-1][1])
        self.entries.append((val, current_min))

    def pop(self):
        self.entries.pop()

    def top(self):
        return self.entries[-1][0]

    def getMin(self):
        return self.entries[-1][1]"),
    ],
    check: Check(
      signature: "class MinStack:
    def __init__(self):
    def push(self, val):
    def pop(self):
    def top(self):
    def getMin(self):",
      starter: "class MinStack:
    def __init__(self):
        pass
    def push(self, val):
        pass
    def pop(self):
        pass
    def top(self):
        pass
    def getMin(self):
        pass",
      harness: "try:
    (MinStack)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__stack__ = MinStack()
__stack__.push(-2)
__stack__.push(0)
__stack__.push(-3)
__case__(\"getMin() after push -2, 0, -3\", -3, __stack__.getMin())
__stack__.pop()
__case__(\"top() after pop()\", 0, __stack__.top())
__case__(\"getMin() after pop()\", -2, __stack__.getMin())",
    ),
  )
}

pub fn nc18_daily_temperatures() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def dailyTemperatures(temperatures):
    result = [0] * len(temperatures)
    stack = []  # (index, temp) — monotonically decreasing

    for i, temp in enumerate(temperatures):
        while stack and temp > stack[-1][1]:
            prev_index, _ = stack.pop()
            result[prev_index] = i - prev_index
        stack.append((i, temp))

    return result"),
      #("Solution 2 · Brute force", "def dailyTemperatures(temperatures):
    # For each day, scan forward until it gets warmer. O(n^2), and the direct
    # reading of the question — the monotonic stack exists only to avoid
    # rescanning the same cold stretch once per day.
    result = []
    for i, temp in enumerate(temperatures):
        days = 0
        for j in range(i + 1, len(temperatures)):
            if temperatures[j] > temp:
                days = j - i
                break
        result.append(days)
    return result"),
    ],
    check: Check(
      signature: "def dailyTemperatures(temperatures):",
      starter: "def dailyTemperatures(temperatures):
    pass",
      harness: "try:
    (dailyTemperatures)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"dailyTemperatures([73, 74, 75, 71, 69, 72, 76, 73])\", [1, 1, 4, 2, 1, 1, 0, 0], dailyTemperatures([73, 74, 75, 71, 69, 72, 76, 73]))
__case__(\"dailyTemperatures([30, 40, 50, 60])\", [1, 1, 1, 0], dailyTemperatures([30, 40, 50, 60]))
__case__(\"dailyTemperatures([30, 30, 30])\", [0, 0, 0], dailyTemperatures([30, 30, 30]))",
    ),
  )
}

pub fn nc19_binary_search() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def search(nums, target):
    left, right = 0, len(nums) - 1

    while left <= right:
        mid = left + (right - left) // 2
        if nums[mid] == target:
            return mid
        elif nums[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1"),
      #("Solution 2 · Recursive", "def search(nums, target):
    # The same halving, written as recursion. The bounds are arguments rather
    # than mutated locals, which makes each step's invariant easier to see.
    return halve(nums, target, 0, len(nums) - 1)

def halve(nums, target, lo, hi):
    if lo > hi:
        return -1

    mid = lo + (hi - lo) // 2
    if nums[mid] == target:
        return mid
    if nums[mid] < target:
        return halve(nums, target, mid + 1, hi)
    return halve(nums, target, lo, mid - 1)"),
    ],
    check: Check(
      signature: "def search(nums, target):",
      starter: "def search(nums, target):
    pass",
      harness: "try:
    (search)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"search([-1, 0, 3, 5, 9, 12], 9)\", 4, search([-1, 0, 3, 5, 9, 12], 9))
__case__(\"search([-1, 0, 3, 5, 9, 12], 2)\", -1, search([-1, 0, 3, 5, 9, 12], 2))
__case__(\"search([5], 5)\", 0, search([5], 5))
__case__(\"search([], 1)\", -1, search([], 1))",
    ),
  )
}

pub fn nc20_find_min_rotated() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def findMin(nums):
    left, right = 0, len(nums) - 1

    while left < right:
        mid = left + (right - left) // 2
        if nums[mid] > nums[right]:
            left = mid + 1
        else:
            right = mid

    return nums[left]"),
      #("Solution 2 · Linear scan", "def findMin(nums):
    # O(n) rather than O(log n), but it makes the shape of the problem obvious:
    # a rotated sorted array drops in value exactly once, and that drop is the
    # minimum. No drop means it was never rotated, so the head wins.
    for i in range(1, len(nums)):
        if nums[i] < nums[i - 1]:
            return nums[i]
    return nums[0]"),
    ],
    check: Check(
      signature: "def findMin(nums):",
      starter: "def findMin(nums):
    pass",
      harness: "try:
    (findMin)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"findMin([3, 4, 5, 1, 2])\", 1, findMin([3, 4, 5, 1, 2]))
__case__(\"findMin([4, 5, 6, 7, 0, 1, 2])\", 0, findMin([4, 5, 6, 7, 0, 1, 2]))
__case__(\"findMin([11, 13, 15, 17])\", 11, findMin([11, 13, 15, 17]))
__case__(\"findMin([2, 1])\", 1, findMin([2, 1]))",
    ),
  )
}

pub fn nc21_search_rotated() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def search(nums, target):
    left, right = 0, len(nums) - 1

    while left <= right:
        mid = left + (right - left) // 2
        if nums[mid] == target:
            return mid

        if nums[left] <= nums[mid]:  # left half sorted
            if nums[left] <= target < nums[mid]:
                right = mid - 1
            else:
                left = mid + 1
        else:  # right half sorted
            if nums[mid] < target <= nums[right]:
                left = mid + 1
            else:
                right = mid - 1

    return -1"),
      #("Solution 2 · Find pivot", "def search(nums, target):
    # Two plain steps instead of one clever one: find where the rotation
    # wrapped, which splits the input into two ordinary sorted arrays, then
    # binary search each. Nothing has to reason mid-search about which half is
    # sorted.
    pivot = rotationPoint(nums)
    found = binarySearch(nums, target, 0, pivot - 1)
    if found != -1:
        return found
    return binarySearch(nums, target, pivot, len(nums) - 1)

def rotationPoint(nums):
    for i in range(1, len(nums)):
        if nums[i] < nums[i - 1]:
            return i
    return 0

def binarySearch(nums, target, lo, hi):
    while lo <= hi:
        mid = lo + (hi - lo) // 2
        if nums[mid] == target:
            return mid
        if nums[mid] < target:
            lo = mid + 1
        else:
            hi = mid - 1
    return -1"),
    ],
    check: Check(
      signature: "def search(nums, target):",
      starter: "def search(nums, target):
    pass",
      harness: "try:
    (search)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"search([4, 5, 6, 7, 0, 1, 2], 0)\", 4, search([4, 5, 6, 7, 0, 1, 2], 0))
__case__(\"search([4, 5, 6, 7, 0, 1, 2], 3)\", -1, search([4, 5, 6, 7, 0, 1, 2], 3))
__case__(\"search([1], 1)\", 0, search([1], 1))
__case__(\"search([4, 5, 6, 7, 0, 1, 2], 6)\", 2, search([4, 5, 6, 7, 0, 1, 2], 6))",
    ),
  )
}

pub fn tip01_counter() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "from collections import Counter

def topTwo(nums):
    return Counter(nums).most_common(2)

def countOf(nums, value):
    return Counter(nums)[value]"),
      #("Solution 2 · Plain dict", "def topTwo(nums):
    # What Counter does underneath: a dict of counts, then a sort. Worth writing
    # once so most_common stops being a black box.
    counts = {}
    for num in nums:
        counts[num] = counts.get(num, 0) + 1
    ordered = sorted(counts.items(), key=lambda entry: entry[1], reverse=True)
    return ordered[:2]

def countOf(nums, value):
    return sum(1 for num in nums if num == value)"),
    ],
    check: Check(
      signature: "def topTwo(nums):

def countOf(nums, value):",
      starter: "def topTwo(nums):
    pass

def countOf(nums, value):
    pass",
      harness: "try:
    (topTwo, countOf)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"topTwo([1, 1, 1, 2, 2, 3])\", [(1, 3), (2, 2)], topTwo([1, 1, 1, 2, 2, 3]))
__case__(\"countOf([1, 1, 2], 1)\", 2, countOf([1, 1, 2], 1))
__case__(\"countOf([1, 1, 2], 9)\", 0, countOf([1, 1, 2], 9))",
    ),
  )
}

pub fn tip02_defaultdict() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "from collections import defaultdict

def groupByLength(words):
    groups = defaultdict(list)
    for word in words:
        groups[len(word)].append(word)
    return dict(groups)"),
      #("Solution 2 · Setdefault", "def groupByLength(words):
    # setdefault does the same job as defaultdict without changing the type of
    # the dictionary — handy when the result is returned or serialised, since
    # there is no default factory left attached to it.
    groups = {}
    for word in words:
        groups.setdefault(len(word), []).append(word)
    return groups"),
    ],
    check: Check(
      signature: "def groupByLength(words):",
      starter: "def groupByLength(words):
    pass",
      harness: "try:
    (groupByLength)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"groupByLength(['a', 'bc', 'de', 'f'])\", {1: [\"a\", \"f\"], 2: [\"bc\", \"de\"]}, groupByLength([\"a\", \"bc\", \"de\", \"f\"]))
__case__(\"groupByLength([])\", {}, groupByLength([]))",
    ),
  )
}

pub fn tip03_deque() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "from collections import deque

def bfsOrder(graph, start):
    queue = deque([start])
    seen = {start}
    order = []
    while queue:
        node = queue.popleft()
        order.append(node)
        for neighbor in graph.get(node, []):
            if neighbor not in seen:
                seen.add(neighbor)
                queue.append(neighbor)
    return order"),
      #("Solution 2 · List queue", "def bfsOrder(graph, start):
    # A list plus a read cursor. The cursor is the point: list.pop(0) is O(n),
    # so a plain list only stays a good queue if you never shift it.
    queue = [start]
    head = 0
    seen = {start}
    order = []

    while head < len(queue):
        node = queue[head]
        head += 1
        order.append(node)
        for neighbor in graph.get(node, []):
            if neighbor not in seen:
                seen.add(neighbor)
                queue.append(neighbor)

    return order"),
    ],
    check: Check(
      signature: "def bfsOrder(graph, start):",
      starter: "def bfsOrder(graph, start):
    pass",
      harness: "try:
    (bfsOrder)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__graph__ = {\"a\": [\"b\", \"c\"], \"b\": [\"d\"], \"c\": [\"d\"], \"d\": []}
__case__(\"bfsOrder(graph, 'a')\", [\"a\", \"b\", \"c\", \"d\"], bfsOrder(__graph__, \"a\"))
__case__(\"bfsOrder({'x': []}, 'x')\", [\"x\"], bfsOrder({\"x\": []}, \"x\"))",
    ),
  )
}

pub fn tip04_heapq() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "import heapq

def kSmallest(nums, k):
    heap = list(nums)
    heapq.heapify(heap)
    return [heapq.heappop(heap) for _ in range(min(k, len(heap)))]

def kLargest(nums, k):
    heap = [-n for n in nums]
    heapq.heapify(heap)
    return [-heapq.heappop(heap) for _ in range(min(k, len(heap)))]"),
      #("Solution 2 · Sorting", "def kSmallest(nums, k):
    # Sorting is O(n log n) against the heap's O(n + k log n). For small k the
    # heap wins; for k near n they are the same, and this is far shorter.
    return sorted(nums)[:k]

def kLargest(nums, k):
    return sorted(nums, reverse=True)[:k]"),
    ],
    check: Check(
      signature: "def kSmallest(nums, k):

def kLargest(nums, k):",
      starter: "def kSmallest(nums, k):
    pass

def kLargest(nums, k):
    pass",
      harness: "try:
    (kSmallest, kLargest)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"kSmallest([5, 1, 4, 2], 2)\", [1, 2], kSmallest([5, 1, 4, 2], 2))
__case__(\"kLargest([5, 1, 4, 2], 2)\", [5, 4], kLargest([5, 1, 4, 2], 2))
__case__(\"kSmallest([3], 5)\", [3], kSmallest([3], 5))",
    ),
  )
}

pub fn tip05_enumerate_zip() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def firstIndexOf(nums, target):
    for i, value in enumerate(nums):
        if value == target:
            return i
    return -1

def dotProduct(a, b):
    return sum(x * y for x, y in zip(a, b))"),
      #("Solution 2 · Index loop", "def firstIndexOf(nums, target):
    # Indexing by hand. It works, and it is exactly what enumerate and zip save
    # you from: the off-by-one risk and the second subscript in dotProduct.
    for i in range(len(nums)):
        if nums[i] == target:
            return i
    return -1

def dotProduct(a, b):
    total = 0
    for i in range(min(len(a), len(b))):
        total += a[i] * b[i]
    return total"),
    ],
    check: Check(
      signature: "def firstIndexOf(nums, target):

def dotProduct(a, b):",
      starter: "def firstIndexOf(nums, target):
    pass

def dotProduct(a, b):
    pass",
      harness: "try:
    (firstIndexOf, dotProduct)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"firstIndexOf([9, 8, 7], 8)\", 1, firstIndexOf([9, 8, 7], 8))
__case__(\"firstIndexOf([9, 8, 7], 5)\", -1, firstIndexOf([9, 8, 7], 5))
__case__(\"dotProduct([1, 2, 3], [4, 5, 6])\", 32, dotProduct([1, 2, 3], [4, 5, 6]))",
    ),
  )
}

pub fn tip06_slicing() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def reversedString(s):
    return s[::-1]

def everySecond(s):
    return s[::2]

def lastN(s, n):
    return s[-n:] if n > 0 else \"\"

def trimEnds(s):
    return s[1:-1]"),
      #("Solution 2 · Explicit loops", "def reversedString(s):
    # Every slice spelled out as a loop. The slices are better in real code;
    # writing them this way once makes the step and the negative bounds obvious.
    out = \"\"
    for char in s:
        out = char + out
    return out

def everySecond(s):
    out = \"\"
    for i in range(0, len(s), 2):
        out += s[i]
    return out

def lastN(s, n):
    if n <= 0:
        return \"\"
    return \"\".join(s[i] for i in range(max(len(s) - n, 0), len(s)))

def trimEnds(s):
    return \"\".join(s[i] for i in range(1, len(s) - 1))"),
    ],
    check: Check(
      signature: "def reversedString(s):

def everySecond(s):

def lastN(s, n):

def trimEnds(s):",
      starter: "def reversedString(s):
    pass

def everySecond(s):
    pass

def lastN(s, n):
    pass

def trimEnds(s):
    pass",
      harness: "try:
    (reversedString, everySecond, lastN, trimEnds)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"reversedString('gleam')\", \"maelg\", reversedString(\"gleam\"))
__case__(\"everySecond('abcdef')\", \"ace\", everySecond(\"abcdef\"))
__case__(\"lastN('drill', 3)\", \"ill\", lastN(\"drill\", 3))
__case__(\"trimEnds('~mid~')\", \"mid\", trimEnds(\"~mid~\"))",
    ),
  )
}

pub fn tip07_sort_key() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def sortByLength(words):
    return sorted(words, key=len)

def sortPairs(pairs):
    return sorted(pairs, key=lambda p: (p[0], -p[1]))"),
      #("Solution 2 · Decorate sort undecorate", "def sortByLength(words):
    # Decorate, sort, undecorate: attach the sort key to each item, sort the
    # pairs, then strip it. `key=` is this pattern built into sorted().
    decorated = [(len(word), word) for word in words]
    decorated.sort(key=lambda pair: pair[0])
    return [word for _, word in decorated]

def sortPairs(pairs):
    decorated = [((pair[0], -pair[1]), pair) for pair in pairs]
    decorated.sort(key=lambda entry: entry[0])
    return [pair for _, pair in decorated]"),
    ],
    check: Check(
      signature: "def sortByLength(words):

def sortPairs(pairs):",
      starter: "def sortByLength(words):
    pass

def sortPairs(pairs):
    pass",
      harness: "try:
    (sortByLength, sortPairs)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"sortByLength(['ccc', 'a', 'bb'])\", [\"a\", \"bb\", \"ccc\"], sortByLength([\"ccc\", \"a\", \"bb\"]))
__case__(\"sortPairs([('b', 1), ('a', 1), ('a', 9)])\", [(\"a\", 9), (\"a\", 1), (\"b\", 1)], sortPairs([(\"b\", 1), (\"a\", 1), (\"a\", 9)]))",
    ),
  )
}

pub fn tip08_join() -> Embedded {
  Embedded(
    solutions: [
      #("Solution 1", "def joinUpper(chars):
    parts = []
    for c in chars:
        parts.append(c.upper())
    return \"\".join(parts)"),
      #("Solution 2 · Concatenation", "def joinUpper(chars):
    # The version join exists to replace. Each `+=` builds a whole new string,
    # so this is quadratic in the output length — fine for two characters,
    # painful for a megabyte.
    out = \"\"
    for c in chars:
        out += c.upper()
    return out"),
    ],
    check: Check(
      signature: "def joinUpper(chars):",
      starter: "def joinUpper(chars):
    pass",
      harness: "try:
    (joinUpper)
except NameError:
    raise Exception(\"__signature_mismatch__\")

__results__ = []
def __case__(label, expected, actual):
    __results__.append([label, repr(expected), repr(actual)])

__case__(\"joinUpper(['g', 'o'])\", \"GO\", joinUpper([\"g\", \"o\"]))
__case__(\"joinUpper([])\", \"\", joinUpper([]))",
    ),
  )
}
