// GENERATED by `gleam run -m generate` in drills/ - do not edit.
// Runs every TypeScript solution variant against its harness:
//   bun verify_all.ts     (from drills/ts)
import * as v0 from "./.verify/nc01_contains_duplicate/harness";
import * as v1 from "./.verify/nc01_contains_duplicate__sorting/harness";
import * as v2 from "./.verify/nc02_valid_anagram/harness";
import * as v3 from "./.verify/nc02_valid_anagram__sorting/harness";
import * as v4 from "./.verify/nc03_two_sum/harness";
import * as v5 from "./.verify/nc03_two_sum__sorted_two_pointer/harness";
import * as v6 from "./.verify/nc04_group_anagrams/harness";
import * as v7 from "./.verify/nc04_group_anagrams__sorted_key/harness";
import * as v8 from "./.verify/nc05_top_k_frequent/harness";
import * as v9 from "./.verify/nc05_top_k_frequent__sorting/harness";
import * as v10 from "./.verify/nc06_product_except_self/harness";
import * as v11 from "./.verify/nc06_product_except_self__brute_force/harness";
import * as v12 from "./.verify/nc07_longest_consecutive/harness";
import * as v13 from "./.verify/nc07_longest_consecutive__sorting/harness";
import * as v14 from "./.verify/nc08_valid_palindrome/harness";
import * as v15 from "./.verify/nc08_valid_palindrome__cleaned_reverse/harness";
import * as v16 from "./.verify/nc09_two_sum_sorted/harness";
import * as v17 from "./.verify/nc09_two_sum_sorted__binary_search/harness";
import * as v18 from "./.verify/nc10_three_sum/harness";
import * as v19 from "./.verify/nc10_three_sum__brute_force/harness";
import * as v20 from "./.verify/nc11_container_water/harness";
import * as v21 from "./.verify/nc11_container_water__brute_force/harness";
import * as v22 from "./.verify/nc12_best_time_stock/harness";
import * as v23 from "./.verify/nc12_best_time_stock__brute_force/harness";
import * as v24 from "./.verify/nc13_longest_substring/harness";
import * as v25 from "./.verify/nc13_longest_substring__index_scan/harness";
import * as v26 from "./.verify/nc14_character_replacement/harness";
import * as v27 from "./.verify/nc14_character_replacement__per_character/harness";
import * as v28 from "./.verify/nc15_permutation_in_string/harness";
import * as v29 from "./.verify/nc15_permutation_in_string__sorted_windows/harness";
import * as v30 from "./.verify/nc16_valid_parentheses/harness";
import * as v31 from "./.verify/nc16_valid_parentheses__reduction/harness";
import * as v32 from "./.verify/nc17_min_stack/harness";
import * as v33 from "./.verify/nc17_min_stack__pair_stack/harness";
import * as v34 from "./.verify/nc18_daily_temperatures/harness";
import * as v35 from "./.verify/nc18_daily_temperatures__brute_force/harness";
import * as v36 from "./.verify/nc19_binary_search/harness";
import * as v37 from "./.verify/nc19_binary_search__recursive/harness";
import * as v38 from "./.verify/nc20_find_min_rotated/harness";
import * as v39 from "./.verify/nc20_find_min_rotated__linear_scan/harness";
import * as v40 from "./.verify/nc21_search_rotated/harness";
import * as v41 from "./.verify/nc21_search_rotated__find_pivot/harness";
import * as v42 from "./.verify/nc22_encode_decode/harness";
import * as v43 from "./.verify/nc22_encode_decode__escaping/harness";
import * as v44 from "./.verify/nc23_valid_sudoku/harness";
import * as v45 from "./.verify/nc23_valid_sudoku__by_unit/harness";
import * as v46 from "./.verify/nc24_trapping_rain_water/harness";
import * as v47 from "./.verify/nc24_trapping_rain_water__prefix_maxima/harness";
import * as v48 from "./.verify/nc25_min_window_substring/harness";
import * as v49 from "./.verify/nc25_min_window_substring__filtered_positions/harness";
import * as v50 from "./.verify/nc26_sliding_window_maximum/harness";
import * as v51 from "./.verify/nc26_sliding_window_maximum__brute_force/harness";
import * as v52 from "./.verify/nc26_sliding_window_maximum__monotonic_deque/harness";
import * as v53 from "./.verify/nc27_eval_rpn/harness";
import * as v54 from "./.verify/nc27_eval_rpn__recursive/harness";
import * as v55 from "./.verify/nc28_generate_parentheses/harness";
import * as v56 from "./.verify/nc28_generate_parentheses__by_composition/harness";
import * as v57 from "./.verify/nc29_car_fleet/harness";
import * as v58 from "./.verify/nc29_car_fleet__pairwise/harness";
import * as v59 from "./.verify/nc30_largest_rectangle/harness";
import * as v60 from "./.verify/nc30_largest_rectangle__expand_from_each_bar/harness";
import * as v61 from "./.verify/nc31_search_2d_matrix/harness";
import * as v62 from "./.verify/nc31_search_2d_matrix__staircase/harness";
import * as v63 from "./.verify/nc32_koko_bananas/harness";
import * as v64 from "./.verify/nc32_koko_bananas__linear_scan/harness";
import * as v65 from "./.verify/nc33_time_map/harness";
import * as v66 from "./.verify/nc33_time_map__linear_scan/harness";
import * as v67 from "./.verify/nc34_median_two_sorted/harness";
import * as v68 from "./.verify/nc34_median_two_sorted__concat_sort/harness";
import * as v69 from "./.verify/nc34_median_two_sorted__partition_search/harness";
import * as v70 from "./.verify/nc35_insert_interval/harness";
import * as v71 from "./.verify/nc35_insert_interval__merge_after_append/harness";
import * as v72 from "./.verify/nc36_merge_intervals/harness";
import * as v73 from "./.verify/nc36_merge_intervals__sweep_counts/harness";
import * as v74 from "./.verify/nc37_non_overlapping/harness";
import * as v75 from "./.verify/nc37_non_overlapping__by_start/harness";
import * as v76 from "./.verify/nc38_meeting_rooms/harness";
import * as v77 from "./.verify/nc38_meeting_rooms__pairwise/harness";
import * as v78 from "./.verify/nc39_meeting_rooms_ii/harness";
import * as v79 from "./.verify/nc39_meeting_rooms_ii__count_at_each_start/harness";
import * as v80 from "./.verify/nc40_min_interval/harness";
import * as v81 from "./.verify/nc40_min_interval__offline_by_length/harness";
import * as v82 from "./.verify/nc41_maximum_subarray/harness";
import * as v83 from "./.verify/nc41_maximum_subarray__prefix_minimum/harness";
import * as v84 from "./.verify/nc42_jump_game/harness";
import * as v85 from "./.verify/nc42_jump_game__backwards/harness";
import * as v86 from "./.verify/nc43_jump_game_ii/harness";
import * as v87 from "./.verify/nc43_jump_game_ii__reverse_greedy/harness";
import * as v88 from "./.verify/nc44_gas_station/harness";
import * as v89 from "./.verify/nc44_gas_station__try_each_start/harness";
import * as v90 from "./.verify/nc45_hand_of_straights/harness";
import * as v91 from "./.verify/nc45_hand_of_straights__sorted_consume/harness";
import * as v92 from "./.verify/nc46_merge_triplets/harness";
import * as v93 from "./.verify/nc46_merge_triplets__track_positions/harness";
import * as v94 from "./.verify/nc47_partition_labels/harness";
import * as v95 from "./.verify/nc47_partition_labels__expand_end/harness";
import * as v96 from "./.verify/nc48_valid_parenthesis_string/harness";
import * as v97 from "./.verify/nc48_valid_parenthesis_string__two_passes/harness";
import * as v98 from "./.verify/nc49_single_number/harness";
import * as v99 from "./.verify/nc49_single_number__sum_of_uniques/harness";
import * as v100 from "./.verify/nc50_number_of_one_bits/harness";
import * as v101 from "./.verify/nc50_number_of_one_bits__shift_and_test/harness";
import * as v102 from "./.verify/nc51_counting_bits/harness";
import * as v103 from "./.verify/nc51_counting_bits__popcount_each/harness";
import * as v104 from "./.verify/nc52_reverse_bits/harness";
import * as v105 from "./.verify/nc52_reverse_bits__via_binary_string/harness";
import * as v106 from "./.verify/nc53_missing_number/harness";
import * as v107 from "./.verify/nc53_missing_number__gauss_sum/harness";
import * as v108 from "./.verify/nc54_sum_of_two_integers/harness";
import * as v109 from "./.verify/nc54_sum_of_two_integers__full_adder/harness";
import * as v110 from "./.verify/nc55_reverse_integer/harness";
import * as v111 from "./.verify/nc55_reverse_integer__via_string/harness";
import * as v112 from "./.verify/nc56_rotate_image/harness";
import * as v113 from "./.verify/nc56_rotate_image__by_index/harness";
import * as v114 from "./.verify/nc57_spiral_matrix/harness";
import * as v115 from "./.verify/nc57_spiral_matrix__boundaries/harness";
import * as v116 from "./.verify/nc58_set_matrix_zeroes/harness";
import * as v117 from "./.verify/nc58_set_matrix_zeroes__by_scanning/harness";
import * as v118 from "./.verify/nc59_happy_number/harness";
import * as v119 from "./.verify/nc59_happy_number__floyd_cycle/harness";
import * as v120 from "./.verify/nc60_plus_one/harness";
import * as v121 from "./.verify/nc60_plus_one__via_number/harness";
import * as v122 from "./.verify/nc61_pow/harness";
import * as v123 from "./.verify/nc61_pow__repeated_multiplication/harness";
import * as v124 from "./.verify/nc62_multiply_strings/harness";
import * as v125 from "./.verify/nc62_multiply_strings__partial_sums/harness";
import * as v126 from "./.verify/nc63_detect_squares/harness";
import * as v127 from "./.verify/nc63_detect_squares__by_side_length/harness";

type Case = [string, string, string];

const VARIANTS: [string, string, () => Case[]][] = [
  ["nc01_contains_duplicate", "Solution 1", v0.run],
  ["nc01_contains_duplicate", "Solution 2 · Sorting", v1.run],
  ["nc02_valid_anagram", "Solution 1", v2.run],
  ["nc02_valid_anagram", "Solution 2 · Sorting", v3.run],
  ["nc03_two_sum", "Solution 1", v4.run],
  ["nc03_two_sum", "Solution 2 · Sorted two pointer", v5.run],
  ["nc04_group_anagrams", "Solution 1", v6.run],
  ["nc04_group_anagrams", "Solution 2 · Sorted key", v7.run],
  ["nc05_top_k_frequent", "Solution 1", v8.run],
  ["nc05_top_k_frequent", "Solution 2 · Sorting", v9.run],
  ["nc06_product_except_self", "Solution 1", v10.run],
  ["nc06_product_except_self", "Solution 2 · Brute force", v11.run],
  ["nc07_longest_consecutive", "Solution 1", v12.run],
  ["nc07_longest_consecutive", "Solution 2 · Sorting", v13.run],
  ["nc08_valid_palindrome", "Solution 1", v14.run],
  ["nc08_valid_palindrome", "Solution 2 · Cleaned reverse", v15.run],
  ["nc09_two_sum_sorted", "Solution 1", v16.run],
  ["nc09_two_sum_sorted", "Solution 2 · Binary search", v17.run],
  ["nc10_three_sum", "Solution 1", v18.run],
  ["nc10_three_sum", "Solution 2 · Brute force", v19.run],
  ["nc11_container_water", "Solution 1", v20.run],
  ["nc11_container_water", "Solution 2 · Brute force", v21.run],
  ["nc12_best_time_stock", "Solution 1", v22.run],
  ["nc12_best_time_stock", "Solution 2 · Brute force", v23.run],
  ["nc13_longest_substring", "Solution 1", v24.run],
  ["nc13_longest_substring", "Solution 2 · Index scan", v25.run],
  ["nc14_character_replacement", "Solution 1", v26.run],
  ["nc14_character_replacement", "Solution 2 · Per character", v27.run],
  ["nc15_permutation_in_string", "Solution 1", v28.run],
  ["nc15_permutation_in_string", "Solution 2 · Sorted windows", v29.run],
  ["nc16_valid_parentheses", "Solution 1", v30.run],
  ["nc16_valid_parentheses", "Solution 2 · Reduction", v31.run],
  ["nc17_min_stack", "Solution 1", v32.run],
  ["nc17_min_stack", "Solution 2 · Pair stack", v33.run],
  ["nc18_daily_temperatures", "Solution 1", v34.run],
  ["nc18_daily_temperatures", "Solution 2 · Brute force", v35.run],
  ["nc19_binary_search", "Solution 1", v36.run],
  ["nc19_binary_search", "Solution 2 · Recursive", v37.run],
  ["nc20_find_min_rotated", "Solution 1", v38.run],
  ["nc20_find_min_rotated", "Solution 2 · Linear scan", v39.run],
  ["nc21_search_rotated", "Solution 1", v40.run],
  ["nc21_search_rotated", "Solution 2 · Find pivot", v41.run],
  ["nc22_encode_decode", "Solution 1", v42.run],
  ["nc22_encode_decode", "Solution 2 · Escaping", v43.run],
  ["nc23_valid_sudoku", "Solution 1", v44.run],
  ["nc23_valid_sudoku", "Solution 2 · By unit", v45.run],
  ["nc24_trapping_rain_water", "Solution 1", v46.run],
  ["nc24_trapping_rain_water", "Solution 2 · Prefix maxima", v47.run],
  ["nc25_min_window_substring", "Solution 1", v48.run],
  ["nc25_min_window_substring", "Solution 2 · Filtered positions", v49.run],
  ["nc26_sliding_window_maximum", "Solution 1", v50.run],
  ["nc26_sliding_window_maximum", "Solution 2 · Brute force", v51.run],
  ["nc26_sliding_window_maximum", "Solution 3 · Monotonic deque", v52.run],
  ["nc27_eval_rpn", "Solution 1", v53.run],
  ["nc27_eval_rpn", "Solution 2 · Recursive", v54.run],
  ["nc28_generate_parentheses", "Solution 1", v55.run],
  ["nc28_generate_parentheses", "Solution 2 · By composition", v56.run],
  ["nc29_car_fleet", "Solution 1", v57.run],
  ["nc29_car_fleet", "Solution 2 · Pairwise", v58.run],
  ["nc30_largest_rectangle", "Solution 1", v59.run],
  ["nc30_largest_rectangle", "Solution 2 · Expand from each bar", v60.run],
  ["nc31_search_2d_matrix", "Solution 1", v61.run],
  ["nc31_search_2d_matrix", "Solution 2 · Staircase", v62.run],
  ["nc32_koko_bananas", "Solution 1", v63.run],
  ["nc32_koko_bananas", "Solution 2 · Linear scan", v64.run],
  ["nc33_time_map", "Solution 1", v65.run],
  ["nc33_time_map", "Solution 2 · Linear scan", v66.run],
  ["nc34_median_two_sorted", "Solution 1", v67.run],
  ["nc34_median_two_sorted", "Solution 2 · Concat sort", v68.run],
  ["nc34_median_two_sorted", "Solution 3 · Partition search", v69.run],
  ["nc35_insert_interval", "Solution 1", v70.run],
  ["nc35_insert_interval", "Solution 2 · Merge after append", v71.run],
  ["nc36_merge_intervals", "Solution 1", v72.run],
  ["nc36_merge_intervals", "Solution 2 · Sweep counts", v73.run],
  ["nc37_non_overlapping", "Solution 1", v74.run],
  ["nc37_non_overlapping", "Solution 2 · By start", v75.run],
  ["nc38_meeting_rooms", "Solution 1", v76.run],
  ["nc38_meeting_rooms", "Solution 2 · Pairwise", v77.run],
  ["nc39_meeting_rooms_ii", "Solution 1", v78.run],
  ["nc39_meeting_rooms_ii", "Solution 2 · Count at each start", v79.run],
  ["nc40_min_interval", "Solution 1", v80.run],
  ["nc40_min_interval", "Solution 2 · Offline by length", v81.run],
  ["nc41_maximum_subarray", "Solution 1", v82.run],
  ["nc41_maximum_subarray", "Solution 2 · Prefix minimum", v83.run],
  ["nc42_jump_game", "Solution 1", v84.run],
  ["nc42_jump_game", "Solution 2 · Backwards", v85.run],
  ["nc43_jump_game_ii", "Solution 1", v86.run],
  ["nc43_jump_game_ii", "Solution 2 · Reverse greedy", v87.run],
  ["nc44_gas_station", "Solution 1", v88.run],
  ["nc44_gas_station", "Solution 2 · Try each start", v89.run],
  ["nc45_hand_of_straights", "Solution 1", v90.run],
  ["nc45_hand_of_straights", "Solution 2 · Sorted consume", v91.run],
  ["nc46_merge_triplets", "Solution 1", v92.run],
  ["nc46_merge_triplets", "Solution 2 · Track positions", v93.run],
  ["nc47_partition_labels", "Solution 1", v94.run],
  ["nc47_partition_labels", "Solution 2 · Expand end", v95.run],
  ["nc48_valid_parenthesis_string", "Solution 1", v96.run],
  ["nc48_valid_parenthesis_string", "Solution 2 · Two passes", v97.run],
  ["nc49_single_number", "Solution 1", v98.run],
  ["nc49_single_number", "Solution 2 · Sum of uniques", v99.run],
  ["nc50_number_of_one_bits", "Solution 1", v100.run],
  ["nc50_number_of_one_bits", "Solution 2 · Shift and test", v101.run],
  ["nc51_counting_bits", "Solution 1", v102.run],
  ["nc51_counting_bits", "Solution 2 · Popcount each", v103.run],
  ["nc52_reverse_bits", "Solution 1", v104.run],
  ["nc52_reverse_bits", "Solution 2 · Via binary string", v105.run],
  ["nc53_missing_number", "Solution 1", v106.run],
  ["nc53_missing_number", "Solution 2 · Gauss sum", v107.run],
  ["nc54_sum_of_two_integers", "Solution 1", v108.run],
  ["nc54_sum_of_two_integers", "Solution 2 · Full adder", v109.run],
  ["nc55_reverse_integer", "Solution 1", v110.run],
  ["nc55_reverse_integer", "Solution 2 · Via string", v111.run],
  ["nc56_rotate_image", "Solution 1", v112.run],
  ["nc56_rotate_image", "Solution 2 · By index", v113.run],
  ["nc57_spiral_matrix", "Solution 1", v114.run],
  ["nc57_spiral_matrix", "Solution 2 · Boundaries", v115.run],
  ["nc58_set_matrix_zeroes", "Solution 1", v116.run],
  ["nc58_set_matrix_zeroes", "Solution 2 · By scanning", v117.run],
  ["nc59_happy_number", "Solution 1", v118.run],
  ["nc59_happy_number", "Solution 2 · Floyd cycle", v119.run],
  ["nc60_plus_one", "Solution 1", v120.run],
  ["nc60_plus_one", "Solution 2 · Via number", v121.run],
  ["nc61_pow", "Solution 1", v122.run],
  ["nc61_pow", "Solution 2 · Repeated multiplication", v123.run],
  ["nc62_multiply_strings", "Solution 1", v124.run],
  ["nc62_multiply_strings", "Solution 2 · Partial sums", v125.run],
  ["nc63_detect_squares", "Solution 1", v126.run],
  ["nc63_detect_squares", "Solution 2 · By side length", v127.run],
];

const failures: string[] = [];
for (const [module, label, run] of VARIANTS) {
  let cases: Case[];
  try {
    cases = run();
  } catch (error) {
    failures.push(`${module} [${label}] threw ${error}`);
    continue;
  }
  if (cases.length === 0) {
    failures.push(`${module} [${label}] harness produced no cases`);
  }
  for (const [name, expected, actual] of cases) {
    if (expected !== actual) {
      failures.push(`${module} [${label}] ${name}: expected ${expected}, got ${actual}`);
    }
  }
}
for (const failure of failures) console.log("FAIL " + failure);
console.log(`${VARIANTS.length} TypeScript variants checked, ${failures.length} failures`);
if (failures.length > 0) process.exit(1);
