// GENERATED by `gleam run -m generate` in drills/ - do not edit.
// Runs every TypeScript solution variant against its harness:
//   bun verify_all.ts     (from drills/ts)
import * as v0 from "./.verify/nc01_contains_duplicate__sorting/harness";
import * as v1 from "./.verify/nc01_contains_duplicate/harness";
import * as v2 from "./.verify/nc02_valid_anagram__sorting/harness";
import * as v3 from "./.verify/nc02_valid_anagram/harness";
import * as v4 from "./.verify/nc03_two_sum__sorted_two_pointer/harness";
import * as v5 from "./.verify/nc03_two_sum/harness";
import * as v6 from "./.verify/nc04_group_anagrams__sorted_key/harness";
import * as v7 from "./.verify/nc04_group_anagrams/harness";
import * as v8 from "./.verify/nc05_top_k_frequent__sorting/harness";
import * as v9 from "./.verify/nc05_top_k_frequent/harness";
import * as v10 from "./.verify/nc06_product_except_self__brute_force/harness";
import * as v11 from "./.verify/nc06_product_except_self/harness";
import * as v12 from "./.verify/nc07_longest_consecutive__sorting/harness";
import * as v13 from "./.verify/nc07_longest_consecutive/harness";
import * as v14 from "./.verify/nc08_valid_palindrome__cleaned_reverse/harness";
import * as v15 from "./.verify/nc08_valid_palindrome/harness";
import * as v16 from "./.verify/nc09_two_sum_sorted__binary_search/harness";
import * as v17 from "./.verify/nc09_two_sum_sorted/harness";
import * as v18 from "./.verify/nc100_edit_distance__memoised/harness";
import * as v19 from "./.verify/nc100_edit_distance/harness";
import * as v20 from "./.verify/nc101_burst_balloons__bottom_up/harness";
import * as v21 from "./.verify/nc101_burst_balloons/harness";
import * as v22 from "./.verify/nc102_regular_expression_matching__no_cache/harness";
import * as v23 from "./.verify/nc102_regular_expression_matching/harness";
import * as v24 from "./.verify/nc103_implement_trie__prefix_set/harness";
import * as v25 from "./.verify/nc103_implement_trie/harness";
import * as v26 from "./.verify/nc104_word_dictionary__by_length/harness";
import * as v27 from "./.verify/nc104_word_dictionary/harness";
import * as v28 from "./.verify/nc105_word_search_ii__each_word/harness";
import * as v29 from "./.verify/nc105_word_search_ii/harness";
import * as v30 from "./.verify/nc106_number_of_islands__union_find/harness";
import * as v31 from "./.verify/nc106_number_of_islands/harness";
import * as v32 from "./.verify/nc107_clone_graph__depth_first/harness";
import * as v33 from "./.verify/nc107_clone_graph/harness";
import * as v34 from "./.verify/nc108_max_area_of_island__breadth_first/harness";
import * as v35 from "./.verify/nc108_max_area_of_island/harness";
import * as v36 from "./.verify/nc109_pacific_atlantic__from_each_cell/harness";
import * as v37 from "./.verify/nc109_pacific_atlantic/harness";
import * as v38 from "./.verify/nc10_three_sum__brute_force/harness";
import * as v39 from "./.verify/nc10_three_sum/harness";
import * as v40 from "./.verify/nc110_surrounded_regions__per_region/harness";
import * as v41 from "./.verify/nc110_surrounded_regions/harness";
import * as v42 from "./.verify/nc111_rotting_oranges__simulate_minutes/harness";
import * as v43 from "./.verify/nc111_rotting_oranges/harness";
import * as v44 from "./.verify/nc112_walls_and_gates__from_each_room/harness";
import * as v45 from "./.verify/nc112_walls_and_gates/harness";
import * as v46 from "./.verify/nc113_course_schedule__dfs_colours/harness";
import * as v47 from "./.verify/nc113_course_schedule/harness";
import * as v48 from "./.verify/nc114_course_schedule_ii__dfs_postorder/harness";
import * as v49 from "./.verify/nc114_course_schedule_ii/harness";
import * as v50 from "./.verify/nc115_redundant_connection__by_removal/harness";
import * as v51 from "./.verify/nc115_redundant_connection/harness";
import * as v52 from "./.verify/nc116_connected_components__by_traversal/harness";
import * as v53 from "./.verify/nc116_connected_components/harness";
import * as v54 from "./.verify/nc117_graph_valid_tree__union_find/harness";
import * as v55 from "./.verify/nc117_graph_valid_tree/harness";
import * as v56 from "./.verify/nc118_word_ladder__compare_pairs/harness";
import * as v57 from "./.verify/nc118_word_ladder/harness";
import * as v58 from "./.verify/nc119_reconstruct_itinerary__backtracking/harness";
import * as v59 from "./.verify/nc119_reconstruct_itinerary/harness";
import * as v60 from "./.verify/nc11_container_water__brute_force/harness";
import * as v61 from "./.verify/nc11_container_water/harness";
import * as v62 from "./.verify/nc120_min_cost_connect_points__kruskal/harness";
import * as v63 from "./.verify/nc120_min_cost_connect_points/harness";
import * as v64 from "./.verify/nc121_network_delay_time__bellman_ford/harness";
import * as v65 from "./.verify/nc121_network_delay_time/harness";
import * as v66 from "./.verify/nc122_swim_in_water__binary_search/harness";
import * as v67 from "./.verify/nc122_swim_in_water/harness";
import * as v68 from "./.verify/nc123_alien_dictionary__dfs_postorder/harness";
import * as v69 from "./.verify/nc123_alien_dictionary/harness";
import * as v70 from "./.verify/nc124_cheapest_flights__breadth_first/harness";
import * as v71 from "./.verify/nc124_cheapest_flights/harness";
import * as v72 from "./.verify/nc125_reverse_linked_list__by_recursion/harness";
import * as v73 from "./.verify/nc125_reverse_linked_list/harness";
import * as v74 from "./.verify/nc126_merge_two_sorted_lists__by_recursion/harness";
import * as v75 from "./.verify/nc126_merge_two_sorted_lists/harness";
import * as v76 from "./.verify/nc127_reorder_list__via_array/harness";
import * as v77 from "./.verify/nc127_reorder_list/harness";
import * as v78 from "./.verify/nc128_remove_nth_from_end__by_length/harness";
import * as v79 from "./.verify/nc128_remove_nth_from_end/harness";
import * as v80 from "./.verify/nc129_copy_random_list__interleaved/harness";
import * as v81 from "./.verify/nc129_copy_random_list/harness";
import * as v82 from "./.verify/nc12_best_time_stock__brute_force/harness";
import * as v83 from "./.verify/nc12_best_time_stock/harness";
import * as v84 from "./.verify/nc130_add_two_numbers/harness";
import * as v85 from "./.verify/nc130_add_two_numbers__via_digits_array/harness";
import * as v86 from "./.verify/nc131_linked_list_cycle__seen_set/harness";
import * as v87 from "./.verify/nc131_linked_list_cycle/harness";
import * as v88 from "./.verify/nc132_find_the_duplicate__counting/harness";
import * as v89 from "./.verify/nc132_find_the_duplicate/harness";
import * as v90 from "./.verify/nc133_lru_cache/harness";
import * as v91 from "./.verify/nc133_lru_cache__linked_nodes/harness";
import * as v92 from "./.verify/nc134_merge_k_sorted_lists/harness";
import * as v93 from "./.verify/nc134_merge_k_sorted_lists__smallest_head/harness";
import * as v94 from "./.verify/nc135_reverse_k_group__count_first/harness";
import * as v95 from "./.verify/nc135_reverse_k_group/harness";
import * as v96 from "./.verify/nc136_invert_binary_tree__by_rebuilding/harness";
import * as v97 from "./.verify/nc136_invert_binary_tree/harness";
import * as v98 from "./.verify/nc137_maximum_depth__by_levels/harness";
import * as v99 from "./.verify/nc137_maximum_depth/harness";
import * as v100 from "./.verify/nc138_diameter_of_binary_tree__height_per_node/harness";
import * as v101 from "./.verify/nc138_diameter_of_binary_tree/harness";
import * as v102 from "./.verify/nc139_balanced_binary_tree__height_per_node/harness";
import * as v103 from "./.verify/nc139_balanced_binary_tree/harness";
import * as v104 from "./.verify/nc13_longest_substring__index_scan/harness";
import * as v105 from "./.verify/nc13_longest_substring/harness";
import * as v106 from "./.verify/nc140_same_tree__by_serialising/harness";
import * as v107 from "./.verify/nc140_same_tree/harness";
import * as v108 from "./.verify/nc141_subtree_of_another_tree/harness";
import * as v109 from "./.verify/nc141_subtree_of_another_tree__by_serialising/harness";
import * as v110 from "./.verify/nc142_lowest_common_ancestor_bst__by_paths/harness";
import * as v111 from "./.verify/nc142_lowest_common_ancestor_bst/harness";
import * as v112 from "./.verify/nc143_level_order_traversal__by_depth/harness";
import * as v113 from "./.verify/nc143_level_order_traversal/harness";
import * as v114 from "./.verify/nc144_right_side_view__right_first/harness";
import * as v115 from "./.verify/nc144_right_side_view/harness";
import * as v116 from "./.verify/nc145_count_good_nodes__by_path/harness";
import * as v117 from "./.verify/nc145_count_good_nodes/harness";
import * as v118 from "./.verify/nc146_validate_bst__in_order/harness";
import * as v119 from "./.verify/nc146_validate_bst/harness";
import * as v120 from "./.verify/nc147_kth_smallest_bst__by_counting/harness";
import * as v121 from "./.verify/nc147_kth_smallest_bst/harness";
import * as v122 from "./.verify/nc148_build_tree_preorder_inorder/harness";
import * as v123 from "./.verify/nc148_build_tree_preorder_inorder__by_bounds/harness";
import * as v124 from "./.verify/nc149_max_path_sum__all_paths/harness";
import * as v125 from "./.verify/nc149_max_path_sum/harness";
import * as v126 from "./.verify/nc14_character_replacement__per_character/harness";
import * as v127 from "./.verify/nc14_character_replacement/harness";
import * as v128 from "./.verify/nc150_serialize_deserialize__post_order/harness";
import * as v129 from "./.verify/nc150_serialize_deserialize/harness";
import * as v130 from "./.verify/nc15_permutation_in_string__sorted_windows/harness";
import * as v131 from "./.verify/nc15_permutation_in_string/harness";
import * as v132 from "./.verify/nc16_valid_parentheses__reduction/harness";
import * as v133 from "./.verify/nc16_valid_parentheses/harness";
import * as v134 from "./.verify/nc17_min_stack__pair_stack/harness";
import * as v135 from "./.verify/nc17_min_stack/harness";
import * as v136 from "./.verify/nc18_daily_temperatures__brute_force/harness";
import * as v137 from "./.verify/nc18_daily_temperatures/harness";
import * as v138 from "./.verify/nc19_binary_search__recursive/harness";
import * as v139 from "./.verify/nc19_binary_search/harness";
import * as v140 from "./.verify/nc20_find_min_rotated__linear_scan/harness";
import * as v141 from "./.verify/nc20_find_min_rotated/harness";
import * as v142 from "./.verify/nc21_search_rotated__find_pivot/harness";
import * as v143 from "./.verify/nc21_search_rotated/harness";
import * as v144 from "./.verify/nc22_encode_decode__escaping/harness";
import * as v145 from "./.verify/nc22_encode_decode/harness";
import * as v146 from "./.verify/nc23_valid_sudoku__by_unit/harness";
import * as v147 from "./.verify/nc23_valid_sudoku/harness";
import * as v148 from "./.verify/nc24_trapping_rain_water__prefix_maxima/harness";
import * as v149 from "./.verify/nc24_trapping_rain_water/harness";
import * as v150 from "./.verify/nc25_min_window_substring__filtered_positions/harness";
import * as v151 from "./.verify/nc25_min_window_substring/harness";
import * as v152 from "./.verify/nc26_sliding_window_maximum__brute_force/harness";
import * as v153 from "./.verify/nc26_sliding_window_maximum__monotonic_deque/harness";
import * as v154 from "./.verify/nc26_sliding_window_maximum/harness";
import * as v155 from "./.verify/nc27_eval_rpn__recursive/harness";
import * as v156 from "./.verify/nc27_eval_rpn/harness";
import * as v157 from "./.verify/nc28_generate_parentheses__by_composition/harness";
import * as v158 from "./.verify/nc28_generate_parentheses/harness";
import * as v159 from "./.verify/nc29_car_fleet__pairwise/harness";
import * as v160 from "./.verify/nc29_car_fleet/harness";
import * as v161 from "./.verify/nc30_largest_rectangle__expand_from_each_bar/harness";
import * as v162 from "./.verify/nc30_largest_rectangle/harness";
import * as v163 from "./.verify/nc31_search_2d_matrix__staircase/harness";
import * as v164 from "./.verify/nc31_search_2d_matrix/harness";
import * as v165 from "./.verify/nc32_koko_bananas__linear_scan/harness";
import * as v166 from "./.verify/nc32_koko_bananas/harness";
import * as v167 from "./.verify/nc33_time_map__linear_scan/harness";
import * as v168 from "./.verify/nc33_time_map/harness";
import * as v169 from "./.verify/nc34_median_two_sorted__concat_sort/harness";
import * as v170 from "./.verify/nc34_median_two_sorted/harness";
import * as v171 from "./.verify/nc34_median_two_sorted__partition_search/harness";
import * as v172 from "./.verify/nc35_insert_interval__merge_after_append/harness";
import * as v173 from "./.verify/nc35_insert_interval/harness";
import * as v174 from "./.verify/nc36_merge_intervals__sweep_counts/harness";
import * as v175 from "./.verify/nc36_merge_intervals/harness";
import * as v176 from "./.verify/nc37_non_overlapping__by_start/harness";
import * as v177 from "./.verify/nc37_non_overlapping/harness";
import * as v178 from "./.verify/nc38_meeting_rooms__pairwise/harness";
import * as v179 from "./.verify/nc38_meeting_rooms/harness";
import * as v180 from "./.verify/nc39_meeting_rooms_ii__count_at_each_start/harness";
import * as v181 from "./.verify/nc39_meeting_rooms_ii/harness";
import * as v182 from "./.verify/nc40_min_interval/harness";
import * as v183 from "./.verify/nc40_min_interval__offline_by_length/harness";
import * as v184 from "./.verify/nc41_maximum_subarray__prefix_minimum/harness";
import * as v185 from "./.verify/nc41_maximum_subarray/harness";
import * as v186 from "./.verify/nc42_jump_game__backwards/harness";
import * as v187 from "./.verify/nc42_jump_game/harness";
import * as v188 from "./.verify/nc43_jump_game_ii__reverse_greedy/harness";
import * as v189 from "./.verify/nc43_jump_game_ii/harness";
import * as v190 from "./.verify/nc44_gas_station__try_each_start/harness";
import * as v191 from "./.verify/nc44_gas_station/harness";
import * as v192 from "./.verify/nc45_hand_of_straights__sorted_consume/harness";
import * as v193 from "./.verify/nc45_hand_of_straights/harness";
import * as v194 from "./.verify/nc46_merge_triplets__track_positions/harness";
import * as v195 from "./.verify/nc46_merge_triplets/harness";
import * as v196 from "./.verify/nc47_partition_labels__expand_end/harness";
import * as v197 from "./.verify/nc47_partition_labels/harness";
import * as v198 from "./.verify/nc48_valid_parenthesis_string__two_passes/harness";
import * as v199 from "./.verify/nc48_valid_parenthesis_string/harness";
import * as v200 from "./.verify/nc49_single_number__sum_of_uniques/harness";
import * as v201 from "./.verify/nc49_single_number/harness";
import * as v202 from "./.verify/nc50_number_of_one_bits__shift_and_test/harness";
import * as v203 from "./.verify/nc50_number_of_one_bits/harness";
import * as v204 from "./.verify/nc51_counting_bits__popcount_each/harness";
import * as v205 from "./.verify/nc51_counting_bits/harness";
import * as v206 from "./.verify/nc52_reverse_bits__via_binary_string/harness";
import * as v207 from "./.verify/nc52_reverse_bits/harness";
import * as v208 from "./.verify/nc53_missing_number__gauss_sum/harness";
import * as v209 from "./.verify/nc53_missing_number/harness";
import * as v210 from "./.verify/nc54_sum_of_two_integers__full_adder/harness";
import * as v211 from "./.verify/nc54_sum_of_two_integers/harness";
import * as v212 from "./.verify/nc55_reverse_integer__via_string/harness";
import * as v213 from "./.verify/nc55_reverse_integer/harness";
import * as v214 from "./.verify/nc56_rotate_image__by_index/harness";
import * as v215 from "./.verify/nc56_rotate_image/harness";
import * as v216 from "./.verify/nc57_spiral_matrix/harness";
import * as v217 from "./.verify/nc57_spiral_matrix__boundaries/harness";
import * as v218 from "./.verify/nc58_set_matrix_zeroes__by_scanning/harness";
import * as v219 from "./.verify/nc58_set_matrix_zeroes/harness";
import * as v220 from "./.verify/nc59_happy_number__floyd_cycle/harness";
import * as v221 from "./.verify/nc59_happy_number/harness";
import * as v222 from "./.verify/nc60_plus_one__via_number/harness";
import * as v223 from "./.verify/nc60_plus_one/harness";
import * as v224 from "./.verify/nc61_pow__repeated_multiplication/harness";
import * as v225 from "./.verify/nc61_pow/harness";
import * as v226 from "./.verify/nc62_multiply_strings__partial_sums/harness";
import * as v227 from "./.verify/nc62_multiply_strings/harness";
import * as v228 from "./.verify/nc63_detect_squares__by_side_length/harness";
import * as v229 from "./.verify/nc63_detect_squares/harness";
import * as v230 from "./.verify/nc64_climbing_stairs__memoised/harness";
import * as v231 from "./.verify/nc64_climbing_stairs/harness";
import * as v232 from "./.verify/nc65_min_cost_climbing_stairs__from_the_top/harness";
import * as v233 from "./.verify/nc65_min_cost_climbing_stairs/harness";
import * as v234 from "./.verify/nc66_house_robber__memoised/harness";
import * as v235 from "./.verify/nc66_house_robber/harness";
import * as v236 from "./.verify/nc67_house_robber_ii__both_at_once/harness";
import * as v237 from "./.verify/nc67_house_robber_ii/harness";
import * as v238 from "./.verify/nc68_longest_palindrome__brute_force/harness";
import * as v239 from "./.verify/nc68_longest_palindrome/harness";
import * as v240 from "./.verify/nc69_palindromic_substrings__dp_table/harness";
import * as v241 from "./.verify/nc69_palindromic_substrings/harness";
import * as v242 from "./.verify/nc70_decode_ways__memoised/harness";
import * as v243 from "./.verify/nc70_decode_ways/harness";
import * as v244 from "./.verify/nc71_coin_change__breadth_first/harness";
import * as v245 from "./.verify/nc71_coin_change/harness";
import * as v246 from "./.verify/nc72_maximum_product_subarray__prefix_and_suffix/harness";
import * as v247 from "./.verify/nc72_maximum_product_subarray/harness";
import * as v248 from "./.verify/nc73_word_break__memoised/harness";
import * as v249 from "./.verify/nc73_word_break/harness";
import * as v250 from "./.verify/nc74_longest_increasing_subsequence/harness";
import * as v251 from "./.verify/nc74_longest_increasing_subsequence__patience/harness";
import * as v252 from "./.verify/nc75_partition_equal_subset__memoised/harness";
import * as v253 from "./.verify/nc75_partition_equal_subset/harness";
import * as v254 from "./.verify/nc76_kth_largest_stream__keep_everything/harness";
import * as v255 from "./.verify/nc76_kth_largest_stream/harness";
import * as v256 from "./.verify/nc77_last_stone_weight__find_max_each_round/harness";
import * as v257 from "./.verify/nc77_last_stone_weight/harness";
import * as v258 from "./.verify/nc78_k_closest_points/harness";
import * as v259 from "./.verify/nc78_k_closest_points__select_k_times/harness";
import * as v260 from "./.verify/nc79_kth_largest_array/harness";
import * as v261 from "./.verify/nc79_kth_largest_array__quickselect/harness";
import * as v262 from "./.verify/nc80_task_scheduler__simulate/harness";
import * as v263 from "./.verify/nc80_task_scheduler/harness";
import * as v264 from "./.verify/nc81_design_twitter/harness";
import * as v265 from "./.verify/nc81_design_twitter__merge_per_user/harness";
import * as v266 from "./.verify/nc82_find_median_stream__sorted_list/harness";
import * as v267 from "./.verify/nc82_find_median_stream/harness";
import * as v268 from "./.verify/nc83_subsets__bitmask/harness";
import * as v269 from "./.verify/nc83_subsets/harness";
import * as v270 from "./.verify/nc84_combination_sum__by_target/harness";
import * as v271 from "./.verify/nc84_combination_sum/harness";
import * as v272 from "./.verify/nc85_permutations__insert_everywhere/harness";
import * as v273 from "./.verify/nc85_permutations/harness";
import * as v274 from "./.verify/nc86_subsets_ii__by_counts/harness";
import * as v275 from "./.verify/nc86_subsets_ii/harness";
import * as v276 from "./.verify/nc87_combination_sum_ii__dedupe_at_the_end/harness";
import * as v277 from "./.verify/nc87_combination_sum_ii/harness";
import * as v278 from "./.verify/nc88_word_search/harness";
import * as v279 from "./.verify/nc88_word_search__prune_by_counts/harness";
import * as v280 from "./.verify/nc89_palindrome_partitioning/harness";
import * as v281 from "./.verify/nc89_palindrome_partitioning__with_table/harness";
import * as v282 from "./.verify/nc90_letter_combinations__iterative_product/harness";
import * as v283 from "./.verify/nc90_letter_combinations/harness";
import * as v284 from "./.verify/nc91_n_queens__filter_permutations/harness";
import * as v285 from "./.verify/nc91_n_queens/harness";
import * as v286 from "./.verify/nc92_unique_paths/harness";
import * as v287 from "./.verify/nc92_unique_paths__pascal/harness";
import * as v288 from "./.verify/nc93_longest_common_subsequence__memoised/harness";
import * as v289 from "./.verify/nc93_longest_common_subsequence/harness";
import * as v290 from "./.verify/nc94_coin_change_ii__by_coin_recursion/harness";
import * as v291 from "./.verify/nc94_coin_change_ii/harness";
import * as v292 from "./.verify/nc95_target_sum/harness";
import * as v293 from "./.verify/nc95_target_sum__as_subset_sum/harness";
import * as v294 from "./.verify/nc96_stock_with_cooldown__memoised/harness";
import * as v295 from "./.verify/nc96_stock_with_cooldown/harness";
import * as v296 from "./.verify/nc97_interleaving_string/harness";
import * as v297 from "./.verify/nc97_interleaving_string__rolling_row/harness";
import * as v298 from "./.verify/nc98_longest_increasing_path__by_value_order/harness";
import * as v299 from "./.verify/nc98_longest_increasing_path/harness";
import * as v300 from "./.verify/nc99_distinct_subsequences__memoised/harness";
import * as v301 from "./.verify/nc99_distinct_subsequences/harness";

type Case = [string, string, string];

const VARIANTS: [string, string, () => Case[]][] = [
  ["nc01_contains_duplicate", "Sorting", v0.run],
  ["nc01_contains_duplicate", "Hash Set", v1.run],
  ["nc02_valid_anagram", "Sorting", v2.run],
  ["nc02_valid_anagram", "Count Map", v3.run],
  ["nc03_two_sum", "Sort + Two Pointers", v4.run],
  ["nc03_two_sum", "Hash Map", v5.run],
  ["nc04_group_anagrams", "Sorted Key", v6.run],
  ["nc04_group_anagrams", "Count Key", v7.run],
  ["nc05_top_k_frequent", "Sorting", v8.run],
  ["nc05_top_k_frequent", "Bucket Sort", v9.run],
  ["nc06_product_except_self", "Brute Force", v10.run],
  ["nc06_product_except_self", "Prefix & Suffix Products", v11.run],
  ["nc07_longest_consecutive", "Sorting", v12.run],
  ["nc07_longest_consecutive", "Hash Set", v13.run],
  ["nc08_valid_palindrome", "Nifty Python · Reverse", v14.run],
  ["nc08_valid_palindrome", "Two Pointers", v15.run],
  ["nc09_two_sum_sorted", "Binary Search", v16.run],
  ["nc09_two_sum_sorted", "Two Pointers", v17.run],
  ["nc100_edit_distance", "Top-Down Memo", v18.run],
  ["nc100_edit_distance", "Space-Saving DP", v19.run],
  ["nc101_burst_balloons", "Bottom-Up DP", v20.run],
  ["nc101_burst_balloons", "Top-Down Memo", v21.run],
  ["nc102_regular_expression_matching", "Recursion", v22.run],
  ["nc102_regular_expression_matching", "Top-Down Memo", v23.run],
  ["nc103_implement_trie", "Hash Set", v24.run],
  ["nc103_implement_trie", "Trie", v25.run],
  ["nc104_word_dictionary", "Brute Force", v26.run],
  ["nc104_word_dictionary", "Trie", v27.run],
  ["nc105_word_search_ii", "Backtracking", v28.run],
  ["nc105_word_search_ii", "Trie", v29.run],
  ["nc106_number_of_islands", "Union-Find", v30.run],
  ["nc106_number_of_islands", "DFS", v31.run],
  ["nc107_clone_graph", "DFS", v32.run],
  ["nc107_clone_graph", "BFS", v33.run],
  ["nc108_max_area_of_island", "BFS", v34.run],
  ["nc108_max_area_of_island", "DFS", v35.run],
  ["nc109_pacific_atlantic", "Brute Force", v36.run],
  ["nc109_pacific_atlantic", "BFS", v37.run],
  ["nc10_three_sum", "Brute Force", v38.run],
  ["nc10_three_sum", "Sort + Two Pointers", v39.run],
  ["nc110_surrounded_regions", "Per-Region DFS", v40.run],
  ["nc110_surrounded_regions", "Boundary DFS", v41.run],
  ["nc111_rotting_oranges", "Simulation", v42.run],
  ["nc111_rotting_oranges", "Multi-Source BFS", v43.run],
  ["nc112_walls_and_gates", "Brute Force", v44.run],
  ["nc112_walls_and_gates", "Multi-Source BFS", v45.run],
  ["nc113_course_schedule", "DFS Colouring", v46.run],
  ["nc113_course_schedule", "Topological Sort", v47.run],
  ["nc114_course_schedule_ii", "DFS Postorder", v48.run],
  ["nc114_course_schedule_ii", "Topological Sort", v49.run],
  ["nc115_redundant_connection", "Brute Force", v50.run],
  ["nc115_redundant_connection", "Union-Find", v51.run],
  ["nc116_connected_components", "DFS", v52.run],
  ["nc116_connected_components", "Union-Find", v53.run],
  ["nc117_graph_valid_tree", "Union-Find", v54.run],
  ["nc117_graph_valid_tree", "DFS", v55.run],
  ["nc118_word_ladder", "Brute Force", v56.run],
  ["nc118_word_ladder", "BFS", v57.run],
  ["nc119_reconstruct_itinerary", "Backtracking", v58.run],
  ["nc119_reconstruct_itinerary", "Hierholzer", v59.run],
  ["nc11_container_water", "Brute Force", v60.run],
  ["nc11_container_water", "Two Pointers", v61.run],
  ["nc120_min_cost_connect_points", "Kruskal", v62.run],
  ["nc120_min_cost_connect_points", "Prim", v63.run],
  ["nc121_network_delay_time", "Bellman-Ford", v64.run],
  ["nc121_network_delay_time", "Dijkstra", v65.run],
  ["nc122_swim_in_water", "Binary Search", v66.run],
  ["nc122_swim_in_water", "Dijkstra", v67.run],
  ["nc123_alien_dictionary", "DFS Topological Sort", v68.run],
  ["nc123_alien_dictionary", "Topological Sort", v69.run],
  ["nc124_cheapest_flights", "BFS", v70.run],
  ["nc124_cheapest_flights", "Bellman-Ford", v71.run],
  ["nc125_reverse_linked_list", "Recursion", v72.run],
  ["nc125_reverse_linked_list", "Iterative", v73.run],
  ["nc126_merge_two_sorted_lists", "Recursion", v74.run],
  ["nc126_merge_two_sorted_lists", "Iterative", v75.run],
  ["nc127_reorder_list", "Two Pointers", v76.run],
  ["nc127_reorder_list", "Fast & Slow Pointers", v77.run],
  ["nc128_remove_nth_from_end", "Two Pass", v78.run],
  ["nc128_remove_nth_from_end", "Two Pointers", v79.run],
  ["nc129_copy_random_list", "Interleaved Copies", v80.run],
  ["nc129_copy_random_list", "Hash Map", v81.run],
  ["nc12_best_time_stock", "Brute Force", v82.run],
  ["nc12_best_time_stock", "Greedy", v83.run],
  ["nc130_add_two_numbers", "Simulation", v84.run],
  ["nc130_add_two_numbers", "Solution 2 · Via digits array", v85.run],
  ["nc131_linked_list_cycle", "Hash Set", v86.run],
  ["nc131_linked_list_cycle", "Fast & Slow Pointers", v87.run],
  ["nc132_find_the_duplicate", "Binary Search", v88.run],
  ["nc132_find_the_duplicate", "Fast & Slow Pointers", v89.run],
  ["nc133_lru_cache", "Nifty Python · Dict Order", v90.run],
  ["nc133_lru_cache", "Design", v91.run],
  ["nc134_merge_k_sorted_lists", "Divide & Conquer", v92.run],
  ["nc134_merge_k_sorted_lists", "Solution 2 · Smallest head", v93.run],
  ["nc135_reverse_k_group", "Two Pass", v94.run],
  ["nc135_reverse_k_group", "Linked List", v95.run],
  ["nc136_invert_binary_tree", "Flatten & Rebuild", v96.run],
  ["nc136_invert_binary_tree", "DFS", v97.run],
  ["nc137_maximum_depth", "BFS", v98.run],
  ["nc137_maximum_depth", "DFS", v99.run],
  ["nc138_diameter_of_binary_tree", "Brute Force", v100.run],
  ["nc138_diameter_of_binary_tree", "DFS", v101.run],
  ["nc139_balanced_binary_tree", "Brute Force", v102.run],
  ["nc139_balanced_binary_tree", "DFS", v103.run],
  ["nc13_longest_substring", "Nifty Python · str.find", v104.run],
  ["nc13_longest_substring", "Sliding Window", v105.run],
  ["nc140_same_tree", "Serialisation", v106.run],
  ["nc140_same_tree", "DFS", v107.run],
  ["nc141_subtree_of_another_tree", "DFS", v108.run],
  ["nc141_subtree_of_another_tree", "Serialisation", v109.run],
  ["nc142_lowest_common_ancestor_bst", "Path Comparison", v110.run],
  ["nc142_lowest_common_ancestor_bst", "BST Walk", v111.run],
  ["nc143_level_order_traversal", "DFS", v112.run],
  ["nc143_level_order_traversal", "BFS", v113.run],
  ["nc144_right_side_view", "DFS", v114.run],
  ["nc144_right_side_view", "BFS", v115.run],
  ["nc145_count_good_nodes", "Full-Path DFS", v116.run],
  ["nc145_count_good_nodes", "DFS", v117.run],
  ["nc146_validate_bst", "In-Order Traversal", v118.run],
  ["nc146_validate_bst", "DFS", v119.run],
  ["nc147_kth_smallest_bst", "Subtree Counting", v120.run],
  ["nc147_kth_smallest_bst", "Iterative In-Order", v121.run],
  ["nc148_build_tree_preorder_inorder", "Recursion", v122.run],
  ["nc148_build_tree_preorder_inorder", "Hash Map", v123.run],
  ["nc149_max_path_sum", "Brute Force", v124.run],
  ["nc149_max_path_sum", "DFS", v125.run],
  ["nc14_character_replacement", "Per-Letter Window", v126.run],
  ["nc14_character_replacement", "Sliding Window", v127.run],
  ["nc150_serialize_deserialize", "Post-Order DFS", v128.run],
  ["nc150_serialize_deserialize", "Pre-Order DFS", v129.run],
  ["nc15_permutation_in_string", "Brute Force", v130.run],
  ["nc15_permutation_in_string", "Sliding Window", v131.run],
  ["nc16_valid_parentheses", "Nifty Python · Replace", v132.run],
  ["nc16_valid_parentheses", "Stack", v133.run],
  ["nc17_min_stack", "Pair Stack", v134.run],
  ["nc17_min_stack", "Two Stacks", v135.run],
  ["nc18_daily_temperatures", "Brute Force", v136.run],
  ["nc18_daily_temperatures", "Monotonic Stack", v137.run],
  ["nc19_binary_search", "Recursive Binary Search", v138.run],
  ["nc19_binary_search", "Binary Search", v139.run],
  ["nc20_find_min_rotated", "Linear Scan", v140.run],
  ["nc20_find_min_rotated", "Binary Search", v141.run],
  ["nc21_search_rotated", "Pivot + Binary Search", v142.run],
  ["nc21_search_rotated", "Binary Search", v143.run],
  ["nc22_encode_decode", "Separator + Escaping", v144.run],
  ["nc22_encode_decode", "Length Prefix", v145.run],
  ["nc23_valid_sudoku", "Check Each Unit", v146.run],
  ["nc23_valid_sudoku", "One Pass + Seen Set", v147.run],
  ["nc24_trapping_rain_water", "Prefix Maxima", v148.run],
  ["nc24_trapping_rain_water", "Two Pointers", v149.run],
  ["nc25_min_window_substring", "Filtered Sliding Window", v150.run],
  ["nc25_min_window_substring", "Sliding Window", v151.run],
  ["nc26_sliding_window_maximum", "Brute Force", v152.run],
  ["nc26_sliding_window_maximum", "Monotonic Deque", v153.run],
  ["nc26_sliding_window_maximum", "Prefix & Suffix Maxima", v154.run],
  ["nc27_eval_rpn", "Recursion", v155.run],
  ["nc27_eval_rpn", "Stack", v156.run],
  ["nc28_generate_parentheses", "Divide & Conquer", v157.run],
  ["nc28_generate_parentheses", "Backtracking", v158.run],
  ["nc29_car_fleet", "Brute Force", v159.run],
  ["nc29_car_fleet", "Sort + Greedy", v160.run],
  ["nc30_largest_rectangle", "Brute Force", v161.run],
  ["nc30_largest_rectangle", "Monotonic Stack", v162.run],
  ["nc31_search_2d_matrix", "Staircase Search", v163.run],
  ["nc31_search_2d_matrix", "Binary Search", v164.run],
  ["nc32_koko_bananas", "Brute Force", v165.run],
  ["nc32_koko_bananas", "Binary Search", v166.run],
  ["nc33_time_map", "Linear Scan", v167.run],
  ["nc33_time_map", "Binary Search", v168.run],
  ["nc34_median_two_sorted", "Sorting", v169.run],
  ["nc34_median_two_sorted", "Two Pointers", v170.run],
  ["nc34_median_two_sorted", "Binary Search", v171.run],
  ["nc35_insert_interval", "Sort + Merge", v172.run],
  ["nc35_insert_interval", "Intervals", v173.run],
  ["nc36_merge_intervals", "Sweep Line", v174.run],
  ["nc36_merge_intervals", "Intervals", v175.run],
  ["nc37_non_overlapping", "Greedy by Start", v176.run],
  ["nc37_non_overlapping", "Greedy", v177.run],
  ["nc38_meeting_rooms", "Brute Force", v178.run],
  ["nc38_meeting_rooms", "Sorting", v179.run],
  ["nc39_meeting_rooms_ii", "Brute Force", v180.run],
  ["nc39_meeting_rooms_ii", "Sweep Line", v181.run],
  ["nc40_min_interval", "Brute Force", v182.run],
  ["nc40_min_interval", "Greedy", v183.run],
  ["nc41_maximum_subarray", "Prefix Sums", v184.run],
  ["nc41_maximum_subarray", "Kadane", v185.run],
  ["nc42_jump_game", "Backwards Greedy", v186.run],
  ["nc42_jump_game", "Greedy", v187.run],
  ["nc43_jump_game_ii", "Reverse Greedy", v188.run],
  ["nc43_jump_game_ii", "Greedy", v189.run],
  ["nc44_gas_station", "Brute Force", v190.run],
  ["nc44_gas_station", "Greedy", v191.run],
  ["nc45_hand_of_straights", "Sorting", v192.run],
  ["nc45_hand_of_straights", "Greedy", v193.run],
  ["nc46_merge_triplets", "Coverage Check", v194.run],
  ["nc46_merge_triplets", "Greedy", v195.run],
  ["nc47_partition_labels", "Brute Force", v196.run],
  ["nc47_partition_labels", "Greedy", v197.run],
  ["nc48_valid_parenthesis_string", "Two Passes", v198.run],
  ["nc48_valid_parenthesis_string", "Greedy", v199.run],
  ["nc49_single_number", "Math", v200.run],
  ["nc49_single_number", "Bit Manipulation", v201.run],
  ["nc50_number_of_one_bits", "Shift & Test", v202.run],
  ["nc50_number_of_one_bits", "Bit Manipulation", v203.run],
  ["nc51_counting_bits", "Bit Manipulation", v204.run],
  ["nc51_counting_bits", "Bottom-Up DP", v205.run],
  ["nc52_reverse_bits", "Nifty Python · Strings", v206.run],
  ["nc52_reverse_bits", "Bit Manipulation", v207.run],
  ["nc53_missing_number", "Math", v208.run],
  ["nc53_missing_number", "Bit Manipulation", v209.run],
  ["nc54_sum_of_two_integers", "Full Adder", v210.run],
  ["nc54_sum_of_two_integers", "Bit Manipulation", v211.run],
  ["nc55_reverse_integer", "Nifty Python · Strings", v212.run],
  ["nc55_reverse_integer", "Math", v213.run],
  ["nc56_rotate_image", "Index Mapping", v214.run],
  ["nc56_rotate_image", "Nifty Python · Zip", v215.run],
  ["nc57_spiral_matrix", "Nifty Python · Rotate", v216.run],
  ["nc57_spiral_matrix", "Simulation", v217.run],
  ["nc58_set_matrix_zeroes", "Brute Force", v218.run],
  ["nc58_set_matrix_zeroes", "Hash Set", v219.run],
  ["nc59_happy_number", "Fast & Slow Pointers", v220.run],
  ["nc59_happy_number", "Hash Set", v221.run],
  ["nc60_plus_one", "Nifty Python · Big Int", v222.run],
  ["nc60_plus_one", "Math", v223.run],
  ["nc61_pow", "Brute Force", v224.run],
  ["nc61_pow", "Binary Exponentiation", v225.run],
  ["nc62_multiply_strings", "Simulation", v226.run],
  ["nc62_multiply_strings", "Math", v227.run],
  ["nc63_detect_squares", "Side Length Scan", v228.run],
  ["nc63_detect_squares", "Hash Map", v229.run],
  ["nc64_climbing_stairs", "Top-Down Memo", v230.run],
  ["nc64_climbing_stairs", "Space-Saving DP", v231.run],
  ["nc65_min_cost_climbing_stairs", "Backward DP", v232.run],
  ["nc65_min_cost_climbing_stairs", "Space-Saving DP", v233.run],
  ["nc66_house_robber", "Top-Down Memo", v234.run],
  ["nc66_house_robber", "Space-Saving DP", v235.run],
  ["nc67_house_robber_ii", "One-Pass DP", v236.run],
  ["nc67_house_robber_ii", "Space-Saving DP", v237.run],
  ["nc68_longest_palindrome", "Brute Force", v238.run],
  ["nc68_longest_palindrome", "Centre Expansion", v239.run],
  ["nc69_palindromic_substrings", "Bottom-Up DP", v240.run],
  ["nc69_palindromic_substrings", "Centre Expansion", v241.run],
  ["nc70_decode_ways", "Top-Down Memo", v242.run],
  ["nc70_decode_ways", "Space-Saving DP", v243.run],
  ["nc71_coin_change", "BFS", v244.run],
  ["nc71_coin_change", "Bottom-Up DP", v245.run],
  ["nc72_maximum_product_subarray", "Prefix & Suffix Products", v246.run],
  ["nc72_maximum_product_subarray", "Space-Saving DP", v247.run],
  ["nc73_word_break", "Top-Down Memo", v248.run],
  ["nc73_word_break", "Bottom-Up DP", v249.run],
  ["nc74_longest_increasing_subsequence", "Bottom-Up DP", v250.run],
  ["nc74_longest_increasing_subsequence", "Patience Sorting", v251.run],
  ["nc75_partition_equal_subset", "Top-Down Memo", v252.run],
  ["nc75_partition_equal_subset", "Bottom-Up DP", v253.run],
  ["nc76_kth_largest_stream", "Brute Force", v254.run],
  ["nc76_kth_largest_stream", "Heap", v255.run],
  ["nc77_last_stone_weight", "Brute Force", v256.run],
  ["nc77_last_stone_weight", "Heap", v257.run],
  ["nc78_k_closest_points", "Sorting", v258.run],
  ["nc78_k_closest_points", "Heap", v259.run],
  ["nc79_kth_largest_array", "Sorting", v260.run],
  ["nc79_kth_largest_array", "Quickselect", v261.run],
  ["nc80_task_scheduler", "Simulation", v262.run],
  ["nc80_task_scheduler", "Greedy", v263.run],
  ["nc81_design_twitter", "Design", v264.run],
  ["nc81_design_twitter", "Heap", v265.run],
  ["nc82_find_median_stream", "Sorted List", v266.run],
  ["nc82_find_median_stream", "Two Heaps", v267.run],
  ["nc83_subsets", "Bit Manipulation", v268.run],
  ["nc83_subsets", "Recursion", v269.run],
  ["nc84_combination_sum", "Bottom-Up DP", v270.run],
  ["nc84_combination_sum", "Backtracking", v271.run],
  ["nc85_permutations", "Iterative Insertion", v272.run],
  ["nc85_permutations", "Backtracking", v273.run],
  ["nc86_subsets_ii", "Counting", v274.run],
  ["nc86_subsets_ii", "Backtracking", v275.run],
  ["nc87_combination_sum_ii", "Brute Force", v276.run],
  ["nc87_combination_sum_ii", "Backtracking", v277.run],
  ["nc88_word_search", "Backtracking", v278.run],
  ["nc88_word_search", "Pruned Backtracking", v279.run],
  ["nc89_palindrome_partitioning", "Backtracking", v280.run],
  ["nc89_palindrome_partitioning", "DP + Backtracking", v281.run],
  ["nc90_letter_combinations", "Iterative", v282.run],
  ["nc90_letter_combinations", "Recursion", v283.run],
  ["nc91_n_queens", "Brute Force", v284.run],
  ["nc91_n_queens", "Backtracking", v285.run],
  ["nc92_unique_paths", "Space-Saving DP", v286.run],
  ["nc92_unique_paths", "Math", v287.run],
  ["nc93_longest_common_subsequence", "Top-Down Memo", v288.run],
  ["nc93_longest_common_subsequence", "Space-Saving DP", v289.run],
  ["nc94_coin_change_ii", "Top-Down Memo", v290.run],
  ["nc94_coin_change_ii", "Bottom-Up DP", v291.run],
  ["nc95_target_sum", "Bottom-Up DP", v292.run],
  ["nc95_target_sum", "Subset Sum", v293.run],
  ["nc96_stock_with_cooldown", "Top-Down Memo", v294.run],
  ["nc96_stock_with_cooldown", "State Machine DP", v295.run],
  ["nc97_interleaving_string", "Top-Down Memo", v296.run],
  ["nc97_interleaving_string", "Space-Saving DP", v297.run],
  ["nc98_longest_increasing_path", "Sort + DP", v298.run],
  ["nc98_longest_increasing_path", "DFS + Memo", v299.run],
  ["nc99_distinct_subsequences", "Top-Down Memo", v300.run],
  ["nc99_distinct_subsequences", "Space-Saving DP", v301.run],
];

const failures: string[] = [];
for (const [module, label, run] of VARIANTS) {
  let cases: Case[];
  try {
    cases = run();
  } catch (error) {
    failures.push(`${module} [${label}] threw ${error}`);
    continue;
  }
  if (cases.length === 0) {
    failures.push(`${module} [${label}] harness produced no cases`);
  }
  for (const [name, expected, actual] of cases) {
    if (expected !== actual) {
      failures.push(`${module} [${label}] ${name}: expected ${expected}, got ${actual}`);
    }
  }
}
for (const failure of failures) console.log("FAIL " + failure);
console.log(`${VARIANTS.length} TypeScript variants checked, ${failures.length} failures`);
if (failures.length > 0) process.exit(1);
